# -*- coding: utf-8 -*-
"""Localized About/FAQ content for the 28 non-English pages (English lives on the root).

Each entry: h2 / p1 / p2 / lh / lang_intro / cur_intro / cur_summary / faq_h / faqs (6 x [q, a]) / disc.
p2 uses {F} {E} {W} placeholders for the Frankfurter / ExchangeRate-API / Fawaz Currency API links.
"""

LINKS = {
    "F": '<a href="https://frankfurter.dev/" rel="noopener">Frankfurter</a>',
    "E": '<a href="https://www.exchangerate-api.com/" rel="noopener">ExchangeRate-API</a>',
    "W": '<a href="https://github.com/fawazahmed0/exchange-api" rel="noopener">Fawaz Currency API</a>',
}

CONTENT = {
    "tr": {
        "h2": "Fxverter Hakkında",
        "p1": "Fxverter, tarayıcınızda tamamen çalışan ücretsiz ve açık kaynaklı bir çevrimiçi döviz çeviricidir: 141 dünya para birimi için canlı kurlar sunar; API anahtarı, kayıt ve kurulum gerektirmez — web sitesini tarayıcınızda açın ve hemen çevirmeye başlayın.",
        "p2": "Kurlar, dilediğiniz an geçiş yapabileceğiniz üç halka açık kaynaktan gelir: {F} (Avrupa Merkez Bankası referans kurları), {E} ve {W}. Kurlar oturum başına önbelleğe alınır; 29 arayüz dili otomatik algılanır, Arapça ve Farsça için sağdan sola destek içerir.",
        "lh": "Desteklenen diller ve para birimleri",
        "lang_intro": "Arayüz 29 dilde gelir:",
        "cur_intro": "141 para birimi için canlı kur mevcuttur, açılır menülerde doğrudan arayabilirsiniz. Kullanılabilirlik seçilen veri kaynağına bağlıdır — eksik çiftler otomatik olarak diğer kaynaktan alınır:",
        "cur_summary": "Tüm para birimi listesini görüntüle",
        "faq_h": "Sık sorulan sorular",
        "faqs": [
            ["Bu döviz çevirici ücretsiz mi?", "Evet. Fxverter, MIT lisansıyla tamamen ücretsiz ve açık kaynaklıdır. API anahtarı, kayıt ve takip yoktur."],
            ["Kurlar ne kadar doğru?", "Kurlar, ücretsiz herkese açık API'lerden gelen gösterge niteliğinde referans kurlarıdır (Frankfurter üzerinden ECB, ExchangeRate-API, Fawaz). Günlük güncellenir ve hızlı referans için uygundur; işlem yapmadan önce bankanızla doğrulayın."],
            ["Hangi para birimleri destekleniyor?", "USD, EUR, GBP, JPY, CNY, TRY, INR ve CHF dahil 141 para birimi. Kullanılabilirlik veri kaynağına bağlıdır — eksik çiftler otomatik olarak başka bir kaynaktan alınır."],
            ["Kurulum gerekiyor mu veya hesap oluşturmalı mıyım?", "Hayır. Herhangi bir modern tarayıcıda — masaüstünde veya mobilde — web sitesini açın ve hemen çevirmeye başlayın. Kurulum da hesap da gerekmez."],
            ["Hangi dilleri destekliyor?", "Otomatik algılama ile 29 dil; Arapça ve Farsça için sağdan sola tam destek."],
            ["Verilerimi takip ediyor mu?", "Hayır. Tüm dönüşümler tarayıcınızda yerel olarak çalışır — hesap yok, takip çerezi yok, yalnızca herkese açık kur API'lerine anonim istekler vardır."],
        ],
        "disc": "Yasal uyarı: tüm kurlar yalnızca göstergedir; banka transferi, resmi fatura veya muhasebe için kullanılmamalıdır. İşlem öncesi bankanızla doğrulayın. © 2026 Seyyid Kadir · MIT Lisansı.",
    },
    "de": {
        "h2": "Über Fxverter",
        "p1": "Fxverter ist ein kostenloser, Open-Source-Währungsrechner, der vollständig im Browser läuft: live Wechselkurse für 141 Weltwährungen, ohne API-Schlüssel, ohne Anmeldung, ohne Installation — einfach die Website im Browser öffnen und losrechnen.",
        "p2": "Die Kurse stammen aus drei öffentlich verfügbaren Quellen, zwischen denen Sie jederzeit wechseln können: {F} (EZB-Referenzkurse), {E} und {W}. Kurse werden pro Sitzung zwischengespeichert; 29 Oberflächensprachen werden automatisch erkannt, einschließlich Rechts-nach-links für Arabisch und Persisch.",
        "lh": "Sprachen & Währungen",
        "lang_intro": "Die Oberfläche gibt es in 29 Sprachen:",
        "cur_intro": "Live-Kurse für 141 Währungen, direkt in den Dropdowns durchsuchbar. Die Verfügbarkeit hängt von der gewählten Datenquelle ab — fehlende Paare werden automatisch aus einer anderen Quelle geladen:",
        "cur_summary": "Vollständige Währungsliste anzeigen",
        "faq_h": "Häufige Fragen",
        "faqs": [
            ["Ist dieser Währungsrechner kostenlos?", "Ja. Fxverter ist komplett kostenlos und Open Source (MIT-Lizenz). Kein API-Schlüssel, keine Anmeldung, kein Tracking."],
            ["Wie genau sind die Wechselkurse?", "Es sind indikative Referenzkurse aus kostenlosen öffentlichen APIs (EZB über Frankfurter, ExchangeRate-API, Fawaz), täglich aktualisiert — ideal als schnelle Orientierung; bitte vor Transaktionen mit Ihrer Bank prüfen."],
            ["Welche Währungen werden unterstützt?", "141 Währungen, darunter USD, EUR, GBP, JPY, CNY, TRY, INR und CHF. Die Verfügbarkeit hängt von der Datenquelle ab — fehlende Paare werden automatisch aus einer anderen Quelle geladen."],
            ["Muss ich etwas installieren oder ein Konto anlegen?", "Nein. Öffnen Sie die Website einfach in einem modernen Browser — am Desktop oder mobil — und legen Sie los. Nichts zu installieren, kein Konto nötig."],
            ["Welche Sprachen werden unterstützt?", "29 Sprachen mit automatischer Erkennung, einschließlich Rechts-nach-links für Arabisch und Persisch."],
            ["Werden meine Daten verfolgt?", "Nein. Alle Umrechnungen laufen lokal im Browser — keine Konten, keine Tracking-Cookies, nur anonyme Anfragen an die öffentlichen Kurs-APIs."],
        ],
        "disc": "Haftungshinweis: alle Kurse sind nur Richtwerte und nicht für Banküberweisungen, offizielle Rechnungen oder Buchhaltung bestimmt. Bitte vor Transaktionen mit Ihrer Bank prüfen. © 2026 Seyyid Kadir · MIT-Lizenz.",
    },
    "fr": {
        "h2": "À propos de Fxverter",
        "p1": "Fxverter est un convertisseur de devises en ligne gratuit et open source qui fonctionne entièrement dans votre navigateur : taux de change en direct pour 141 devises mondiales, sans clé API, sans inscription, sans installation — ouvrez simplement le site dans votre navigateur et convertissez.",
        "p2": "Les taux proviennent de trois sources publiques entre lesquelles vous pouvez basculer à tout moment : {F} (taux de référence de la BCE), {E} et la {W}. Les taux sont mis en cache par session ; 29 langues d'interface sont détectées automatiquement, avec prise en charge de droite à gauche pour l'arabe et le persan.",
        "lh": "Langues & devises",
        "lang_intro": "L'interface existe en 29 langues :",
        "cur_intro": "Les taux sont disponibles pour 141 devises, avec recherche directe dans les menus déroulants. La disponibilité dépend de la source choisie — les paires manquantes sont récupérées automatiquement auprès d'une autre source :",
        "cur_summary": "Voir la liste complète des devises",
        "faq_h": "Questions fréquentes",
        "faqs": [
            ["Ce convertisseur est-il gratuit ?", "Oui. Fxverter est entièrement gratuit et open source (licence MIT). Sans clé API, sans inscription, sans tracking."],
            ["Les taux sont-ils fiables ?", "Ce sont des taux de référence indicatifs issus d'API publiques gratuites (BCE via Frankfurter, ExchangeRate-API, Fawaz), mis à jour quotidiennement — parfaits comme repère rapide ; vérifiez toujours auprès de votre banque avant une transaction."],
            ["Quelles devises sont prises en charge ?", "141 devises, dont USD, EUR, GBP, JPY, CNY, TRY, INR et CHF. La disponibilité dépend de la source — les paires manquantes sont récupérées automatiquement ailleurs."],
            ["Faut-il installer quelque chose ou créer un compte ?", "Non. Ouvrez simplement le site dans n'importe quel navigateur moderne — sur ordinateur ou mobile — et convertissez aussitôt. Rien à installer, aucun compte requis."],
            ["Quelles langues sont disponibles ?", "29 langues avec détection automatique, dont le support de droite à gauche pour l'arabe et le persan."],
            ["Mes données sont-elles suivies ?", "Non. Toutes les conversions s'exécutent localement dans votre navigateur — pas de comptes, pas de cookies de suivi, seulement des requêtes anonymes vers les API publiques."],
        ],
        "disc": "Avertissement : tous les taux sont indicatifs et ne doivent pas servir aux virements bancaires, factures officielles ou comptabilité. Vérifiez toujours auprès de votre banque. © 2026 Seyyid Kadir · Licence MIT.",
    },
    "es": {
        "h2": "Sobre Fxverter",
        "p1": "Fxverter es un conversor de divisas online gratuito y de código abierto que funciona íntegramente en tu navegador: tipos de cambio en vivo para 141 divisas, sin clave API, sin registro, sin instalación — simplemente abre la web en tu navegador y empieza a convertir.",
        "p2": "Los tipos provienen de tres fuentes públicas entre las que puedes cambiar en cualquier momento: {F} (tipos de referencia del BCE), {E} y la {W}. Los tipos se guardan en caché por sesión; 29 idiomas de interfaz se detectan automáticamente, incluido el soporte de derecha a izquierda para árabe y persa.",
        "lh": "Idiomas y divisas",
        "lang_intro": "La interfaz está disponible en 29 idiomas:",
        "cur_intro": "Hay tipos de cambio para 141 divisas, con búsqueda directa en los desplegables. La disponibilidad depende de la fuente elegida — los pares que falten se obtienen automáticamente de otra fuente:",
        "cur_summary": "Ver la lista completa de divisas",
        "faq_h": "Preguntas frecuentes",
        "faqs": [
            ["¿Este conversor de divisas es gratis?", "Sí. Fxverter es totalmente gratuito y de código abierto (licencia MIT). Sin clave API, sin registro y sin rastreo."],
            ["¿Qué precisión tienen los tipos de cambio?", "Son tipos de referencia indicativos de APIs públicas gratuitas (BCE vía Frankfurter, ExchangeRate-API, Fawaz), actualizados a diario — perfectos como referencia rápida; verifica siempre con tu banco antes de operar."],
            ["¿Qué divisas están soportadas?", "141 divisas, incluidas USD, EUR, GBP, JPY, CNY, TRY, INR y CHF. La disponibilidad depende de la fuente — los pares que falten se obtienen automáticamente de otra."],
            ["¿Hay que instalar algo o crear una cuenta?", "No. Abre la web en cualquier navegador moderno — ordenador o móvil — y convierte al instante. Nada que instalar y sin cuenta."],
            ["¿Qué idiomas admite?", "29 idiomas con detección automática, incluida la escritura de derecha a izquierda para árabe y persa."],
            ["¿Rastrea mis datos?", "No. Todas las conversiones se ejecutan localmente en tu navegador — sin cuentas, sin cookies de rastreo, solo peticiones anónimas a las API públicas de tipos."],
        ],
        "disc": "Aviso: todos los tipos son indicativos y no deben usarse para transferencias bancarias, facturas oficiales ni contabilidad. Verifica siempre con tu banco. © 2026 Seyyid Kadir · Licencia MIT.",
    },
    "pt": {
        "h2": "Sobre o Fxverter",
        "p1": "O Fxverter é um conversor de moedas online gratuito e de código aberto que funciona inteiramente no seu navegador: taxas de câmbio ao vivo para 141 moedas mundiais, sem chave de API, sem cadastro, sem instalação — basta abrir o site no navegador e começar a converter.",
        "p2": "As taxas vêm de três fontes públicas entre as quais você pode alternar a qualquer momento: {F} (taxas de referência do BCE), {E} e {W}. As taxas são armazenadas em cache por sessão; 29 idiomas de interface são detectados automaticamente, incluindo suporte da direita para a esquerda para árabe e persa.",
        "lh": "Idiomas e moedas",
        "lang_intro": "A interface está disponível em 29 idiomas:",
        "cur_intro": "Há taxas de câmbio para 141 moedas, com busca direta nos menus suspensos. A disponibilidade depende da fonte escolhida — os pares ausentes são obtidos automaticamente de outra fonte:",
        "cur_summary": "Ver a lista completa de moedas",
        "faq_h": "Perguntas frequentes",
        "faqs": [
            ["Este conversor de moedas é gratuito?", "Sim. O Fxverter é totalmente gratuito e de código aberto (licença MIT). Sem chave de API, sem cadastro, sem rastreamento."],
            ["Quão precisas são as taxas de câmbio?", "São taxas de referência indicativas de APIs públicas gratuitas (BCE via Frankfurter, ExchangeRate-API, Fawaz), atualizadas diariamente — ótimas como referência rápida; sempre confirme com seu banco antes de operar."],
            ["Quais moedas são suportadas?", "141 moedas, incluindo USD, EUR, GBP, JPY, CNY, TRY, INR e CHF. A disponibilidade depende da fonte — pares ausentes são obtidos automaticamente de outra."],
            ["Preciso instalar algo ou criar uma conta?", "Não. Basta abrir o site em qualquer navegador moderno — no computador ou no celular — e converter imediatamente. Nada para instalar e sem cadastro."],
            ["Quais idiomas são suportados?", "29 idiomas com detecção automática, incluindo suporte da direita para a esquerda para árabe e persa."],
            ["Você rastreia meus dados?", "Não. Todas as conversões rodam localmente no seu navegador — sem contas, sem cookies de rastreamento, apenas requisições anônimas às APIs públicas."],
        ],
        "disc": "Aviso: todas as taxas são indicativas e não devem ser usadas para transferências bancárias, notas fiscais oficiais ou contabilidade. Confirme sempre com seu banco. © 2026 Seyyid Kadir · Licença MIT.",
    },
    "ru": {
        "h2": "О конвертере Fxverter",
        "p1": "Fxverter — бесплатный онлайн-конвертер валют с открытым кодом, работающий полностью в вашем браузере: актуальные курсы для 141 мировых валют, без API-ключа, без регистрации, без установки — просто откройте сайт в браузере и начинайте конвертировать.",
        "p2": "Курсы поступают из трёх открытых источников, между которыми можно переключаться в любой момент: {F} (референсные курсы ЕЦБ), {E} и {W}. Курсы кэшируются на время сессии; 29 языков интерфейса определяются автоматически, включая поддержку письма справа налево для арабского и персидского.",
        "lh": "Языки и валюты",
        "lang_intro": "Интерфейс доступен на 29 языках:",
        "cur_intro": "Курсы доступны для 141 валют, с поиском прямо в выпадающих списках. Доступность зависит от выбранного источника — недостающие пары автоматически берутся из другого источника:",
        "cur_summary": "Показать полный список валют",
        "faq_h": "Частые вопросы",
        "faqs": [
            ["Этот конвертер бесплатный?", "Да. Fxverter полностью бесплатен и открыт (лицензия MIT). Без API-ключа, без регистрации, без отслеживания."],
            ["Насколько точны курсы?", "Это индикативные референс-курсы из бесплатных открытых API (ЕЦБ через Frankfurter, ExchangeRate-API, Fawaz), обновляются ежедневно — отлично для быстрой справки; перед сделками сверяйтесь с банком."],
            ["Какие валюты поддерживаются?", "141 валюта, включая USD, EUR, GBP, JPY, CNY, TRY, INR и CHF. Доступность зависит от источника — недостающие пары автоматически берутся из другого."],
            ["Нужно ли что-то устанавливать или создавать аккаунт?", "Нет. Просто откройте сайт в любом современном браузере — на компьютере или телефоне — и конвертируйте сразу. Ничего устанавливать не нужно, аккаунт не требуется."],
            ["Какие языки поддерживаются?", "29 языков с автоопределением, включая поддержку справа налево для арабского и персидского."],
            ["Отслеживаете ли вы мои данные?", "Нет. Все конвертации выполняются локально в браузере — без аккаунтов и cookie для отслеживания, только анонимные запросы к открытым API курсов."],
        ],
        "disc": "Дисклеймер: все курсы носят ориентировочный характер и не предназначены для банковских переводов, официальных счетов или бухгалтерии. Перед операциями сверяйтесь с банком. © 2026 Seyyid Kadir · Лицензия MIT.",
    },
    "zh": {
        "h2": "关于 Fxverter",
        "p1": "Fxverter 是一款免费开源的在线货币换算工具，完全在浏览器中运行：提供 141 种世界货币的实时汇率，无需 API 密钥、无需注册、无需安装——打开网址即可直接使用。",
        "p2": "汇率来自三个可随时切换的公开数据源：{F}（欧洲央行参考汇率）、{E} 和 {W}。汇率按会话缓存，界面支持 29 种语言自动检测，其中阿拉伯语和波斯语支持从右到左排版。",
        "lh": "支持的语言与币种",
        "lang_intro": "界面提供 29 种语言：",
        "cur_intro": "支持 141 种货币的实时汇率换算，可直接在下拉框中搜索。实际可用性取决于所选数据源——当前源缺失的币种会自动从其他数据源获取：",
        "cur_summary": "查看完整的货币列表",
        "faq_h": "常见问题",
        "faqs": [
            ["这个货币换算器是免费的吗？", "是的。Fxverter 完全免费、开源（MIT 许可证），无需 API 密钥，无需注册，也没有任何追踪。"],
            ["汇率有多准确？", "汇率来自免费公开 API 的参考汇率（欧洲央行 via Frankfurter、ExchangeRate-API、Fawaz），每日更新，适合快速参考；进行实际交易前请务必与银行核实。"],
            ["支持哪些货币？", "支持包括美元、欧元、英镑、日元、人民币、土耳其里拉、印度卢比和瑞士法郎在内的 141 种货币。可用性取决于数据源——缺失的币种会自动从其他源获取。"],
            ["需要安装软件或注册账号吗？", "不需要。在任意现代浏览器（电脑或手机）中打开网址即可直接换算，无需安装任何软件，也无需注册账号。"],
            ["支持哪些语言？", "29 种界面语言，自动检测浏览器语言，阿拉伯语和波斯语支持从右到左排版。"],
            ["会追踪我的数据吗？", "不会。所有换算都在你的浏览器本地完成——没有账号体系、没有追踪 Cookie，只有对公开汇率 API 的匿名请求。"],
        ],
        "disc": "免责声明：所有汇率仅供参考，不得用于银行转账、正式发票或会计用途。交易前请务必与银行核实。© 2026 Seyyid Kadir · MIT 许可证。",
    },
    "ja": {
        "h2": "Fxverter について",
        "p1": "Fxverter は、ブラウザ内で完全に動作する無料・オープンソースの通貨コンバーターです。141 の世界通貨のリアルタイム為替レートを表示し、API キー不要・登録不要・インストール不要 — ウェブサイトをブラウザで開くだけですぐに使えます。",
        "p2": "レートはいつでも切り替えできる 3 つの公開データソースから取得します：{F}（欧州中央銀行の参照レート）、{E}、{W}。レートはセッションごとにキャッシュされ、29 の UI 言語を自動判別します（アラビア語・ペルシア語は右から左表示に対応）。",
        "lh": "対応言語と通貨",
        "lang_intro": "インターフェースは 29 言語を提供：",
        "cur_intro": "141 通貨のリアルタイムレートに対応し、ドロップダウンから直接検索できます。利用可否は選択したデータソースによって異なり、不足しているペアは自動的に他のソースから取得します：",
        "cur_summary": "通貨の全リストを見る",
        "faq_h": "よくある質問",
        "faqs": [
            ["この通貨コンバーターは無料ですか？", "はい。Fxverter は MIT ライセンスの完全無料・オープンソースです。API キーも登録もトラッキングもありません。"],
            ["為替レートの精度は？", "無料の公開 API（Frankfurter 経由の ECB、ExchangeRate-API、Fawaz）による参考レートで、毎日更新されます。迅速な確認に最適ですが、取引前には必ず銀行でご確認ください。"],
            ["どの通貨に対応していますか？", "USD、EUR、GBP、JPY、CNY、TRY、INR、CHF など 141 通貨。対応状況はデータソースにより異なり、不足ペアは自動的に他のソースから取得します。"],
            ["インストールやアカウント登録は必要ですか？", "必要ありません。パソコンでもスマートフォンでも、モダンブラウザでサイトを開けばすぐに使えます。インストールも登録も不要です。"],
            ["対応言語は？", "自動判別対応の 29 言語。アラビア語・ペルシア語は右から左の表示に完全対応。"],
            ["データは追跡されますか？", "いいえ。変換はすべてブラウザ内でローカルに実行されます — アカウントも追跡 Cookie もなく、公開レート API への匿名リクエストのみです。"],
        ],
        "disc": "免責事項：すべてのレートは参考値であり、銀行送金・正式な請求・会計には使用しないでください。取引前には必ず銀行等でご確認ください。© 2026 Seyyid Kadir · MIT ライセンス。",
    },
    "ko": {
        "h2": "Fxverter 소개",
        "p1": "Fxverter는 브라우저에서 완전히 동작하는 무료 오픈소스 통화 변환기입니다. 141개 세계 통화의 실시간 환율을 제공하며 API 키, 가입, 설치가 필요 없습니다 — 웹사이트를 브라우저에서 열기만 하면 바로 사용할 수 있습니다.",
        "p2": "환율은 언제든 전환할 수 있는 세 가지 공개 소스에서 제공됩니다: {F}(유럽중앙은행 기준 환율), {E}, {W}. 환율은 세션별로 캐시되며 29개 UI 언어가 자동 감지되고, 아랍어와 페르시아어는 오른쪽에서 왼쪽 쓰기를 지원합니다.",
        "lh": "지원 언어 및 통화",
        "lang_intro": "인터페이스는 29개 언어를 제공합니다:",
        "cur_intro": "141개 통화의 실시간 환율을 지원하며 드롭다운에서 바로 검색할 수 있습니다. 사용 가능 여부는 선택한 데이터 소스에 따라 다르며, 누락된 쌍은 다른 소스에서 자동으로 가져옵니다:",
        "cur_summary": "전체 통화 목록 보기",
        "faq_h": "자주 묻는 질문",
        "faqs": [
            ["이 환율 계산기는 무료인가요?", "네. Fxverter는 MIT 라이선스의 완전 무료 오픈소스입니다. API 키도, 가입도, 추적도 없습니다."],
            ["환율은 얼마나 정확한가요?", "무료 공개 API(Frankfurter를 통한 ECB, ExchangeRate-API, Fawaz)의 참고용 시세로 매일 업데이트됩니다. 빠른 참조에는 적합하지만 거래 전 반드시 은행에 확인하세요."],
            ["어떤 통화를 지원하나요?", "USD, EUR, GBP, JPY, CNY, TRY, INR, CHF 등 141개 통화. 데이터 소스에 따라 다르며 누락된 쌍은 자동으로 다른 소스에서 가져옵니다."],
            ["설치나 계정 만들기가 필요한가요?", "아니요. PC든 모바일이든 최신 브라우저에서 웹사이트를 열기만 하면 바로 변환할 수 있습니다. 설치도 계정도 필요 없습니다."],
            ["어떤 언어를 지원하나요?", "자동 감지되는 29개 언어. 아랍어와 페르시아어는 오른쪽에서 왼쪽 쓰기를 완전히 지원합니다."],
            ["제 데이터를 추적하나요?", "아니요. 모든 변환은 브라우저에서 로컬로 실행됩니다 — 계정도 추적 쿠키도 없고 공개 환율 API에 대한 익명 요청만 있습니다."],
        ],
        "disc": "면책 조항: 모든 환율은 참고용이며 은행 이체, 공식 송장, 회계 용도로 사용해서는 안 됩니다. 거래 전 반드시 은행에 확인하세요. © 2026 Seyyid Kadir · MIT 라이선스.",
    },
    "ar": {
        "h2": "عن Fxverter",
        "p1": "Fxverter هو محوّل عملات مجاني مفتوح المصدر يعمل بالكامل داخل متصفحك: أسعار صرف مباشرة لـ 141 عملة عالمية، بدون مفتاح API، بدون تسجيل، بدون تثبيت — افتح الموقع في متصفحك وابدأ التحويل فورًا.",
        "p2": "تأتي الأسعار من ثلاثة مصادر عامة يمكنك التبديل بينها في أي وقت: {F} (أسعار البنك المركزي الأوروبي المرجعية) و{E} و{W}. تُخزَّن الأسعار مؤقتًا لكل جلسة، وتُكتشف 29 لغة للواجهة تلقائيًا، مع دعم الكتابة من اليمين إلى اليسار للعربية والفارسية.",
        "lh": "اللغات والعملات",
        "lang_intro": "الواجهة متوفرة بـ 29 لغة:",
        "cur_intro": "تتوفر أسعار الصرف لـ 141 عملة، مع إمكانية البحث مباشرة في القوائم المنسدلة. يعتمد التوفر على المصدر المختار — الأزواج الناقصة تُجلب تلقائيًا من مصدر آخر:",
        "cur_summary": "عرض قائمة العملات الكاملة",
        "faq_h": "الأسئلة الشائعة",
        "faqs": [
            ["هل هذا المحول مجاني؟", "نعم. Fxverter مجاني تمامًا ومفتوح المصدر بموجب رخصة MIT. بدون مفتاح API، بدون تسجيل، بدون تتبع."],
            ["ما مدى دقة أسعار الصرف؟", "هي أسعار مرجعية إرشادية من واجهات برمجية عامة مجانية (البنك المركزي الأوروبي عبر Frankfurter و ExchangeRate-API و Fawaz)، تُحدَّث يوميًا — مناسبة كمرجع سريع؛ تحقق دائمًا من بنكك قبل أي معاملة."],
            ["ما العملات المدعومة؟", "141 عملة منها USD و EUR و GBP و JPY و CNY و TRY و INR و CHF. يعتمد التوفر على المصدر — الأزواج الناقصة تُجلب تلقائيًا من مصدر آخر."],
            ["هل أحتاج لتثبيت شيء أو إنشاء حساب؟", "لا. افتح الموقع في أي متصفح حديث — على الحاسوب أو الهاتف — وابدأ التحويل فورًا. لا تثبيت ولا حساب."],
            ["ما اللغات المدعومة؟", "29 لغة مع كشف تلقائي، ودعم كامل للكتابة من اليمين إلى اليسار للعربية والفارسية."],
            ["هل تتبعون بياناتي؟", "لا. تُنفَّذ جميع التحويلات محليًا في متصفحك — لا حسابات، لا كوكيز تتبع، فقط طلبات مجهولة إلى واجهات الأسعار العامة."],
        ],
        "disc": "تنبيه: جميع الأسعار إرشادية فقط ويجب عدم استخدامها للتحويلات البنكية أو الفواتير الرسمية أو المحاسبة. تحقق دائمًا من بنكك. © 2026 Seyyid Kadir · رخصة MIT.",
    },
    "hi": {
        "h2": "Fxverter के बारे में",
        "p1": "Fxverter एक मुफ़्त, ओपन-सोर्स ऑनलाइन मुद्रा परिवर्तक है जो पूरी तरह आपके ब्राउज़र में चलता है: 141 विश्व मुद्राओं के लाइव विनिमय दर, बिना API कुंजी, बिना साइन-अप, बिना इंस्टॉलेशन — बस वेबसाइट ब्राउज़र में खोलें और रूपांतरण शुरू करें।",
        "p2": "रेट तीन सार्वजनिक स्रोतों से आते हैं जिनके बीच आप कभी भी बदल सकते हैं: {F} (ECB संदर्भ दरें), {E} और {W}। रेट प्रति सेशन कैश होते हैं; 29 इंटरफ़ेस भाषाएँ स्वतः पहचानी जाती हैं, जिनमें अरबी और फ़ारसी के लिए दाएँ-से-बाएँ समर्थन शामिल है।",
        "lh": "भाषाएँ और मुद्राएँ",
        "lang_intro": "इंटरफ़ेस 29 भाषाओं में उपलब्ध है:",
        "cur_intro": "141 मुद्राओं के लिए लाइव विनिमय दरें उपलब्ध हैं, जिन्हें ड्रॉपडाउन में सीधे खोजा जा सकता है। उपलब्धता चुने गए डेटा स्रोत पर निर्भर करती है — गायब जोड़े अन्य स्रोत से स्वतः लिए जाते हैं:",
        "cur_summary": "पूरी मुद्रा सूची देखें",
        "faq_h": "अक्सर पूछे जाने वाले प्रश्न",
        "faqs": [
            ["क्या यह मुद्रा परिवर्तक मुफ़्त है?", "हाँ। Fxverter MIT लाइसेंस के तहत पूरी तरह मुफ़्त और ओपन सोर्स है। कोई API कुंजी नहीं, कोई साइन-अप नहीं, कोई ट्रैकिंग नहीं।"],
            ["विनिमय दरें कितनी सटीक हैं?", "ये मुफ़्त सार्वजनिक API (Frankfurter द्वारा ECB, ExchangeRate-API, Fawaz) से ली गई संकेतात्मक संदर्भ दरें हैं, रोज़ अपडेट होती हैं — त्वरित संदर्भ के लिए बेहतरीन; लेन-देन से पहले अपने बैंक से जाँच लें।"],
            ["कौन सी मुद्राएँ समर्थित हैं?", "USD, EUR, GBP, JPY, CNY, TRY, INR और CHF सहित 141 मुद्राएँ। उपलब्धता डेटा स्रोत पर निर्भर है — गायब जोड़े अन्य स्रोत से स्वतः लिए जाते हैं।"],
            ["क्या कुछ इंस्टॉल करना या खाता बनाना ज़रूरी है?", "नहीं। किसी भी आधुनिक ब्राउज़र में — डेस्कटॉप या मोबाइल पर — वेबसाइट खोलें और तुरंत रूपांतरण शुरू करें। कुछ इंस्टॉल नहीं, कोई खाता नहीं।"],
            ["कौन सी भाषाएँ समर्थित हैं?", "स्वतः पहचान वाली 29 भाषाएँ, अरबी और फ़ारसी के लिए दाएँ-से-बाएँ पूर्ण समर्थन।"],
            ["क्या मेरा डेटा ट्रैक होता है?", "नहीं। सभी रूपांतरण आपके ब्राउज़र में लोकल चलते हैं — कोई खाता नहीं, कोई ट्रैकिंग कुकी नहीं, केवल सार्वजनिक रेट API के लिए गुमनाम अनुरोध।"],
        ],
        "disc": "अस्वीकरण: सभी दरें केवल संकेतात्मक हैं और बैंक ट्रांसफर, आधिकारिक इनवॉइस या लेखांकन के लिए उपयोग नहीं की जानी चाहिए। लेन-देन से पहले अपने बैंक से जाँचें। © 2026 Seyyid Kadir · MIT लाइसेंस।",
    },
    "id": {
        "h2": "Tentang Fxverter",
        "p1": "Fxverter adalah konverter mata uang online gratis dan open source yang berjalan sepenuhnya di browser Anda: kurs real-time untuk 141 mata uang dunia, tanpa kunci API, tanpa pendaftaran, tanpa instalasi — cukup buka situsnya di browser dan langsung konversi.",
        "p2": "Kurs berasal dari tiga sumber publik yang bisa Anda ganti kapan saja: {F} (kurs referensi ECB), {E}, dan {W}. Kurs di-cache per sesi; 29 bahasa antarmuka terdeteksi otomatis, termasuk dukungan kanan-ke-kiri untuk bahasa Arab dan Persia.",
        "lh": "Bahasa & mata uang",
        "lang_intro": "Antarmuka tersedia dalam 29 bahasa:",
        "cur_intro": "Tersedia kurs real-time untuk 141 mata uang, dapat dicari langsung di dropdown. Ketersediaan bergantung pada sumber data yang dipilih — pasangan yang hilang diambil otomatis dari sumber lain:",
        "cur_summary": "Lihat daftar lengkap mata uang",
        "faq_h": "Pertanyaan umum",
        "faqs": [
            ["Apakah konverter ini gratis?", "Ya. Fxverter sepenuhnya gratis dan open source di bawah lisensi MIT. Tanpa kunci API, tanpa pendaftaran, tanpa pelacakan."],
            ["Seberapa akurat kursnya?", "Ini kurs referensi indikatif dari API publik gratis (ECB via Frankfurter, ExchangeRate-API, Fawaz), diperbarui harian — bagus sebagai referensi cepat; selalu konfirmasi ke bank Anda sebelum bertransaksi."],
            ["Mata uang apa saja yang didukung?", "141 mata uang termasuk USD, EUR, GBP, JPY, CNY, TRY, INR, dan CHF. Ketersediaan bergantung pada sumber — pasangan yang hilang diambil otomatis dari sumber lain."],
            ["Apakah perlu instalasi atau membuat akun?", "Tidak. Cukup buka situsnya di browser modern mana pun — di desktop atau ponsel — dan langsung konversi. Tanpa instalasi, tanpa akun."],
            ["Bahasa apa saja yang didukung?", "29 bahasa dengan deteksi otomatis, termasuk dukungan kanan-ke-kiri untuk Arab dan Persia."],
            ["Apakah data saya dilacak?", "Tidak. Semua konversi berjalan lokal di browser Anda — tanpa akun, tanpa cookie pelacakan, hanya permintaan anonim ke API kurs publik."],
        ],
        "disc": "Penafian: semua kurs bersifat indikatif dan tidak boleh digunakan untuk transfer bank, faktur resmi, atau akuntansi. Selalu verifikasi ke bank Anda. © 2026 Seyyid Kadir · Lisensi MIT.",
    },
    "ms": {
        "h2": "Tentang Fxverter",
        "p1": "Fxverter ialah penukar mata wang dalam talian percuma dan sumber terbuka yang berjalan sepenuhnya dalam pelayar anda: kadar semasa untuk 141 mata wang dunia, tanpa kunci API, tanpa pendaftaran, tanpa pemasangan — cukup buka laman web dalam pelayar dan mula menukar.",
        "p2": "Kadar datang daripada tiga sumber awam yang boleh anda tukar pada bila-bila masa: {F} (kadar rujukan ECB), {E} dan {W}. Kadar di-cache setiap sesi; 29 bahasa antara muka dikesan secara automatik, termasuk sokongan kanan-ke-kiri untuk bahasa Arab dan Parsi.",
        "lh": "Bahasa & mata wang",
        "lang_intro": "Antara muka tersedia dalam 29 bahasa:",
        "cur_intro": "Kadar semasa tersedia untuk 141 mata wang, boleh dicari terus dalam menu lungsur. Ketersediaan bergantung pada sumber data pilihan — pasangan yang tiada diambil secara automatik daripada sumber lain:",
        "cur_summary": "Lihat senarai penuh mata wang",
        "faq_h": "Soalan lazim",
        "faqs": [
            ["Adakah penukar ini percuma?", "Ya. Fxverter adalah percuma sepenuhnya dan sumber terbuka di bawah lesen MIT. Tanpa kunci API, tanpa pendaftaran, tanpa penjejakan."],
            ["Seberapa tepat kadar ini?", "Ia adalah kadar rujukan indikatif daripada API awam percuma (ECB melalui Frankfurter, ExchangeRate-API, Fawaz), dikemas kini setiap hari — sesuai sebagai rujukan pantas; sahkan dengan bank anda sebelum berurus niaga."],
            ["Mata wang apa yang disokong?", "141 mata wang termasuk USD, EUR, GBP, JPY, CNY, TRY, INR dan CHF. Ketersediaan bergantung pada sumber — pasangan yang tiada diambil automatik daripada sumber lain."],
            ["Perlu pasang apa-apa atau buat akaun?", "Tidak. Cukup buka laman web dalam mana-mana pelayar moden — di desktop atau telefon — dan mula menukar terus. Tanpa pemasangan, tanpa akaun."],
            ["Bahasa apa yang disokong?", "29 bahasa dengan pengesanan automatik, termasuk sokongan kanan-ke-kiri untuk Arab dan Parsi."],
            ["Adakah data saya dijejak?", "Tidak. Semua penukaran berjalan setempat dalam pelayar anda — tiada akaun, tiada kuki penjejakan, hanya permintaan tanpa nama ke API kadar awam."],
        ],
        "disc": "Penafian: semua kadar adalah indikatif sahaja dan tidak boleh digunakan untuk pemindahan bank, invois rasmi atau perakaunan. Sentiasa sahkan dengan bank anda. © 2026 Seyyid Kadir · Lesen MIT.",
    },
    "tl": {
        "h2": "Tungkol sa Fxverter",
        "p1": "Ang Fxverter ay isang libreng online na tagapagpalit ng pera na open source at gumagana nang buo sa iyong browser: live na exchange rates para sa 141 pera, walang API key, walang sign-up, walang installation — buksan lang ang website sa browser at magsimulang mag-convert.",
        "p2": "Ang mga rate ay mula sa tatlong publikong source na maaari mong palitan anumang oras: {F} (ECB reference rates), {E}, at {W}. Naka-cache ang mga rate kada session; 29 wika ng interface ang awtomatikong nadadetect, kasama ang right-to-left na suporta para sa Arabic at Persian.",
        "lh": "Mga wika at pera",
        "lang_intro": "Available ang interface sa 29 wika:",
        "cur_intro": "May live na rates para sa 141 pera, direktang mase-search sa mga dropdown. Nakadepende sa piniling data source ang availability — ang mga kulang na pair ay kusang kinukuha mula sa ibang source:",
        "cur_summary": "Tingnan ang buong listahan ng pera",
        "faq_h": "Mga madalas itanong",
        "faqs": [
            ["Libre ba itong currency converter?", "Oo. Ang Fxverter ay ganap na libre at open source sa ilalim ng MIT license. Walang API key, walang sign-up, walang tracking."],
            ["Gaano ka-accurate ang mga exchange rate?", "Mga indikatibong reference rate ang mga ito mula sa libreng public APIs (ECB via Frankfurter, ExchangeRate-API, Fawaz), ina-update araw-araw — sapat na bilang mabilisang sanggunian; laging kumpirmahin sa bangko bago mag-transact."],
            ["Anong mga pera ang suportado?", "141 pera kabilang ang USD, EUR, GBP, JPY, CNY, TRY, INR at CHF. Nakadepende sa data source ang availability — ang kulang na pair ay kusang kinukuha sa iba."],
            ["Kailangan bang mag-install o gumawa ng account?", "Hindi. Buksan lang ang website sa kahit anong modern browser — sa desktop o mobile — at magsimula agad. Walang i-i-install, walang kailangang account."],
            ["Anong mga wika ang suportado?", "29 wika na awtomatikong nadadetect, kasama ang buong right-to-left na suporta para sa Arabic at Persian."],
            ["Nitra-track ba nito ang data ko?", "Hindi. Lahat ng conversion ay tumatakbo nang lokal sa browser mo — walang accounts, walang tracking cookies, mga anonymous request lang sa public rate APIs."],
        ],
        "disc": "Paalala: lahat ng rate ay indikatibo lamang at hindi dapat gamitin sa bank transfers, opisyal na invoice o accounting. Laging kumpirmahin sa bangko. © 2026 Seyyid Kadir · MIT License.",
    },
    "it": {
        "h2": "Informazioni su Fxverter",
        "p1": "Fxverter è un convertitore di valute online gratuito e open source che funziona interamente nel tuo browser: tassi di cambio in tempo reale per 141 valute mondiali, senza chiave API, senza registrazione, senza installazione — basta aprire il sito nel browser e iniziare a convertire.",
        "p2": "I tassi provengono da tre fonti pubbliche tra cui passare in qualsiasi momento: {F} (tassi di riferimento BCE), {E} e {W}. I tassi sono memorizzati nella cache per sessione; 29 lingue dell'interfaccia vengono rilevate automaticamente, incluso il supporto da destra a sinistra per arabo e persiano.",
        "lh": "Lingue e valute",
        "lang_intro": "L'interfaccia è disponibile in 29 lingue:",
        "cur_intro": "I tassi sono disponibili per 141 valute, con ricerca diretta nei menu a tendina. La disponibilità dipende dalla fonte selezionata — le coppie mancanti vengono recuperate automaticamente da un'altra fonte:",
        "cur_summary": "Visualizza l'elenco completo delle valute",
        "faq_h": "Domande frequenti",
        "faqs": [
            ["Questo convertitore è gratuito?", "Sì. Fxverter è completamente gratuito e open source (licenza MIT). Senza chiave API, senza registrazione, senza tracciamento."],
            ["Quanto sono affidabili i tassi?", "Sono tassi di riferimento indicativi da API pubbliche gratuite (BCE tramite Frankfurter, ExchangeRate-API, Fawaz), aggiornati ogni giorno — ottimi come riferimento rapido; verifica sempre con la tua banca prima di operare."],
            ["Quali valute sono supportate?", "141 valute, tra cui USD, EUR, GBP, JPY, CNY, TRY, INR e CHF. La disponibilità dipende dalla fonte — le coppie mancanti vengono recuperate automaticamente altrove."],
            ["Devo installare qualcosa o creare un account?", "No. Apri il sito in qualsiasi browser moderno — su computer o mobile — e converti subito. Niente da installare e nessun account."],
            ["Quali lingue sono supportate?", "29 lingue con rilevamento automatico, incluso il supporto da destra a sinistra per arabo e persiano."],
            ["Tracciate i miei dati?", "No. Tutte le conversioni avvengono localmente nel browser — nessun account, nessun cookie di tracciamento, solo richieste anonime alle API pubbliche dei tassi."],
        ],
        "disc": "Avvertenza: tutti i tassi sono indicativi e non devono essere usati per bonifici, fatture ufficiali o contabilità. Verifica sempre con la tua banca. © 2026 Seyyid Kadir · Licenza MIT.",
    },
    "nl": {
        "h2": "Over Fxverter",
        "p1": "Fxverter is een gratis online valutaomrekenaar met open source die volledig in je browser draait: actuele wisselkoersen voor 141 wereldvaluta, zonder API-sleutel, zonder registratie, zonder installatie — open gewoon de website in je browser en begin met omrekenen.",
        "p2": "De koersen komen van drie openbare bronnen waartussen je op elk moment kunt schakelen: {F} (ECB-referentiekoersen), {E} en de {W}. Koersen worden per sessie gecacht; 29 interfacetalen worden automatisch gedetecteerd, inclusief rechts-naar-links ondersteuning voor Arabisch en Perzisch.",
        "lh": "Talen & valuta's",
        "lang_intro": "De interface is er in 29 talen:",
        "cur_intro": "Actuele koersen voor 141 valuta, direct doorzoekbaar in de dropdowns. De beschikbaarheid hangt af van de gekozen bron — ontbrekende paren worden automatisch uit een andere bron gehaald:",
        "cur_summary": "Volledige valutalijst bekijken",
        "faq_h": "Veelgestelde vragen",
        "faqs": [
            ["Is deze valutaomrekenaar gratis?", "Ja. Fxverter is volledig gratis en open source (MIT-licentie). Geen API-sleutel, geen registratie, geen tracking."],
            ["Hoe betrouwbaar zijn de koersen?", "Het zijn indicatieve referentiekoersen uit gratis openbare API's (ECB via Frankfurter, ExchangeRate-API, Fawaz), dagelijks bijgewerkt — prima als snel oriëntatiepunt; controleer altijd bij je bank voordat je transacteert."],
            ["Welke valuta's worden ondersteund?", "141 valuta's, waaronder USD, EUR, GBP, JPY, CNY, TRY, INR en CHF. De beschikbaarheid hangt van de bron af — ontbrekende paren worden automatisch elders vandaan gehaald."],
            ["Moet ik iets installeren of een account aanmaken?", "Nee. Open de website gewoon in een moderne browser — op desktop of mobiel — en reken meteen om. Niets te installeren, geen account nodig."],
            ["Welke talen worden ondersteund?", "29 talen met automatische detectie, inclusief rechts-naar-links voor Arabisch en Perzisch."],
            ["Worden mijn data gevolgd?", "Nee. Alle omrekeningen draaien lokaal in je browser — geen accounts, geen trackingcookies, alleen anonieme verzoeken aan de openbare koers-API's."],
        ],
        "disc": "Let op: alle koersen zijn indicatief en niet bedoeld voor bankoverschrijvingen, officiële facturen of boekhouding. Controleer altijd bij je bank. © 2026 Seyyid Kadir · MIT-licentie.",
    },
    "pl": {
        "h2": "O Fxverter",
        "p1": "Fxverter to darmowy przelicznik walut online o otwartym kodzie, działający w całości w przeglądarce: aktualne kursy 141 walut świata, bez klucza API, bez rejestracji, bez instalacji — po prostu otwórz stronę w przeglądarce i zacznij przeliczać.",
        "p2": "Kursy pochodzą z trzech publicznych źródeł, między którymi możesz przełączać się w każdej chwili: {F} (kursy referencyjne EBC), {E} i {W}. Kursy są cache'owane na czas sesji; 29 języków interfejsu jest wykrywanych automatycznie, w tym obsługa pisania od prawej do lewej dla arabskiego i perskiego.",
        "lh": "Języki i waluty",
        "lang_intro": "Interfejs dostępny jest w 29 językach:",
        "cur_intro": "Aktualne kursy dostępne są dla 141 walut, z wyszukiwaniem bezpośrednio w listach rozwijanych. Dostępność zależy od wybranego źródła — brakujące pary są automatycznie pobierane z innego źródła:",
        "cur_summary": "Pokaż pełną listę walut",
        "faq_h": "Częste pytania",
        "faqs": [
            ["Czy ten przelicznik jest darmowy?", "Tak. Fxverter jest w pełni darmowy i open source (licencja MIT). Bez klucza API, bez rejestracji, bez śledzenia."],
            ["Jak dokładne są kursy?", "To orientacyjne kursy referencyjne z darmowych publicznych API (EBC przez Frankfurter, ExchangeRate-API, Fawaz), aktualizowane codziennie — świetne jako szybka referencja; przed transakcją zawsze potwierdź w banku."],
            ["Jakie waluty są obsługiwane?", "141 walut, w tym USD, EUR, GBP, JPY, CNY, TRY, INR i CHF. Dostępność zależy od źródła — brakujące pary są automatycznie pobierane z innego."],
            ["Czy muszę coś instalować lub tworzyć konto?", "Nie. Po prostu otwórz stronę w dowolnej nowoczesnej przeglądarce — na komputerze lub telefonie — i przeliczaj od razu. Nic do instalacji, bez konta."],
            ["Jakie języki są obsługiwane?", "29 języków z automatycznym wykrywaniem, w tym pisanie od prawej do lewej dla arabskiego i perskiego."],
            ["Czy śledzicie moje dane?", "Nie. Wszystkie przeliczenia działają lokalnie w przeglądarce — bez kont, bez cookies śledzących, tylko anonimowe zapytania do publicznych API kursów."],
        ],
        "disc": "Zastrzeżenie: wszystkie kursy są orientacyjne i nie mogą służyć do przelewów bankowych, oficjalnych faktur ani księgowości. Zawsze potwierdź w banku. © 2026 Seyyid Kadir · Licencja MIT.",
    },
    "uk": {
        "h2": "Про Fxverter",
        "p1": "Fxverter — безкоштовний онлайн-конвертер валют з відкритим кодом, що працює повністю у вашому браузері: актуальні курси для 141 світових валют, без API-ключа, без реєстрації, без встановлення — просто відкрийте сайт у браузері й починайте конвертувати.",
        "p2": "Курси надходять із трьох відкритих джерел, між якими можна перемикатися будь-коли: {F} (референсні курси ЄЦБ), {E} та {W}. Курси кешуються на час сесії; 29 мов інтерфейсу визначаються автоматично, зокрема підтримка письма справа наліво для арабської та перської.",
        "lh": "Мови та валюти",
        "lang_intro": "Інтерфейс доступний 29 мовами:",
        "cur_intro": "Актуальні курси доступні для 141 валют, із пошуком прямо у випадаючих списках. Доступність залежить від обраного джерела — відсутні пари автоматично беруться з іншого джерела:",
        "cur_summary": "Показати повний список валют",
        "faq_h": "Часті запитання",
        "faqs": [
            ["Цей конвертер безкоштовний?", "Так. Fxverter повністю безкоштовний і відкритий (ліцензія MIT). Без API-ключа, без реєстрації, без відстеження."],
            ["Наскільки точні курси?", "Це орієнтовні референс-курси з безкоштовних відкритих API (ЄЦБ через Frankfurter, ExchangeRate-API, Fawaz), що оновлюються щодня — чудово для швидкої довідки; перед операціями звіряйте з банком."],
            ["Які валюти підтримуються?", "141 валют, зокрема USD, EUR, GBP, JPY, CNY, TRY, INR і CHF. Доступність залежить від джерела — відсутні пари автоматично беруться з іншого."],
            ["Чи потрібно щось встановлювати або створювати акаунт?", "Ні. Просто відкрийте сайт у будь-якому сучасному браузері — на комп'ютері чи телефоні — і конвертуйте одразу. Нічого встановлювати не треба, акаунт не потрібен."],
            ["Які мови підтримуються?", "29 мов з автоматичним визначенням, зокрема письмо справа наліво для арабської та перської."],
            ["Чи відстежуєте ви мої дані?", "Ні. Усі конвертації виконуються локально у браузері — без акаунтів і cookie для відстеження, лише анонімні запити до відкритих API курсів."],
        ],
        "disc": "Дисклеймер: усі курси орієнтовні та не призначені для банківських переказів, офіційних рахунків чи бухгалтерії. Перед операціями звіряйте з банком. © 2026 Seyyid Kadir · Ліцензія MIT.",
    },
    "sv": {
        "h2": "Om Fxverter",
        "p1": "Fxverter är en gratis online-valutaomvandlare med öppen källkod som körs helt i din webbläsare: aktuella kurser för 141 världsvalutor, utan API-nyckel, utan registrering, utan installation — öppna bara webbplatsen i din webbläsare och börja konvertera.",
        "p2": "Kurserna kommer från tre offentliga källor du kan växla mellan när som helst: Frankfurter (ECB:s referenskurser), ExchangeRate-API och Fawaz Currency API. Kurserna cachas per session; 29 gränssnittsspråk identifieras automatiskt, inklusive höger-till-vänster-stöd för arabiska och persiska.",
        "lh": "Språk & valutor",
        "lang_intro": "Gränssnittet finns på 29 språk:",
        "cur_intro": "Aktuella kurser för 141 valutor, sökbara direkt i rullgardinsmenyerna. Tillgängligheten beror på vald källa — saknade par hämtas automatiskt från en annan källa:",
        "cur_summary": "Visa hela valutalistan",
        "faq_h": "Vanliga frågor",
        "faqs": [
            ["Är denna valutaomvandlare gratis?", "Ja. Fxverter är helt gratis och öppen källkod (MIT-licens). Ingen API-nyckel, ingen registrering, ingen spårning."],
            ["Hur tillförlitliga är kurserna?", "Det är indikativa referenskurser från gratis offentliga API:er (ECB via Frankfurter, ExchangeRate-API, Fawaz), uppdaterade dagligen — utmärkt som snabb referens; kontrollera alltid med din bank innan du transagerar."],
            ["Vilka valutor stöds?", "141 valutor, bland annat USD, EUR, GBP, JPY, CNY, TRY, INR och CHF. Tillgängligheten beror på källan — saknade par hämtas automatiskt från en annan."],
            ["Måste jag installera något eller skapa ett konto?", "Nej. Öppna bara webbplatsen i en modern webbläsare — på dator eller mobil — och konvertera direkt. Inget att installera, inget konto behövs."],
            ["Vilka språk stöds?", "29 språk med automatisk identifiering, inklusive höger-till-vänster för arabiska och persiska."],
            ["Spåras mina data?", "Nej. Alla omvandlingar körs lokalt i din webbläsare — inga konton, inga spårcookies, endast anonyma förfrågningar till de offentliga kurs-API:erna."],
        ],
        "disc": "Varning: alla kurser är vägledande och får inte användas för banköverföringar, officiella fakturor eller bokföring. Kontrollera alltid med din bank. © 2026 Seyyid Kadir · MIT-licens.",
    },
    "th": {
        "h2": "เกี่ยวกับ Fxverter",
        "p1": "Fxverter เป็นตัวแปลงสกุลเงินออนไลน์ฟรีแบบโอเพนซอร์สที่ทำงานในเบราว์เซอร์ของคุณทั้งหมด: อัตราแลกเปลี่ยนแบบเรียลไทม์กว่า 141 สกุลเงิน ไม่ต้องใช้ API Key ไม่ต้องสมัคร ไม่ต้องติดตั้ง — เพียงเปิดเว็บไซต์ในเบราว์เซอร์แล้วเริ่มแปลงได้เลย",
        "p2": "อัตราแลกเปลี่ยนมาจากแหล่งข้อมูลสาธารณะ 3 แหล่งที่สลับใช้ได้ตลอดเวลา: {F} (อัตราอ้างอิงจาก ECB), {E} และ {W} อัตราจะถูกแคชต่อเซสชัน รองรับ 29 ภาษาที่ตรวจจับอัตโนมัติ รวมถึงการจัดเรียงจากขวาไปซ้ายสำหรับภาษาอาหรับและเปอร์เซีย",
        "lh": "ภาษาและสกุลเงินที่รองรับ",
        "lang_intro": "อินเทอร์เฟซรองรับ 29 ภาษา:",
        "cur_intro": "มีอัตราแลกเปลี่ยนสำหรับ 141 สกุลเงิน ค้นหาได้โดยตรงในเมนูดรอปดาวน์ ความพร้อมใช้งานขึ้นอยู่กับแหล่งข้อมูลที่เลือก — คู่สกุลเงินที่ขาดหายไปจะดึงจากแหล่งอื่นโดยอัตโนมัติ:",
        "cur_summary": "ดูรายการสกุลเงินทั้งหมด",
        "faq_h": "คำถามที่พบบ่อย",
        "faqs": [
            ["ตัวแปลงสกุลเงินนี้ฟรีหรือไม่?", "ฟรีครับ Fxverter เป็นโอเพนซอร์สฟรีทั้งหมดภายใต้สัญญาอนุญาต MIT ไม่ต้องใช้ API Key ไม่ต้องสมัคร ไม่มีการติดตาม"],
            ["อัตราแลกเปลี่ยนแม่นยำแค่ไหน?", "เป็นอัตราอ้างอิงเชิงบ่งชี้จาก API สาธารณะฟรี (ECB ผ่าน Frankfurter, ExchangeRate-API, Fawaz) อัปเดตทุกวัน — เหมาะเป็นข้อมูลอ้างอิงด่วน ควรยืนยันกับธนาคารก่อนทำธุรกรรมจริง"],
            ["รองรับสกุลเงินใดบ้าง?", "141 สกุลเงิน รวม USD, EUR, GBP, JPY, CNY, TRY, INR และ CHF ความพร้อมใช้งานขึ้นกับแหล่งข้อมูล — คู่ที่ขาดหายจะดึงจากแหล่งอื่นโดยอัตโนมัติ"],
            ["ต้องติดตั้งอะไรหรือสมัครสมาชิกไหม?", "ไม่ต้องเลย เพียงเปิดเว็บไซต์ในเบราว์เซอร์สมัยใหม่ — คอมพิวเตอร์หรือมือถือ — แล้วเริ่มแปลงได้ทันที ไม่ต้องติดตั้ง ไม่ต้องสมัครสมาชิก"],
            ["รองรับภาษาใดบ้าง?", "29 ภาษาตรวจจับอัตโนมัติ รวมถึงการเรียงขวาไปซ้ายสำหรับอาหรับและเปอร์เซีย"],
            ["มีการติดตามข้อมูลของฉันหรือไม่?", "ไม่มี การแปลงทั้งหมดทำงานในเครื่องของคุณ — ไม่มีระบบบัญชี ไม่มีคุกกี้ติดตาม มีเพียงคำขอที่ไม่ระบุตัวตนไปยัง API อัตราแลกเปลี่ยนสาธารณะ"],
        ],
        "disc": "ข้อจำกัด: อัตราแลกเปลี่ยนทั้งหมดเป็นเพียงข้อมูลอ้างอิง ห้ามใช้สำหรับโอนเงินผ่านธนาคาร ออกใบแจ้งหนี้อย่างเป็นทางการ หรือบัญชี ควรยืนยันกับธนาคารของคุณเสมอ © 2026 Seyyid Kadir · MIT License",
    },
    "lo": {
        "h2": "ກ່ຽວກັບ Fxverter",
        "p1": "Fxverter ເປັນເຄື່ອງມືແປງສະກຸນເງິນອອນລາຍຟຣີ ແບບເປີດທີ່ທຳງານຢູ່ໃນບຣາວເຊີຂອງທ່ານ: ອັດຕາແລກປ່ຽນປະຈຸບັນຂອງ 141 ສະກຸນເງິນ ບໍ່ຕ້ອງໃຊ້ API key ບໍ່ຕ້ອງສະໝັກ ບໍ່ຕ້ອງຕິດຕັ້ງ — ພຽງແຕ່ເປີດເວັບໄຊນ໌ໃນບຣາວເຊີແລ້ວເລີ່ມແປງໄດ້ເລີຍ.",
        "p2": "ອັດຕາແລກປ່ຽນມາຈາກແຫຼ່ງຂໍ້ມູນສາທາລະນະ 3 ແຫຼ່ງ ສະຫຼັບໃຊ້ໄດ້ຕະຫຼອດເວລາ: {F} (ອັດຕາອ້າງອີງ ECB), {E} ແລະ {W} ອັດຕາຖືກເກັບໄວ້ຕໍ່ເຊດຊັນ ຮອງຮັບ 29 ພາສາທີ່ກວດຈັບອັດຕະໂນມັດ ລວມທັງການຂຽນຈາກຂວາໄປຊ້າຍສຳລັບອາຣັບິກ ແລະ ເປີເຊຍ.",
        "lh": "ພາສາ ແລະ ສະກຸນເງິນ",
        "lang_intro": "ໜ້າຈໍຮອງຮັບ 29 ພາສາ:",
        "cur_intro": "ມີອັດຕາແລກປ່ຽນສຳລັບ 141 ສະກຸນເງິນ ຄົ້ນຫາໄດ້ໂດຍກົງໃນ dropdown. ຄວາມພ້ອມຂຶ້ນກັບແຫຼ່ງທີ່ເລືອກ — ຄູ່ທີ່ຂາດຈະດຶງຈາກແຫຼ່ງອື່ນໂດຍອັດຕະໂນມັດ:",
        "cur_summary": "ເບິ່ງລາຍການສະກຸນເງິນທັງໝົດ",
        "faq_h": "ຄຳຖາມທີ່ພົບເລື້ອຍ",
        "faqs": [
            ["ເຄື່ອງມືນີ້ຟຣີບໍ?", "ຟຣີ. Fxverter ເປັນໂອເພນຊອສຟຣີທັງໝົດພາຍໃຕ້ສັນຍາ MIT ບໍ່ຕ້ອງໃຊ້ API key ບໍ່ຕ້ອງສະໝັກ ບໍ່ມີການຕິດຕາມ."],
            ["ອັດຕາແມ່ນຖືກຕ້ອງປານໃດ?", "ເປັນອັດຕາອ້າງອີງຈາກ API ສາທາລະນະຟຣີ (ECB ຜ່ານ Frankfurter, ExchangeRate-API, Fawaz) ອັບເດດທຸກມື້ — ເໝາະເປັນຂໍ້ມູນອ້າງອີງດ່ວນ ຄວນຢືນຢັນກັບທະນາຄານກ່ອນທຸກທຸລະກຳ."],
            ["ຮອງຮັບສະກຸນເງິນໃດແດ່?", "141 ສະກຸນເງິນ ລວມ USD, EUR, GBP, JPY, CNY, TRY, INR ແລະ CHF ຂຶ້ນກັບແຫຼ່ງຂໍ້ມູນ — ຄູ່ທີ່ຂາດຈະດຶງຈາກແຫຼ່ງອື່ນໂດຍອັດຕະໂນມັດ."],
            ["ຕ້ອງຕິດຕັ້ງຫຍັງ ຫຼື ສ້າງບັນຊີບໍ?", "ບໍ່ຕ້ອງ. ພຽງແຕ່ເປີດເວັບໄຊນ໌ໃນບຣາວເຊີທັນສະໄໝ — ໃນຄອມພິວເຕີ ຫຼື ໂທລະສັບ — ແລ້ວເລີ່ມແປງໄດ້ທັນທີ ບໍ່ຕ້ອງຕິດຕັ້ງ ບໍ່ຕ້ອງມີບັນຊີ."],
            ["ຮອງຮັບພາສາໃດແດ່?", "29 ພາສາກວດຈັບອັດຕະໂນມັດ ລວມການຂຽນຈາກຂວາໄປຊ້າຍສຳລັບອາຣັບິກ ແລະ ເປີເຊຍ."],
            ["ມີການຕິດຕາມຂໍ້ມູນບໍ?", "ບໍ່ມີ ການແປງທັງໝົດເຮັດໃນເບຣາວເຊີຂອງທ່ານ — ບໍ່ມີບັນຊີ ບໍ່ມີ cookie ຕິດຕາມ ມີແຕ່ຄຳຂໍແບບນິລະນາມໄປຫາ API ອັດຕາສາທາລະນະ."],
        ],
        "disc": "ຂໍ້ຈຳກັດ: ອັດຕາທັງໝົດເປັນພຽງຕົວເລກອ້າງອີງ ບໍ່ຄວນໃຊ້ສຳລັບໂອນເງິນ ໃບແຈ້ງໜີ້ ຫຼື ບັນຊີ ຄວນຢືນຢັນກັບທະນາຄານຂອງທ່ານສະເໝີ © 2026 Seyyid Kadir · MIT License",
    },
    "vi": {
        "h2": "Giới thiệu Fxverter",
        "p1": "Fxverter là công cụ chuyển đổi tiền tệ trực tuyến miễn phí, mã nguồn mở, chạy hoàn toàn trong trình duyệt của bạn: tỷ giá trực tuyến cho 141 đồng tiền thế giới, không cần API key, không cần đăng ký, không cần cài đặt — chỉ cần mở trang web trong trình duyệt và bắt đầu chuyển đổi.",
        "p2": "Tỷ giá đến từ ba nguồn công khai có thể chuyển đổi bất cứ lúc nào: {F} (tỷ giá tham chiếu ECB), {E} và {W}. Tỷ giá được cache theo phiên; 29 ngôn ngữ giao diện được tự động nhận diện, bao gồm hỗ trợ viết từ phải sang trái cho tiếng Ả Rập và tiếng Ba Tư.",
        "lh": "Ngôn ngữ & tiền tệ",
        "lang_intro": "Giao diện hỗ trợ 29 ngôn ngữ:",
        "cur_intro": "Có tỷ giá cho 141 đồng tiền, tìm kiếm trực tiếp trong dropdown. Khả dụng phụ thuộc vào nguồn dữ liệu chọn — cặp thiếu sẽ tự động lấy từ nguồn khác:",
        "cur_summary": "Xem danh sách đầy đủ các đồng tiền",
        "faq_h": "Câu hỏi thường gặp",
        "faqs": [
            ["Công cụ này có miễn phí không?", "Có. Fxverter hoàn toàn miễn phí và mã nguồn mở theo giấy phép MIT. Không cần API key, không đăng ký, không theo dõi."],
            ["Tỷ giá chính xác đến đâu?", "Đây là tỷ giá tham chiếu mang tính chỉ dẫn từ các API công khai miễn phí (ECB qua Frankfurter, ExchangeRate-API, Fawaz), cập nhật hằng ngày — phù hợp làm tham khảo nhanh; luôn xác nhận với ngân hàng trước khi giao dịch."],
            ["Hỗ trợ những đồng tiền nào?", "141 đồng tiền gồm USD, EUR, GBP, JPY, CNY, TRY, INR và CHF. Khả dụng phụ thuộc vào nguồn — cặp thiếu tự động lấy từ nguồn khác."],
            ["Có cần cài đặt hay tạo tài khoản không?", "Không. Chỉ cần mở trang web bằng bất kỳ trình duyệt hiện đại nào — trên máy tính hoặc điện thoại — và chuyển đổi ngay. Không cần cài đặt, không cần tài khoản."],
            ["Hỗ trợ những ngôn ngữ nào?", "29 ngôn ngữ tự động nhận diện, bao gồm hỗ trợ đầy đủ viết từ phải sang trái cho tiếng Ả Rập và Ba Tư."],
            ["Có theo dõi dữ liệu của tôi không?", "Không. Mọi chuyển đổi chạy cục bộ trong trình duyệt — không tài khoản, không cookie theo dõi, chỉ có yêu cầu ẩn danh tới các API tỷ giá công khai."],
        ],
        "disc": "Miễn trừ: mọi tỷ giá chỉ mang tính tham khảo, không dùng cho chuyển khoản ngân hàng, hóa đơn chính thức hay kế toán. Luôn xác nhận với ngân hàng của bạn. © 2026 Seyyid Kadir · Giấy phép MIT.",
    },
    "el": {
        "h2": "Σχετικά με το Fxverter",
        "p1": "Το Fxverter είναι ένας δωρεάν online μετατροπέας νομισμάτων ανοιχτού κώδικα που λειτουργεί εξ ολοκλήρου στον browser σας: ζωντανές ισοτιμίες για 141 νομίσματα του κόσμου, χωρίς κλειδί API, χωρίς εγγραφή, χωρίς εγκατάσταση — απλά ανοίξτε τον ιστότοπο στον browser σας και ξεκινήστε τη μετατροπή.",
        "p2": "Οι ισοτιμίες προέρχονται από τρεις δημόσιες πηγές με άμεση εναλλαγή: {F} (τιμές αναφοράς ΕΚΤ), {E} και {W}. Οι ισοτιμίες αποθηκεύονται στην cache ανά συνεδρία· 29 γλώσσες εντοπίζονται αυτόματα, με υποστήριξη δεξιόαριστερης γραφής για αραβικά και περσικά.",
        "lh": "Γλώσσες & νομίσματα",
        "lang_intro": "Το περιβάλλον διατίθεται σε 29 γλώσσες:",
        "cur_intro": "Υπάρχουν ζωντανές ισοτιμίες για 141 νομίσματα, με αναζήτηση απευθείας στα dropdowns. Η διαθεσιμότητα εξαρτάται από την επιλεγμένη πηγή — τα ζεύγη που λείπουν ανακτώνται αυτόματα από άλλη πηγή:",
        "cur_summary": "Προβολή πλήρους λίστας νομισμάτων",
        "faq_h": "Συχνές ερωτήσεις",
        "faqs": [
            ["Είναι δωρεάν αυτός ο μετατροπέας;", "Ναι. Το Fxverter είναι εντελώς δωρεάν και ανοιχτού κώδικα (άδεια MIT). Χωρίς κλειδί API, χωρίς εγγραφή, χωρίς παρακολούθηση."],
            ["Πόσο ακριβείς είναι οι ισοτιμίες;", "Είναι ενδεικτικές τιμές αναφοράς από δωρεάν δημόσια API (ΕΚΤ μέσω Frankfurter, ExchangeRate-API, Fawaz), με καθημερινή ενημέρωση — ιδανικές ως γρήγορη αναφορά· επιβεβαιώστε πάντα με την τράπεζά σας."],
            ["Ποια νομίσματα υποστηρίζονται;", "141 νομίσματα, μεταξύ των οποίων USD, EUR, GBP, JPY, CNY, TRY, INR και CHF. Η διαθεσιμότητα εξαρτάται από την πηγή — τα ζεύγη που λείπουν ανακτώνται αυτόματα από άλλη."],
            ["Χρειάζεται εγκατάσταση ή δημιουργία λογαριασμού;", "Όχι. Ανοίξτε απλά τον ιστότοπο σε οποιονδήποτε σύγχρονο browser — σε υπολογιστή ή κινητό — και ξεκινήστε αμέσως. Τίποτα για εγκατάσταση, χωρίς λογαριασμό."],
            ["Ποιες γλώσσες υποστηρίζονται;", "29 γλώσσες με αυτόματη ανίχνευση, με πλήρη υποστήριξη δεξιόαριστερης γραφής για αραβικά και περσικά."],
            ["Παρακολουθείτε τα δεδομένα μου;", "Όχι. Όλες οι μετατροπές εκτελούνται τοπικά στον browser — χωρίς λογαριασμούς, χωρίς cookies παρακολούθησης, μόνο ανώνυμα αιτήματα προς τα δημόσια API ισοτιμιών."],
        ],
        "disc": "Σημείωση: όλες οι ισοτιμίες είναι ενδεικτικές και δεν πρέπει να χρησιμοποιούνται για τραπεζικές μεταφορές, επίσημα τιμολόγια ή λογιστική. Επιβεβαιώστε πάντα με την τράπεζά σας. © 2026 Seyyid Kadir · Άδεια MIT.",
    },
    "bn": {
        "h2": "Fxverter সম্পর্কে",
        "p1": "Fxverter একটি ফ্রি, ওপেন-সোর্স অনলাইন মুদ্রা রূপান্তরকারী যা সম্পূর্ণভাবে আপনার ব্রাউজারে চলে: ১৪১টি বিশ্ব মুদ্রার লাইভ বিনিময় হার, কোনো API কী ছাড়াই, সাইন-আপ ছাড়াই, ইনস্টলেশন ছাড়াই — শুধু ব্রাউজারে ওয়েবসাইটটি খুলুন এবং রূপান্তর শুরু করুন।",
        "p2": "রেট আসে তিনটি পাবলিক সোর্স থেকে, যেকোনো সময় বদলানো যায়: {F} (ECB রেফারেন্স রেট), {E} এবং {W}। রেট প্রতি সেশনে ক্যাশ হয়; ২৯টি ইন্টারফেস ভাষা স্বয়ংক্রিয়ভাবে শনাক্ত হয়, আরবি ও ফারসির জন্য ডান-থেকে-বাম সমর্থনসহ।",
        "lh": "ভাষা ও মুদ্রা",
        "lang_intro": "ইন্টারফেস ২৯টি ভাষায় পাওয়া যায়:",
        "cur_intro": "১৪১টি মুদ্রার জন্য লাইভ রেট আছে, ড্রপডাউনেই সরাসরি খোঁজা যায়। প্রাপ্যতা নির্বাচিত ডেটা সোর্সের উপর নির্ভর করে — অনুপস্থিত জোড়া অন্য সোর্স থেকে স্বয়ংক্রিয়ভাবে নেওয়া হয়:",
        "cur_summary": "সম্পূর্ণ মুদ্রা তালিকা দেখুন",
        "faq_h": "সাধারণ জিজ্ঞাসা",
        "faqs": [
            ["এই মুদ্রা রূপান্তরকারী কি ফ্রি?", "হ্যাঁ। Fxverter MIT লাইসেন্সের অধীনে সম্পূর্ণ ফ্রি ও ওপেন সোর্স। কোনো API কী নেই, সাইন-আপ নেই, ট্র্যাকিং নেই।"],
            ["বিনিময় হার কতটা নির্ভুল?", "এগুলো ফ্রি পাবলিক API (Frankfurter-এর মাধ্যমে ECB, ExchangeRate-API, Fawaz) থেকে নেওয়া নির্দেশক রেফারেন্স রেট, প্রতিদিন হালনাগাদ হয় — দ্রুত রেফারেন্সের জন্য দারুণ; লেনদেনের আগে অবশ্যই ব্যাংকে যাচাই করুন।"],
            ["কোন কোন মুদ্রা সমর্থিত?", "USD, EUR, GBP, JPY, CNY, TRY, INR ও CHF-সহ ১৪১টি মুদ্রা। প্রাপ্যতা সোর্সের উপর নির্ভর করে — অনুপস্থিত জোড়া অন্য সোর্স থেকে স্বয়ংক্রিয়ভাবে নেওয়া হয়।"],
            ["ইনস্টল বা অ্যাকাউন্ট তৈরি করা লাগবে?", "না। যেকোনো আধুনিক ব্রাউজারে — কম্পিউটার বা মোবাইলে — ওয়েবসাইটটি খুলুন এবং সাথে সাথে রূপান্তর শুরু করুন। কিছু ইনস্টল করা লাগে না, অ্যাকাউন্টও লাগে না।"],
            ["কোন ভাষাগুলো সমর্থিত?", "স্বয়ংক্রিয় শনাক্তকরণসহ ২৯টি ভাষা, আরবি ও ফারসির জন্য পূর্ণ ডান-থেকে-বাম সমর্থন।"],
            ["কি আমার ডেটা ট্র্যাক করা হয়?", "না। সব রূপান্তর আপনার ব্রাউজারে লোকালি চলে — কোনো অ্যাকাউন্ট নেই, ট্র্যাকিং কুকি নেই, শুধু পাবলিক রেট API-তে নাম-গোপন অনুরোধ যায়।"],
        ],
        "disc": "দাবিত্যাগ: সব রেট কেবল নির্দেশক, ব্যাংক ট্রান্সফার, অফিসিয়াল ইনভয়েস বা হিসাবরক্ষণে ব্যবহার করা উচিত নয়। লেনদেনের আগে ব্যাংকে যাচাই করুন। © 2026 Seyyid Kadir · MIT লাইসেন্স।",
    },
    "fa": {
        "h2": "درباره Fxverter",
        "p1": "Fxverter یک مبدل ارز آنلاین رایگان و متن‌باز است که کاملاً در مرورگر شما اجرا می‌شود: نرخ ارز لحظه‌ای برای ۱۴۱ ارز جهانی، بدون کلید API، بدون ثبت‌نام، بدون نصب — کافی است وب‌سایت را در مرورگر باز کنید و تبدیل را شروع کنید.",
        "p2": "نرخ‌ها از سه منبع عمومی دریافت می‌شوند که هر لحظه می‌توانید بین آن‌ها جابه‌جا شوید: {F} (نرخ‌های مرجع بانک مرکزی اروپا)، {E} و {W}. نرخ‌ها به‌ازای هر نشانه کش می‌شوند؛ ۲۹ زبان رابط به‌طور خودکار تشخیص داده می‌شود، از جمله پشتیبانی راست‌به‌چپ برای عربی و فارسی.",
        "lh": "زبان‌ها و ارزها",
        "lang_intro": "رابط کاربری به ۲۹ زبان در دسترس است:",
        "cur_intro": "نرخ لحظه‌ای برای ۱۴۱ ارز موجود است و می‌توانید مستقیماً در منوهای کشویی جست‌وجو کنید. دسترس‌پذیری به منبع انتخابی بستگی دارد — جفت‌های ناموجود به‌طور خودکار از منبع دیگری دریافت می‌شوند:",
        "cur_summary": "مشاهده فهرست کامل ارزها",
        "faq_h": "پرسش‌های متداول",
        "faqs": [
            ["آیا این مبدل رایگان است؟", "بله. Fxverter به‌طور کامل رایگان و متن‌باز تحت مجوز MIT است. بدون کلید API، بدون ثبت‌نام، بدون ردیابی."],
            ["نرخ‌ها چقدر دقیق‌اند؟", "نرخ‌های مرجع راهنما از APIهای عمومی رایگان هستند (ECB از طریق Frankfurter، ExchangeRate-API، Fawaz) و روزانه به‌روزرسانی می‌شوند — برای مرجع سریع عالی‌اند؛ پیش از هر تراکنش با بانک خود تأیید کنید."],
            ["کدام ارزها پشتیبانی می‌شوند؟", "۱۴۱ ارز از جمله USD، EUR، GBP، JPY، CNY، TRY، INR و CHF. دسترس‌پذیری به منبع بستگی دارد — جفت‌های ناموجود خودکار از منبع دیگر گرفته می‌شوند."],
            ["آیا نصب یا ساخت حساب لازم است؟", "نه. کافی است وب‌سایت را در هر مرورگر مدرنی — روی رایانه یا تلفن — باز کنید و بلافاصله تبدیل را شروع کنید. بدون نصب و بدون حساب."],
            ["چه زبان‌هایی پشتیبانی می‌شوند؟", "۲۹ زبان با تشخیص خودکار، شامل پشتیبانی کامل راست‌به‌چپ برای عربی و فارسی."],
            ["آیا داده‌های من ردیابی می‌شود؟", "نه. همه تبدیل‌ها به‌صورت محلی در مرورگر شما اجرا می‌شوند — بدون حساب، بدون کوکی ردیابی، فقط درخواست‌های ناشناس به APIهای عمومی نرخ."],
        ],
        "disc": "سلب مسئولیت: همه نرخ‌ها صرفاً راهنما هستند و برای حواله بانکی، فاکتور رسمی یا حسابداری نباید استفاده شوند. پیش از تراکنش با بانک خود تأیید کنید. © 2026 Seyyid Kadir · مجوز MIT.",
    },
    "cs": {
        "h2": "O Fxverter",
        "p1": "Fxverter je bezplatný online převodník měn s otevřeným kódem, který běží celý ve vašem prohlížeči: aktuální kurzy 141 světových měn, bez klíče API, bez registrace, bez instalace — stačí otevřít web v prohlížeči a začít převádět.",
        "p2": "Kurzy pocházejí ze tří veřejných zdrojů, mezi nimiž můžete kdykoli přepínat: {F} (referenční kurzy ECB), {E} a {W}. Kurzy se ukládají do mezipaměti na session; 29 jazyků rozhraní se rozpoznává automaticky, včetně psaní zprava doleva pro arabštinu a perštinu.",
        "lh": "Jazyky a měny",
        "lang_intro": "Rozhraní je k dispozici ve 29 jazycích:",
        "cur_intro": "Aktuální kurzy jsou k dispozici pro 141 měn, s vyhledáváním přímo v rozbalovacích seznamech. Dostupnost závisí na zvoleném zdroji — chybějící páry se automaticky načtou z jiného zdroje:",
        "cur_summary": "Zobrazit kompletní seznam měn",
        "faq_h": "Časté dotazy",
        "faqs": [
            ["Je tento převodník zdarma?", "Ano. Fxverter je zcela zdarma a open source (licence MIT). Bez klíče API, bez registrace, bez sledování."],
            ["Jak přesné jsou kurzy?", "Jsou to orientační referenční kurzy z bezplatných veřejných API (ECB přes Frankfurter, ExchangeRate-API, Fawaz), aktualizované denně — ideální jako rychlá orientace; před transakcí si vždy ověřte kurz v bance."],
            ["Které měny jsou podporovány?", "141 měn, mimo jiné USD, EUR, GBP, JPY, CNY, TRY, INR a CHF. Dostupnost závisí na zdroji — chybějící páry se automaticky převezmou z jiného."],
            ["Musím něco instalovat nebo si vytvořit účet?", "Ne. Stačí otevřít web v jakémkoli moderním prohlížeči — na počítači nebo mobilu — a ihned převádět. Nic k instalaci, bez účtu."],
            ["Jaké jazyky jsou podporovány?", "29 jazyků s automatickou detekcí, včetně psaní zprava doleva pro arabštinu a perštinu."],
            ["Sledujete moje data?", "Ne. Všechny převody běží lokálně ve vašem prohlížeči — žádné účty, žádné sledovací cookies, pouze anonymní požadavky na veřejná API kurzů."],
        ],
        "disc": "Upozornění: všechny kurzy jsou orientační a nesmí se používat pro bankovní převody, oficiální faktury ani účetnictví. Vždy si kurz ověřte ve své bance. © 2026 Seyyid Kadir · Licence MIT.",
    },
    "ro": {
        "h2": "Despre Fxverter",
        "p1": "Fxverter este un convertor valutar online gratuit, cu cod deschis, care rulează integral în browserul tău: cursuri de schimb în timp real pentru 141 de valute mondiale, fără cheie API, fără înregistrare, fără instalare — deschide pur și simplu site-ul în browser și începe să convertești.",
        "p2": "Cursurile provin din trei surse publice între care poți comuta oricând: {F} (cursurile de referință BCE), {E} și {W}. Cursurile se salvează în cache pe sesiune; 29 de limbi de interfață sunt detectate automat, inclusiv suportul dreapta-stânga pentru arabă și persană.",
        "lh": "Limbi și valute",
        "lang_intro": "Interfața este disponibilă în 29 de limbi:",
        "cur_intro": "Cursuri în timp real pentru 141 de valute, căutabile direct în meniurile derulante. Disponibilitatea depinde de sursa selectată — perechile lipsă sunt preluate automat din altă sursă:",
        "cur_summary": "Vezi lista completă de valute",
        "faq_h": "Întrebări frecvente",
        "faqs": [
            ["Este gratuit acest convertor?", "Da. Fxverter este complet gratuit și open source (licență MIT). Fără cheie API, fără înregistrare, fără urmărire."],
            ["Cât de precise sunt cursurile?", "Sunt cursuri de referință orientative din API-uri publice gratuite (BCE prin Frankfurter, ExchangeRate-API, Fawaz), actualizate zilnic — perfecte ca reper rapid; verifică întotdeauna cu banca ta înainte de tranzacții."],
            ["Ce valute sunt suportate?", "141 de valute, inclusiv USD, EUR, GBP, JPY, CNY, TRY, INR și CHF. Disponibilitatea depinde de sursă — perechile lipsă sunt preluate automat din altă sursă."],
            ["Trebuie să instalez ceva sau să creez un cont?", "Nu. Deschide pur și simplu site-ul în orice browser modern — pe computer sau mobil — și convertește imediat. Nimic de instalat, fără cont."],
            ["Ce limbi sunt suportate?", "29 de limbi cu detecție automată, inclusiv scrierea de la dreapta la stânga pentru arabă și persană."],
            ["Îmi urmăriți datele?", "Nu. Toate conversiile rulează local în browser — fără conturi, fără cookie-uri de urmărire, doar cereri anonime către API-urile publice de cursuri."],
        ],
        "disc": "Atenționare: toate cursurile sunt orientative și nu trebuie folosite pentru transferuri bancare, facturi oficiale sau contabilitate. Verifică întotdeauna cu banca ta. © 2026 Seyyid Kadir · Licență MIT.",
    },
    "da": {
        "h2": "Om Fxverter",
        "p1": "Fxverter er en gratis online valutaomregner med open source, der kører helt i din browser: aktuelle kurser for 141 verdensvalutaer, uden API-nøgle, uden registrering, uden installation — åbn blot webstedet i din browser og begynd at konvertere.",
        "p2": "Kurserne kommer fra tre offentlige kilder, du kan skifte mellem når som helst: {F} (ECB's referenzekurser), {E} og {W}. Kurserne caches pr. session; 29 grænsefladesprog genkendes automatisk, herunder højre-til-venstre-understøttelse til arabisk og persisk.",
        "lh": "Sprog & valutaer",
        "lang_intro": "Grænsefladen findes på 29 sprog:",
        "cur_intro": "Aktuelle kurser for 141 valutaer, søgbare direkte i dropdown-menuerne. Tilgængeligheden afhænger af den valgte kilde — manglende par hentes automatisk fra en anden kilde:",
        "cur_summary": "Se hele listen over valutaer",
        "faq_h": "Ofte stillede spørgsmål",
        "faqs": [
            ["Er denne valutaomregner gratis?", "Ja. Fxverter er helt gratis og open source (MIT-licens). Ingen API-nøgle, ingen registrering, ingen sporing."],
            ["Hvor pålidelige er kurserne?", "Det er vejledende referenzekurser fra gratis offentlige API'er (ECB via Frankfurter, ExchangeRate-API, Fawaz), opdateret dagligt — fint som hurtig reference; tjek altid med din bank, før du handler."],
            ["Hvilke valutaer understøttes?", "141 valutaer, herunder USD, EUR, GBP, JPY, CNY, TRY, INR og CHF. Tilgængeligheden afhænger af kilden — manglende par hentes automatisk fra en anden."],
            ["Skal jeg installere noget eller oprette en konto?", "Nej. Åbn blot webstedet i en moderne browser — på computer eller mobil — og konvertér med det samme. Intet at installere, ingen konto."],
            ["Hvilke sprog understøttes?", "29 sprog med automatisk genkendelse, herunder højre-til-venstre til arabisk og persisk."],
            ["Spores mine data?", "Nej. Alle omregninger kører lokalt i din browser — ingen konti, ingen sporingscookies, kun anonyme forespørgsler til de offentlige kurs-API'er."],
        ],
        "disc": "Ansvarsfraskrivelse: alle kurser er vejledende og må ikke bruges til bankoverførsler, officielle fakturaer eller bogføring. Tjek altid med din bank. © 2026 Seyyid Kadir · MIT-licens.",
    },
}
