# -*- coding: utf-8 -*-
"""Bahasa Indonesia (id) and Bahasa Melayu (ms) intros for the 38 currencies."""

ABOUT_BATCH = {
 "id": {
  "USD": "Dolar AS diterbitkan oleh Federal Reserve dan menjadi mata uang cadangan utama dunia.",
  "EUR": "Euro diterbitkan oleh Bank Sentral Eropa dan menjadi mata uang resmi untuk 20 negara di zona euro.",
  "GBP": "Poundsterling diterbitkan oleh Bank of England dan menjadi salah satu mata uang tertua yang masih dipakai.",
  "JPY": "Yen Jepang diterbitkan oleh Bank of Japan dan menjadi mata uang ketiga yang paling banyak diperdagangkan di dunia.",
"TRY": "Lira Turki diterbitkan oleh Bank Sentral Turkiye dan nilainya sangat dipengaruhi oleh tingginya inflasi.",
  "CNY": "Yuan Tiongkok dikelola oleh Bank Rakyat Tiongkok dan menjadi salah satu mata uang yang paling diperhatikan dalam perdagangan.",
  "CHF": "Franc Swiss diterbitkan oleh Bank Nasional Swiss dan menjadi salah satu mata uang yang dianggap aman di dunia.",
  "INR": "Rupee India diterbitkan oleh Reserve Bank of India dan menjadi salah satu mata uang penting di Asia Selatan.",
"KRW": "Won Korea Selatan diterbitkan oleh Bank Korea dan menjadi mata uang yang erat kaitannya dengan ekspor semikonduktor dan otomotif.",
  "AUD": "Dolar Australia diterbitkan oleh Reserve Bank of Australia dan menjadi mata uang komoditas yang erat dengan harga bijih besi dan perdagangan.",
  "CAD": "Dolar Kanada diterbitkan oleh Bank of Canada dan menjadi mata uang yang erat kaitannya dengan harga minyak.",
  "MXN": "Peso Meksiko diterbitkan oleh Bank Meksiko dan menjadi salah satu mata uang yang paling sering diperdagangkan di kawasan Amerika Latin.",
"BRL": "Real Brasil diterbitkan oleh Bank Sentral Brasil dan menjadi mata uang salah satu ekonomi terbesar di Amerika Latin.",
  "ZAR": "Rand Afrika Selatan diterbitkan oleh South African Reserve Bank dan menjadi mata uang yang paling banyak diperdagangkan di Afrika.",
  "RUB": "Rubel Rusia diterbitkan oleh Bank of Russia dan menjadi mata uang yang dipengaruhi oleh ekspor energi.",
  "SAR": "Riyal Arab Saudi diterbitkan oleh bank sentral Saudi dan nilainya dipatok terhadap dolar AS.",
"AED": "Dirham UEA diterbitkan oleh bank sentral UEA dan menjadi mata uang yang dipatok terhadap dolar AS.",
  "SEK": "Krona Swedia diterbitkan oleh Riksbank yang merupakan salah satu bank sentral tertua di dunia.",
  "NOK": "Krone Norwegia diterbitkan oleh Norges Bank dan menjadi mata uang yang kuat kaitannya dengan harga energi.",
  "NZD": "Dolar Selandia Baru diterbitkan oleh Reserve Bank of New Zealand dan menjadi salah satu mata uang komoditas.",
"SGD": "Dolar Singapura diterbitkan oleh Otoritas Moneter Singapura dan menjadi salah satu mata uang yang paling stabil di Asia.",
  "HKD": "Dolar Hong Kong diterbitkan dalam sistem nilai tukar tetap dan menjadi salah satu mata uang yang dipatok terhadap dolar AS.",
  "THB": "Baht Thailand diterbitkan oleh Bank of Thailand dan menjadi mata uang yang penting bagi sektor pariwisata dan perdagangan.",
  "IDR": "Rupiah Indonesia diterbitkan oleh Bank Indonesia dan menjadi mata uang resmi negara Indonesia.",
"MYR": "Ringgit Malaysia diterbitkan oleh Bank Negara Malaysia dan menjadi mata uang yang dipengaruhi oleh ekspor sawit dan minyak.",
  "PHP": "Peso Filipina diterbitkan oleh Bangko Sentral ng Pilipinas dan nilainya sangat dipengaruhi oleh kiriman uang dari pekerja di luar negeri.",
  "VND": "Dong Vietnam diterbitkan oleh Bank Negara Vietnam dan dikenal sebagai salah satu mata uang dengan nilai nominal yang besar.",
  "LAK": "Kip Laos diterbitkan oleh Bank Nasional Laos dan menjadi mata uang resmi negara Laos.",
"PKR": "Rupee Pakistan diterbitkan oleh Bank Negara Pakistan dan menjadi mata uang resmi Pakistan.",
  "BDT": "Taka Bangladesh diterbitkan oleh bank sentral Bangladesh dan menjadi mata uang yang sangat dipengaruhi oleh kiriman para perantau.",
  "NGN": "Naira Nigeria diterbitkan oleh Bank Sentral Nigeria dan menjadi mata uang negara berpenduduk terbanyak di Afrika.",
  "EGP": "Pound Mesir diterbitkan oleh Bank Sentral Mesir dan menjadi salah satu mata uang penting di Afrika Utara.",
"UAH": "Hryvnia Ukraina diterbitkan oleh Bank Nasional Ukraina dan menjadi mata uang resmi Ukraina.",
  "PLN": "Zloty Polandia diterbitkan oleh Bank Nasional Polandia dan menjadi mata uang yang paling sering diperdagangkan di kawasan Eropa.",
  "CZK": "Koruna Ceko diterbitkan oleh Bank Nasional Ceko dan menjadi mata uang yang aktif diperdagangkan.",
  "DKK": "Krone Denmark diterbitkan oleh Bank Sentral Denmark dan menjadi mata uang yang erat hubungannya dengan euro.",
"ILS": "Shekel Baru Israel diterbitkan oleh Bank of Israel dan menjadi mata uang yang dianggap mewakili kondisi ekonomi berteknologi tinggi.",
  "QAR": "Riyal Qatar diterbitkan oleh Bank Sentral Qatar dan menjadi mata uang yang dipatok terhadap dolar AS.",
 },
 "ms": {
  "USD": "Dolar AS diterbit oleh Rizab Persekutuan dan berperanan sebagai mata wang rizab utama dunia.",
  "EUR": "Euro diterbitkan oleh Bank Pusat Eropah dan menjadi mata wang rasmi untuk 20 negara dalam zon euro.",
  "GBP": "Paun sterling diterbitkan oleh Bank of England dan menjadi salah satu mata wang tertua yang masih digunakan di dunia.",
  "JPY": "Yen Jepun diterbitkan oleh Bank of Japan dan menjadi mata wang ketiga yang paling banyak didagangkan di dunia.",
"TRY": "Lira Turki diterbitkan oleh Bank Pusat Turkiye dan nilainya sangat dipengaruhi oleh kadar inflasi yang tinggi.",
  "CNY": "Yuan China diterbitkan oleh Bank Rakyat China dan menjadi salah satu mata wang yang paling diperhatikan dalam perdagangan dunia.",
  "CHF": "Franc Swiss diterbitkan oleh Bank Negara Switzerland dan menjadi salah satu mata wang yang dianggap selamat di dunia.",
  "INR": "Rupee India diterbitkan oleh Reserve Bank of India dan menjadi salah satu mata wang penting di Asia Selatan.",
"KRW": "Won Korea Selatan diterbitkan oleh Bank Korea dan menjadi mata wang yang berkait rapat dengan eksport semikonduktor dan kenderaan.",
  "AUD": "Dolar Australia diterbitkan oleh Bank Simpanan Australia dan menjadi mata wang komoditi yang berkait dengan harga bijih besi dan perdagangan.",
  "CAD": "Dolar Kanada diterbitkan oleh Bank of Canada dan menjadi salah satu mata wang yang berkait rapat dengan harga minyak.",
  "MXN": "Peso Mexico diterbitkan oleh Bank of Mexico dan menjadi antara mata wang yang paling kerap didagangkan di Amerika Latin.",
"BRL": "Real Brazil diterbitkan oleh Bank Pusat Brazil dan menjadi mata wang dalam salah satu ekonomi terbesar Amerika Latin.",
  "ZAR": "Rand Afrika Selatan diterbitkan oleh Rizab Bank Afrika Selatan dan menjadi mata wang yang paling banyak didagangkan di Afrika.",
  "RUB": "Rubel Rusia diterbitkan oleh Bank of Russia dan menjadi mata wang yang dipengaruhi oleh eksport tenaga.",
  "SAR": "Riyal Arab Saudi diterbitkan oleh bank pusat Saudi dan nilainya dipatok kepada dolar AS.",
"AED": "Dirham UEA diterbitkan oleh bank pusat UEA dan menjadi mata wang yang dipatok kepada dolar AS.",
  "SEK": "Krona Sweden diterbitkan oleh Riksbank yang merupakan salah satu bank pusat tertua di dunia.",
  "NOK": "Krone Norway diterbitkan oleh Norges Bank dan menjadi mata wang yang berkait rapat dengan harga tenaga.",
  "NZD": "Dolar New Zealand diterbitkan oleh bank pusat New Zealand dan menjadi salah satu mata wang komoditi.",
"SGD": "Dolar Singapura diterbitkan oleh Penguasa Kewangan Singapura dan menjadi salah satu mata wang yang paling stabil di Asia.",
  "HKD": "Dolar Hong Kong diterbitkan dalam sistem kadar pertukaran tetap dan menjadi salah satu mata wang yang dipatok kepada dolar AS.",
  "THB": "Baht Thailand diterbitkan oleh Bank of Thailand dan menjadi mata wang yang penting bagi sektor pelancongan dan perdagangan.",
  "IDR": "Rupiah Indonesia diterbitkan oleh Bank Indonesia dan menjadi mata wang rasmi Indonesia.",
"MYR": "Ringgit Malaysia diterbitkan oleh Bank Negara Malaysia dan menjadi mata wang yang dipengaruhi oleh eksport minyak sawit dan tenaga.",
  "PHP": "Peso Filipina dikeluarkan oleh Bangko Sentral ng Pilipinas dan nilainya amat dipengaruhi oleh kiriman wang daripada pekerja di luar negara.",
  "VND": "Dong Vietnam diterbitkan oleh Bank Negara Vietnam dan dikenali sebagai salah satu mata wang dengan nilai nominal yang besar.",
  "LAK": "Kip Laos diterbitkan oleh bank pusat Laos dan menjadi mata wang rasmi Laos.",
"PKR": "Rupee Pakistan dikeluarkan oleh Bank Negara Pakistan dan menjadi mata wang rasmi Pakistan.",
  "BDT": "Taka Bangladesh diterbitkan oleh bank pusat Bangladesh dan menjadi mata wang yang sangat dipengaruhi oleh kiriman wang oleh rakyat.",
  "NGN": "Naira Nigeria diterbitkan oleh Bank Pusat Nigeria dan menjadi mata wang negara yang paling ramai penduduk di Afrika.",
  "EGP": "Pound Mesir diterbitkan oleh Bank Pusat Mesir dan menjadi salah satu mata wang penting di Afrika Utara.",
"UAH": "Hryvnia Ukraine diterbitkan oleh bank pusat Ukraine dan menjadi mata wang rasmi Ukraine.",
"PLN": "Zloty Poland diterbitkan oleh Bank Negara Poland dan menjadi mata wang yang paling kerap diperdagangkan di Eropah.",
  "CZK": "Koruna Republik Czech diterbitkan oleh bank pusat Czech dan menjadi mata wang yang aktif didagangkan di tengah Eropah.",
  "DKK": "Krone Denmark diterbitkan oleh bank sentral Denmark dan menjadi mata wang yang berkait rapat dengan euro.",
  "ILS": "Syekel Israel diterbitkan oleh Bank of Israel dan menjadi mata wang yang sering dianggap mewakili ekonomi berteknologi tinggi.",
  "QAR": "Riyal Qatar diterbitkan oleh Bank Pusat Qatar dan menjadi mata wang yang dipatok kepada dolar AS.",
 }
}