# -*- coding: utf-8 -*-
"""About intros: es, fr."""
ABOUT_BATCH = {
 "es": {
   "USD": "El dólar estadounidense, emitido por la Reserva Federal, es la principal moneda de reserva del mundo y la más negociada en los mercados de divisas.",
   "EUR": "El euro, gestionado por el Banco Central Europeo, es la moneda oficial de los 20 países de la zona euro y la segunda moneda más negociada del mundo.",
   "GBP": "La libra esterlina, emitida por el Banco de Inglaterra, es la moneda más antigua aún en circulación y una de las principales monedas de reserva del mundo.",
   "JPY": "El yen japonés, emitido por el Banco de Japón, es la tercera moneda más negociada del mundo y un valor de refugio tradicional.",
   "TRY": "La lira turca, emitida por el Banco Central de Turquía, ha sufrido una fuerte inflación y una gran volatilidad del tipo de cambio en los últimos años.",
   "CNY": "El yuan chino (renminbi), gestionado por el Banco Popular de China, opera bajo un tipo de flotación controlada, y el par yuan-dólar es de los más seguidos del mundo.",
   "CHF": "El franco suizo, emitido por el Banco Nacional de Suiza, es una moneda refugio clásica, respaldada por la estabilidad política y financiera del país.",
   "INR": "La rupia india, emitida por el Banco de la Reserva de la India, es la moneda del país más poblado del mundo y uno de los mayores receptores de remesas del planeta.",
   "KRW": "El won surcoreano, emitido por el Banco de Corea, es una moneda muy negociada de Asia, cuyo valor pasa por las exportaciones de semiconductores y automóviles.",
   "AUD": "El dólar australiano, emitido por el Banco de la Reserva de Australia, es una moneda de materias primas como el mineral de hierro y el oro, entre las más negociadas del mundo.",
   "CAD": "El dólar canadiense, emitido por el Banco de Canadá, es una moneda ligada a las materias primas, y su cotización responde al precio del petróleo.",
   "BRL": "El real brasileño, emitido por el Banco Central de Brasil, es la moneda más negociada de Sudamérica y su cotización sigue de cerca las exportaciones de soja, café y mineral de hierro.",
   "MXN": "El peso mexicano, emitido por el Banco de México, es la moneda más negociada de América Latina, por su estrecha vinculación con la economía de Estados Unidos.",
   "ZAR": "El rand sudafricano, emitido por el Banco de la Reserva de Sudáfrica, es la moneda africana más negociada y su valor responde a los precios del oro y del platino.",
   "RUB": "El rublo ruso, emitido por el Banco de Rusia, es la moneda oficial de Rusia, cuyo valor depende mucho de los ingresos por exportación de energía.",
   "SAR": "El riyal saudí, emitido por la Autoridad Monetaria de Arabia Saudí (SAMA), está vinculado al dólar estadounidense desde 1986, con un tipo de cambio casi fijo.",
   "AED": "El dirham de los Emiratos Árabes Unidos, emitido por el Banco Central de los EAU, está anclado al dólar, lo que da estabilidad al comercio del golfo.",
   "SEK": "La corona sueca, emitida por el Riksbank — el banco central más antiguo del mundo — es la moneda de Suecia, un país de la Unión Europea fuera del euro.",
   "NOK": "La corona noruega, emitida por el Banco de Noruega, cotiza bajo la influencia de los ingresos del petróleo y del gas de Noruega.",
   "NZD": "El dólar neozelandés, apodado kiwi y emitido por el Banco de la Reserva de Nueva Zelanda, es una moneda de materias primas, ligada a las exportaciones lácteas.",
   "SGD": "El dólar de Singapur, gestionado por la Autoridad Monetaria de Singapur mediante una cesta de monedas, es una divisa estable del centro financiero asiático.",
   "HKD": "El dólar de Hong Kong se mantiene desde 1983 vinculado al dólar estadounidense dentro de una banda de 7,75 a 7,85 dólares de Hong Kong por dólar estadounidense.",
   "THB": "El baht tailandés, emitido por el Banco de Tailandia, es una moneda clave del sudeste asiático, muy utilizada en el sector turístico.",
   "IDR": "La rupia indonesia, emitida por el Banco de Indonesia, es la moneda del país más poblado y con mayor población musulmana del mundo.",
   "MYR": "El ringgit de Malasia, emitido por el Banco Central de Malasia, es una moneda sensible a la evolución del aceite de palma y del petróleo.",
   "BDT": "La taka de Bangladesh, emitida por el Banco de Bangladesh, es la moneda de un país que se apoya en la fabricación de textiles y en las remesas.",
   "PHP": "El peso filipino, emitido por el Banco Central de Filipinas, es la moneda de una de las mayores economías receptoras de remesas del mundo.",
   "VND": "El dong vietnamita, emitido por el Banco Central de Vietnam, es una de las monedas de valor unitario más bajo del mundo, pese al fuerte crecimiento de su economía.",
   "LAK": "El kip laosiano, emitido por el Banco Central de la República de Laos, es la moneda oficial de Laos, con una presencia discreta en los mercados de divisas.",
   "PKR": "La rupia pakistaní, emitida por el Banco Estatal de Pakistán, es la moneda del quinto país más poblado del planeta, con fuerte peso de las remesas de su diáspora.",
   "NGN": "La naira nigeriana, emitida por el Banco Central de Nigeria, es la divisa del país más poblado de África y está muy condicionada por el petróleo.",
   "EGP": "La libra egipcia, emitida por el Banco Central de Egipto, es la moneda del país más poblado del mundo árabe, con el turismo y el canal de Suez como claves.",
"UAH": "La grivnia ucraniana, emitida por el Banco Nacional de Ucrania, es la moneda oficial de Ucrania, con un régimen de tipo de cambio flexible.",
   "PLN": "El zloty polaco, emitido por el Banco Nacional de Polonia, es la moneda de la mayor economía de Europa Central y una de las más activas de la Unión Europea.",
   "CZK": "La corona checa, emitida por el Banco Nacional Checo, es la moneda oficial de la República Checa, un país de la Unión Europea sin el euro.",
   "DKK": "La corona danesa, emitida por el Banco Central de Dinamarca, está ligada al euro mediante el mecanismo europeo de tipos de cambio.",
   "ILS": "El nuevo séquel israelí, emitido por el Banco de Israel, es una de las monedas de Oriente Medio más libremente negociadas por la economía tecnológica del país.",
   "QAR": "El riyal qatarí, emitido por el Banco Central de Qatar, está anclado al dólar estadounidense, respaldado por las exportaciones de gas natural.",
 },
 "fr": {
   "USD": "Le dollar américain, émis par la Réserve fédérale, est la première monnaie de réserve du monde et la plus échangée sur le marché des changes.",
   "EUR": "L'euro, émis par la Banque centrale européenne, est la monnaie officielle de la zone euro (20 pays) et la deuxième monnaie la plus échangée au monde.",
   "GBP": "La livre sterling, émise par la Banque d'Angleterre, est la monnaie la plus ancienne en circulation et une grande monnaie de réserve internationale.",
   "JPY": "Le yen japonais, émis par la Banque du Japon, est la troisième monnaie la plus échangée au monde et une valeur refuge traditionnelle.",
   "TRY": "La livre turque, émise par la banque centrale de la République de Turquie, a connu une forte inflation et une grande volatilité du taux de change ces dernières années.",
   "CNY": "Le yuan chinois (renminbi), géré par la Banque populaire de Chine, suit un régime de flottement contrôlé, et la paire yuan-dollar est l'une des plus suivies du commerce mondial.",
   "CHF": "Le franc suisse, émis par la Banque nationale suisse, est la monnaie de refuge par excellence, adossée à la stabilité politique et financière du pays.",
   "INR": "La roupie indienne, émise par la Banque de réserve de l'Inde, est la monnaie du pays le plus peuplé du monde et accueille d'importants flux de fonds venus de l'étranger.",
   "KRW": "Le won coréen, émis par la banque de Corée, est une devise asiatique très dynamique, largement suivie par les exportations de puces et d'automobiles du pays.",
   "AUD": "Le dollar australien, émis par la banque de réserve d'Australie, est une monnaie de matières premières et figure parmi les plus échangées au monde pour les minerais.",
   "CAD": "Le dollar canadien, émis par la Banque du Canada, est une devise étroitement liée aux prix du pétrole, un des gros enjeux pour l'économie du pays.",
   "MXN": "Le peso mexicain, émis par la banque centrale du Mexique, est la monnaie la plus échangée d'Amérique latine et réagit fortement à l'économie des États-Unis.",
   "BRL": "Le réal brésilien, émis par la banque centrale du Brésil, est la devise la plus échangée de l'Amérique du Sud, ainsi liée aux exportations de soja, de café et de minerai de fer.",
   "ZAR": "Le rand sud-africain, émis par la Banque de réserve d'Afrique du Sud, est la devise africaine la plus négociée, suivant les prix de l'or et du platine.",
   "RUB": "Le rouble russe, émis par la Banque de Russie, est la monnaie officielle de la Russie, dont la valeur dépend beaucoup des revenus d'exportation d'énergie.",
   "SAR": "Le rial saoudien, émis par la banque centrale d'Arabie saoudite (SAMA), est arrimé au dollar américain à un taux de change quasi fixe.",
   "AED": "Le dirham des Émirats arabes unis, émis par la banque centrale des Émirats, est arrimé au dollar, ce qui garantit la stabilité du commerce et du tourisme dans le Golfe.",
   "SEK": "La couronne suédoise, émise par la Riksbank, la plus ancienne banque centrale du monde, est la monnaie de la Suède, membre de l'UE n'ayant pas adopté l'euro.",
   "NOK": "La couronne norvégienne, émise par la banque centrale de Norvège, dépend largement du secteur pétrolier et gazier du pays.",
   "NZD": "Le dollar néo-zélandais, surnommé kiwi et émis par la Reserve Bank of New Zealand, est une monnaie de matières premières, liée aux exportations de produits laitiers.",
   "SGD": "Le dollar de Singapour, géré par l'Autorité monétaire de Singapour sur la base d'un panier de devises, est une devise stable propre au hub financier asiatique.",
   "HKD": "Le dollar de Hong Kong, émis dans le cadre du système monétaire de la ville (HKMA), se maintient vis-à-vis du dollar américain depuis 1983 avec une marge de l'oscillation entre 7,75 et 7,85.",
   "THB": "Le baht thaïlandais, émis par la banque de Thaïlande, est très utilisé dans l'Asie du Sud-Est pour le même commerce et le tourisme de la région.",
   "IDR": "La roupie indonésienne, émise par la Banque d'Indonésie, est la monnaie du pays le plus peuplé du sud-est asiatique et de la plus grande nation musulmane du monde.",
   "MYR": "Le ringgit de Malaisie, émis par la banque centrale de Malaisie, est une devise sensible à l'évolution du cours de l'huile de palme et du pétrole.",
   "BDT": "La taka du Bangladesh, émise par la banque du Bangladesh, est la devise d'une économie dépendante de l'exportation de textiles et de ses remises de fonds.",
   "PHP": "Le peso philippin, émis par la banque centrale des Philippines, est la monnaie d'un pays qui reçoit d'importants flux d'argent de la part de ses travailleurs expatriés.",
   "VND": "Le dong vietnamien, émis par la banque d'État du Vietnam, est l'une des monnaies du monde à la plus faible valeur unitaire.",
   "LAK": "Le kip laotien, émis par la Banque centrale du Laos, est la monnaie officielle du pays, à la présence discrète sur le marché des changes.",
   "PKR": "La roupie pakistanaise, émise par la Banque d'État du Pakistan, est la devise du cinquième pays le plus peuplé au monde, s'appuyant beaucoup sur les remes des travailleurs exilés.",
   "NGN": "Le naira nigérian, émis par la banque centrale du Nigeria, est la monnaie du pays le plus peuplé du Continent africain et dépend beaucoup du pétrole.",
   "EGP": "La livre égyptienne, émise par la banque centrale d'Égypte, est la monnaie du pays arabe le plus peuplé, avec le tourisme et le canal de Suez comme sources de devises.",
   "UAH": "La hryvnia ukrainienne, émise par la Banque nationale d'Ukraine, est la monnaie officielle de l'Ukraine, au régime de change flexible.",
   "PLN": "Le zloty polonais, émis par la Banque nationale de Pologne, est la monnaie de la plus grande économie d'Europe centrale, plutôt que de la zone euro.",
   "CZK": "La couronne tchèque, émise par la Banque nationale tchèque, est la monnaie de la République tchèque, membre de l'Union européenne n'ayant pas adopté l'euro.",
   "DKK": "La couronne danoise, émise par la Banque nationale du Danemark, suit une politique de parité quasi fixe vis-à-vis de l'euro.",
   "ILS": "Le nouveau shéquel israélien, émis par la Banque d'Israël, est une devise du Moyen-Orient très librement échangée, appuyée par l'économie high-tech du pays.",
   "QAR": "Le rial qatari, émis par la banque centrale du Qatar, est arrimé au dollar américain, fort de la production de gaz naturel du pays.",
   },
}