# -*- coding: utf-8 -*-
"""German (de) and Polish (pl) intros for the 38 hand-written currency pages.
One or two short, natural sentences per currency: issuer / central bank plus
one notable fact (reserve currency, peg, commodity, remittances, etc.)."""

ABOUT_BATCH = {
    "de": {
        "USD": "Der US-Dollar wird von der US-Notenbank ausgegeben und ist die wichtigste Reservewährung der Welt.",
        "EUR": "Der Euro wird von der Europäischen Zentralbank und dem Eurosystem ausgegeben und ist die offizielle Währung von 20 EU-Ländern.",
        "GBP": "Das britische Pfund wird von der Bank von England ausgegeben und ist eine der ältesten Währungen der Welt, die bis heute im Umlauf sind.",
        "JPY": "Der japanische Yen wird von der Bank von Japan ausgegeben und ist die dritthäufigste Währung im weltweiten Devisenhandel.",
        "TRY": "Die türkische Lira wird von der Zentralbank der Republik Türkei ausgegeben und leidet seit Jahren unter einer sehr hohen Inflation.",
        "CNY": "Der chinesische Yuan wird von der Volksbank von China unter gelenktem Wechselkurs ausgegeben; das Paar CNY/USD wird weltweit genau beobachtet.",
        "CHF": "Der Schweizer Franken wird von der Schweizerischen Nationalbank ausgegeben und gilt wegen der Stabilität des Landes als sicherer Hafen.",
        "INR": "Die indische Rupie wird von der Reserve Bank of India ausgegeben; Indien gehört zu den größten Empfängern von Rücküberweisungen weltweit.",
        "KRW": "Der südkoreanische Won wird von der Bank of Korea ausgegeben und hängt eng mit der globalen Nachfrage nach Halbleitern zusammen.",
        "AUD": "Der australische Dollar wird von der Reserve Bank of Australia ausgegeben und folgt den Weltmarktpreisen für Eisenerz und Kohle.",
        "CAD": "Der kanadische Dollar wird von der Bank of Canada ausgegeben; sein Wechselkurs reagiert stark auf die Ölpreise und den Energiehandel Nordamerikas.",
        "MXN": "Der mexikanische Peso wird von der Bank von Mexiko ausgegeben und ist die am häufigsten gehandelte Währung Lateinamerikas.",
        "BRL": "Der brasilianische Real wird von der brasilianischen Zentralbank ausgegeben und ist die Währung der größten Volkswirtschaft Lateinamerikas.",
        "ZAR": "Der südafrikanische Rand wird von der Südafrikanischen Reservebank ausgegeben und ist die am aktivsten gehandelte Währung Afrikas.",
        "RUB": "Der russische Rubel wird von der Zentralbank Russlands ausgegeben und hängt stark an den Öl- und Gasexporten des Landes.",
        "SAR": "Der Saudi-Riyal wird von der Zentralbank von Saudi-Arabien (SAMA) ausgegeben und ist seit 1986 zum festen Kurs von 3,75 an den US-Dollar gekoppelt.",
        "AED": "Der Dirham der Vereinigten Arabischen Emirate wird von der Zentralbank der Emirate ausgegeben und ist an den US-Dollar gekoppelt.",
        "SEK": "Die schwedische Krone wird von der Schwedischen Reichsbank (Riksbank) ausgegeben, der ältesten Zentralbank der Welt.",
        "NOK": "Die norwegische Krone wird von der Norges Bank ausgegeben und hängt stark an den Öl- und Gasexporten aus der Nordsee.",
        "NZD": "Der neuseeländische Dollar (Kiwi) wird von der Reserve Bank of New Zealand ausgegeben und folgt den Milch- und Agrarexportpreisen.",
        "SGD": "Der Singapur-Dollar wird von der Monetary Authority of Singapore (MAS) ausgegeben und gilt als eine der stabilsten Währungen Asiens.",
        "HKD": "Der Hongkong-Dollar ist im Band von 7,75–7,85 an den US-Dollar gekoppelt und wird unter Aufsicht der HKMA von drei Banken ausgegeben.",
        "THB": "Der thailändische Baht wird von der Bank of Thailand ausgegeben und spielt für den Tourismus und den Handel Südostasiens eine wichtige Rolle.",
        "IDR": "Die indonesische Rupie wird von der Bank Indonesiens ausgegeben und ist die Währung der größten Volkswirtschaft Südostasiens.",
        "MYR": "Der malaysische Ringgit wird von der Bank Negara Malaysia ausgegeben und hängt stark von den Palmöl- und Erdölpreisen ab.",
        "PHP": "Der philippinische Peso wird von der Zentralbank der Philippinen (BSP) ausgegeben; Überweisungen aus dem Ausland prägen den Wechselkurs.",
        "VND": "Der vietnamesische Dong wird von der Staatsbank von Vietnam ausgegeben und gehört zu den Währungen mit dem niedrigsten nominalen Wert der Welt.",
        "LAK": "Der laotische Kip wird von der Bank von Laos (Lao PDR) ausgegeben und ist die offizielle Währung des Landes.",
        "PKR": "Die pakistanische Rupie wird von der State Bank of Pakistan ausgegeben und ist die offizielle Währung Pakistans.",
        "BDT": "Der Taka wird von der Bank von Bangladesch ausgegeben; Bangladesch ist der zweitgrößte Bekleidungsexporteur und stark von Rücküberweisungen abhängig.",
        "NGN": "Die nigerianische Naira wird von der Zentralbank von Nigeria ausgegeben und ist die Währung des bevölkerungsreichsten Landes Afrikas.",
        "EGP": "Das ägyptische Pfund wird von der Zentralbank von Ägypten ausgegeben und ist eine der wichtigsten Währungen Nordafrikas.",
        "UAH": "Die ukrainische Hrywnja wird von der Nationalbank der Ukraine ausgegeben und ist die offizielle Währung der Ukraine.",
        "PLN": "Der polnische Zloty wird von der Nationalbank Polens (NBP) ausgegeben und ist die meistgehandelte Währung Ostmitteleuropas.",
        "CZK": "Die tschechische Krone wird von der Tschechischen Nationalbank ausgegeben und ist eine der aktivsten Währungen Ostmitteleuropas.",
        "DKK": "Die dänische Krone wird von der dänischen Nationalbank ausgegeben und ist über den Wechselkursmechanismus II (ERM II) eng an den Euro gekoppelt.",
        "ILS": "Der neue israelische Schekel wird von der Bank von Israel ausgegeben und gilt als Gradmesser für die regionale Lage und die Tech-Exporte des Landes.",
        "QAR": "Der katarische Riyal wird von der Katarischen Zentralbank (QCB) ausgegeben und ist mit 3,64 Rial fest an den US-Dollar gekoppelt."
    },
    "pl": {
        "USD": "Dolar USA jest emitowany przez Rezerwę Federalną i jest najważniejszą walutą rezerwową świata.",
        "EUR": "Euro jest emitowane przez Europejski Bank Centralny i jest oficjalną walutą 20 krajów strefy euro.",
        "GBP": "Funt szterling jest emitowany przez Bank Anglii i jest jedną z najstarszych walut, które pozostają w obiegu.",
        "JPY": "Jen japoński jest emitowany przez Bank Japonii i jest trzecią najczęściej handlowaną walutą na świecie.",
        "TRY": "Lira turecka jest emitowana przez Bank Centralny Turcji, a w ostatnich latach wysoka inflacja znacznie osłabiła jej kurs.",
        "CNY": "Chiński juan (renminbi) jest emitowany przez Ludowy Bank Chin; kurs pary CNY/USD jest ważny dla rynków globalnych.",
        "CHF": "Frank szwajcarski jest emitowany przez Szwajcarski Bank Narodowy i uchodzi za bezpieczną walutę.",
        "INR": "Rupia indyjska jest emitowana przez Bank Rezerw Indii, a przekazy z zagranicy mają duży wpływ na jej kurs.",
        "KRW": "Won koreański jest emitowany przez Bank Korei, a jego kurs silnie zależy od eksportu półprzewodników.",
        "AUD": "Dolar australijski jest emitowany przez Bank Rezerwowy Australii i jest walutą powiązaną z cenami rudy żelaza i węgla.",
        "CAD": "Dolar kanadyjski jest emitowany przez Bank Kanady, a jego kurs jest ściśle związany z cenami ropy naftowej.",
        "MXN": "Peso meksykańskie jest emitowane przez Bank Meksyku i jest najczęściej handlowaną walutą w Ameryce Łacińskiej.",
        "BRL": "Real brazylijski jest emitowany przez Bank Centralny Brazylii i jest walutą największej gospodarki Ameryki Łacińskiej.",
        "ZAR": "Rand Republiki Południowej Afryki jest emitowany przez Bank Rezerwowy i jest najczęściej handlowaną walutą w Afryce.",
        "RUB": "Rubel rosyjski jest emitowany przez Bank Centralny Rosji, a jego kurs mocno zależy od eksportu ropy i gazu.",
        "SAR": "Rial saudyjski jest emitowany przez Bank Centralny Arabii Saudyjskiej (SAMA) i jest powiązany z dolarem amerykańskim w ramach stałego kursu 3,75.",
        "AED": "Dirham ZEA jest emitowany przez Bank Centralny Zjednoczonych Emiratów Arabskich i jest powiązany z dolarem amerykańskim.",
        "SEK": "Korona szwedzka jest emitowana przez bank centralny Riksbank, który jest najstarszym bankiem centralnym świata.",
        "NOK": "Korona norweska jest emitowana przez bank centralny Norwegii, a jej kurs zależy od eksportu ropy naftowej i gazu.",
        "NZD": "Dolar nowozelandzki jest emitowany przez Reserve Bank of New Zealand i jest walutą towarową zależącą od cen produktów mlecznych.",
        "SGD": "Dolar singapurski jest emitowany przez Monetary Authority of Singapore (MAS) i jest jedną z najbardziej stabilnych walut Azji.",
        "HKD": "Dolar hongkoński jest powiązany z dolarem amerykańskim w paśmie 7,75–7,85, co zapewnia mu dużą stabilność.",
        "THB": "Bat tajlandzki jest emitowany przez Bank Tajlandii i odgrywa ważną rolę w turystyce oraz handlu regionu.",
        "IDR": "Rupia indonezyjska jest emitowana przez Bank Indonezji i jest walutą największej gospodarki Azji Południowo-Wschodniej.",
        "MYR": "Ringgit malezyjski jest emitowany przez Bank Negara Malaysia; jego kurs silnie zależy od cen oleju palmowego i ropy naftowej.",
        "PHP": "Peso filipińskie jest emitowane przez Bank Centralny Filipin (BSP), a jego kurs zależy od przekazów od pracowników za granicą.",
        "VND": "Dong wietnamski jest emitowany przez bank centralny Wietnamu i należy do walut o najniższej wartości rynkowej.",
        "LAK": "Kip laotański jest oficjalną walutą Laosu i jest emitowany przez Bank Centralny tego kraju.",
        "PKR": "Rupia pakistańska jest emitowana przez State Bank of Pakistan i jest oficjalną walutą kraju.",
        "BDT": "Taka bangladeska jest emitowana przez Bank Centralny Bangladeszu; Bangladesz jest drugim największym eksporterem odzieży na świecie.",
        "NGN": "Naira nigeryjska jest emitowana przez Bank Centralny Nigerii i jest walutą najbardziej zaludnionego kraju Afryki.",
        "EGP": "Funt egipski jest emitowany przez Bank Centralny Egiptu i jest jedną z ważniejszych walut w Afryce Północnej.",
        "UAH": "Hrywna ukraińska jest emitowana przez Bank Centralny Ukrainy i jest oficjalną walutą tego kraju.",
        "PLN": "Złoty polski jest emitowany przez Narodowy Bank Polski i jest najczęściej wymienianą walutą w Europie Środkowo-Wschodniej.",
        "CZK": "Korona czeska jest emitowana przez Czeski Bank Centralny i należy do aktywnie wymienianych walut regionu.",
        "DKK": "Korona duńska jest emitowana przez bank centralny Danii i jest powiązana z euro w systemie ERM II.",
        "ILS": "Szekel izraelski jest emitowany przez Bank Izraela i jest ważną walutą w regionie Bliskiego Wschodu.",
        "QAR": "Rial katarski jest emitowany przez Bank Centralny Kataru i jest powiązany z dolarem USA w paśmie 3,64."
    }
}
