# -*- coding: utf-8 -*-
"""Currency-specific intros, batch 2: Italian (it) and Dutch (nl).
1-2 sentences each, at most 150 characters, for the 38 currencies that
already have an English blurb. No brand mention; no template text."""

ABOUT_BATCH = {
 "it": {
  "AED": 'Il dirham degli Emirati Arabi Uniti, emesso dalla banca centrale degli Emirati, è ancorato al dollaro USA e sostiene il commercio nel Golfo.',
  "AUD": 'Il dollaro australiano, emesso dalla Reserve Bank of Australia, è una valuta legata alle materie prime, come il minerale di ferro.',
  "BDT": 'Il taka del Bangladesh, emesso dalla Bangladesh Bank, è sostenuto dalle esportazioni di indumenti e dalle grandi rimesse.',
  "BRL": "Il real brasiliano, emesso dalla Banca Centrale del Brasile, è la valuta della più grande economia dell'America Latina.",
  "CAD": 'Il dollaro canadese, emesso dalla Bank of Canada, è una valuta di materie prime il cui valore dipende dal petrolio.',
  "CHF": 'Il franco svizzero, emesso dalla Banca nazionale svizzera, serve la Svizzera e il Liechtenstein ed è una classica valuta rifugio.',
  "CNY": "Lo yuan cinese (renminbi) è gestito dalla People's Bank of China con un tasso di cambio controllato.",
  "CZK": 'La corona ceca, emessa dalla Banca Centrale Ceca, è la valuta della Repubblica Ceca.',
  "DKK": "La corona danese, emessa dalla Banca Nazionale di Danimarca, è mantenuta stabile nei confronti dell'euro grazie agli AEC II.",
  "EGP": "La sterlina egiziana, emessa dalla Banca Centrale d'Egitto, è la principale valuta del Nord Africa.",
  "EUR": "L'euro è la valuta ufficiale dei 20 paesi dell'area dell'euro e la seconda valuta di riserva del mondo.",
  "GBP": "La sterlina britannica, emessa dalla Banca d'Inghilterra, è una delle valute più antiche ancora in circolazione.",
  "HKD": 'Il dollaro di Hong Kong rimane in un intervallo ristretto compreso tra 7,75 e 7,85 per dollaro USA grazie al sistema di tassi di cambio collegato.',
  "IDR": 'La rupia indonesiana, emessa da Bank Indonesia, è la valuta della più grande economia del sud-est asiatico.',
  "ILS": "Il nuovo shekel israeliano è emesso dalla Banca di Israele ed è spesso visto come un barometro dell'economia high-tech della regione.",
  "INR": "La rupia indiana, emessa dalla Reserve Bank of India, è una delle valute più importanti dell'Asia meridionale.",
  "JPY": 'Lo yen giapponese, emesso dalla Banca del Giappone, è la terza valuta più scambiata al mondo.',
  "KRW": 'Il won sudcoreano, emesso dalla Bank of Korea, è strettamente legato alle esportazioni di semiconduttori ed elettronica.',
  "LAK": 'Il kip laotiano, emesso dalla Banca della Repubblica Popolare Democratica del Laos, è la valuta ufficiale del Laos.',
  "MXN": 'Il peso messicano, emesso dalla Banca del Messico, è la valuta più scambiata in America Latina.',
  "MYR": 'Il ringgit malese, emesso dalla banca centrale della Malesia, è influenzato dalle esportazioni di olio di palma e petrolio.',
  "NGN": "La naira nigeriana, emessa dalla Banca Centrale della Nigeria, è la valuta del paese più popoloso dell'Africa.",
  "NOK": 'La corona norvegese, emessa dalla banca centrale norvegese, segue il prezzo del petrolio e del gas.',
  "NZD": 'Il dollaro neozelandese, soprannominato kiwi, è emesso dalla Reserve Bank of New Zealand ed è una valuta legata alle materie prime.',
  "PHP": "Il peso filippino, emesso dalla banca centrale delle Filippine, risente molto delle rimesse dei lavoratori filippini all'estero.",
  "PKR": 'La rupia pakistana, emessa dalla Banca di Stato del Pakistan, è la valuta ufficiale del Pakistan.',
  "PLN": "Lo zloty polacco, emesso dalla Banca Nazionale di Polonia, è la valuta più scambiata nell'Europa centrale.",
  "QAR": 'Il riyal del Qatar, emesso dalla Banca Centrale del Qatar, è ancorato al dollaro USA a 3,64.',
  "RUB": 'Il rublo russo, emesso dalla Banca di Russia, è fortemente influenzato dalle esportazioni di energia e dalle sanzioni.',
  "SAR": 'Il riyal saudita, emesso dalla Banca centrale saudita, è stato ancorato al dollaro USA a circa 3,75 per decenni.',
  "SEK": 'La corona svedese è emessa dalla Riksbank, la più antica banca centrale del mondo.',
  "SGD": "Il dollaro di Singapore, gestito dall'Autorità Monetaria di Singapore, è una delle valute più stabili in Asia.",
  "THB": 'Il baht thailandese, emesso dalla Bank of Thailand, è ampiamente utilizzato nel turismo e nel commercio nel sud-est asiatico.',
  "TRY": "La lira turca, emessa dalla Banca Centrale della Turchia, ha affrontato un'elevata inflazione e una forte volatilità.",
  "UAH": "La grivna ucraina, emessa dalla Banca Nazionale dell'Ucraina, è la valuta ufficiale dell'Ucraina.",
  "USD": 'Il dollaro statunitense è la principale valuta di riserva mondiale ed è emesso dalla Federal Reserve.',
  "VND": 'Il dong vietnamita è emesso dalla Banca di Stato del Vietnam e ha un valore nominale molto basso.',
  "ZAR": "Il rand sudafricano, emesso dalla Reserve Bank of South Africa, è la valuta più scambiata dell'Africa, legata all'oro e al platino.",
 },
 "nl": {
  "AED": 'De VAE-dirham, uigegeven door de centrale bank van de Verenigde Arabische Emiraten, is gekoppeld aan de Amerikaanse dollar en stabiliseert de handel.',
  "AUD": 'De Australische dollar, uitgegeven door de Reserve Bank of Australia, is een grondstoffenvaluta waarvan de waarde vaak de ijzerertsprijzen volgt.',
  "BDT": 'De Bengaalse taka, uitgegeven door de Bangladesh Bank, wordt ondersteund door de export van kleding en grote overmakingen.',
  "BRL": 'De Braziliaanse real, uitgegeven door de Centrale Bank van Brazilië, is de munteenheid van de grootste economie in Latijns-Amerika.',
  "CAD": 'De Canadese dollar, uitgegeven door de Bank of Canada, is een grondstoffenvaluta waarvan de prijs afhankelijk is van olie.',
  "CHF": 'De Zwitserse frank, uitgegeven door de Zwitserse Nationale Bank, bedient Zwitserland en Liechtenstein en is een klassieke veiligehavenvaluta.',
  "CNY": "De Chinese yuan (renminbi) wordt beheerd door de People's Bank of China met een gecontroleerde wisselkoers.",
  "CZK": 'De Tsjechische kroon wordt uigegeven door de Tsjechische Nationale Bank en is de munteenheid van Tsjechië.',
  "DKK": 'De Deense kroon, uitgegeven door de Nationale Bank van Denemarken, wordt dankzij ERM II stabiel gehouden ten opzichte van de euro.',
  "EGP": 'Het Egyptische pond, uitgegeven door de Centrale Bank van Egypte, is de belangrijkste munteenheid van Noord-Afrika.',
  "EUR": 'De euro is de officiële munteenheid van de 20 landen van het eurogebied en de tweede reservevaluta van de wereld.',
  "GBP": 'Het Britse pond, uigegeven door de Bank of England, is een valuta die al heel lang in omloop is.',
  "HKD": 'De Hongkongse dollar blijft in een nauw bereik van 7,75 tot 7,85 per Amerikaanse dollar dankzij het gekoppelde wisselkoerssysteem.',
  "IDR": 'De Indonesische roepia, uitgegeven door Bank Indonesia, is de munteenheid van de grootste economie in Zuidoost-Azië.',
  "ILS": 'De Israëlische nieuwe shekel wordt uitgegeven door de Bank of Israel en wordt vaak gezien als een barometer van de high-tech economie van de regio.',
  "INR": "De Indiase roepie, uitgegeven door de Reserve Bank of India, is een van de belangrijkste valuta's in Zuid-Azië.",
  "JPY": 'De Japanse yen, uitgegeven door de Bank of Japan, is de op twee na meest verhandelde valuta ter wereld.',
  "KRW": 'De Zuid-Koreaanse won, uitgegeven door de Bank of Korea, is nauw verbonden met de export van halfgeleiders en elektronica.',
  "LAK": 'De Laotiaanse kip, uitgegeven door de Bank of the Lao PDR, is de officiële munteenheid van Laos.',
  "MXN": 'De Mexicaanse peso, uitgegeven door de Bank of Mexico, is de meest verhandelde valuta in Latijns-Amerika.',
  "MYR": 'De Maleisische ringgit, uitgegeven door de centrale bank van Maleisië, wordt beïnvloed door de export van palmolie en aardolie.',
  "NGN": 'De Nigeriaanse naira, uitgegeven door de Centrale Bank van Nigeria, is de munteenheid van het dichtstbevolkte land van Afrika.',
  "NOK": 'De Noorse kroon, uitgegeven door de Noorse centrale bank, volgt de prijs van olie en gas.',
  "NZD": 'De Nieuw-Zeelandse dollar, bijgenaamd de kiwi, wordt uitgegeven door de Reserve Bank of New Zealand en is een commodity-valuta.',
  "PHP": 'De Filippijnse peso wordt uigegeven door de centrale bank van de Filippijnen en wordt beïnvloed door geldovermakingen uit het buitenland.',
  "PKR": 'De Pakistaanse roepie, uitgegeven door de Staatsbank van Pakistan, is de officiële munteenheid van Pakistan.',
  "PLN": 'De Poolse zloty, uitgegeven door de Nationale Bank van Polen, is de meest verhandelde valuta in Centraal-Europa.',
  "QAR": 'De Qatarese riyal, uitgegeven door de Qatar Central Bank, is gekoppeld aan de Amerikaanse dollar op 3,64.',
  "RUB": 'De Russische roebel, uitgegeven door de Bank of Russia, wordt sterk beïnvloed door energie-export en sancties.',
  "SAR": 'De Saoedische riyal, uitgegeven door de Saoedische Centrale Bank, is al tientallen jaren gekoppeld aan de Amerikaanse dollar rond 3,75.',
  "SEK": 'De Zweedse kroon wordt uitgegeven door de Riksbank, de oudste centrale bank ter wereld.',
  "SGD": "De Singaporese dollar, beheerd door de Monetaire Autoriteit van Singapore, is een van de meest stabiele valuta's in Azië.",
  "THB": 'De Thaise baht, uitgegeven door de Bank of Thailand, wordt veel gebruikt in het toerisme en de handel in Zuidoost-Azië.',
  "TRY": 'De Turkse lira, uitgegeven door de Centrale Bank van Turkije, heeft te maken gehad met hoge inflatie en sterke volatiliteit.',
  "UAH": 'De Oekraïense hryvnia, uitgegeven door de Nationale Bank van Oekraïne, is de officiële munteenheid van Oekraïne.',
  "USD": "De Amerikaanse dollar is 's werelds belangrijkste reservevaluta en wordt uigegeven door de Federal Reserve.",
  "VND": 'De Vietnamese dong, uigegeven door de Staatsbank van Vietnam, heeft een bijzonder lage waarde.',
  "ZAR": 'De Zuid-Afrikaanse rand, uitgegeven door de Reserve Bank van Zuid-Afrika, is de meest verhandelde valuta van Afrika, gekoppeld aan goud en platina.',
 },
}
