# -*- coding: utf-8 -*-
"""Currency intros, batch 3: Portuguese (pt) and Russian (ru)."""

ABOUT_BATCH = {
 "pt": {
   "USD": "O dólar norte-americano é a principal moeda de reserva do mundo, emitida pela Reserva Federal.",
   "EUR": "O euro é a moeda oficial da zona euro, gerida pelo Banco Central Europeu.",
   "GBP": "A libra esterlina, emitida pelo Banco de Inglaterra, é a moeda mais antiga ainda em circulação.",
   "JPY": "O iene japonês, emitido pelo Banco do Japão, é a terceira moeda mais negociada do mundo.",
   "TRY": "A lira turca, sujeita a forte inflação, é a moeda oficial da Turquia.",
   "CNY": "O renminbi (yuan) chinês, gerido pelo Banco Popular da China, é uma das moedas mais acompanhadas do mundo.",
   "CHF": "O franco suíço, emitido pelo Banco Nacional Suíço, é considerado uma moeda de refúgio.",
   "INR": "A rupia indiana, moeda do país mais populoso do mundo, é muito usada nas remessas.",
   "KRW": "O won sul-coreano, emitido pelo Banco da Coreia, é muito negociado e reflete as exportações do país.",
   "AUD": "O dólar australiano é uma moeda que acompanha de perto os preços das matérias-primas.",
   "CAD": "O dólar canadiano responde com rapidez às variações do preço do petróleo.",
   "MXN": "O peso mexicano é a moeda mais negociada da América Latina, perto da economia dos Estados Unidos.",
   "BRL": "O real brasileiro é a moeda mais negociada da América do Sul, seguindo a soja e o minério.",
   "ZAR": "O rand sul-africano é a moeda africana mais negociada, sensível ao ouro e à platina.",
   "RUB": "O rublo é a moeda da Rússia, importante para o comércio mundial de energia.",
   "SAR": "O riyal saudita está indexado ao dólar americano, o que dá estabilidade ao comércio do Golfo.",
   "AED": "O dirham dos Emirados Árabes Unidos está indexado ao dólar e dá estabilidade ao comércio do Golfo.",
   "SEK": "A coroa sueca é a moeda da Suécia, emitida pelo Riksbank, o banco mais antigo do mundo.",
   "NOK": "A coroa norueguesa é a moeda da Noruega, influenciada pelo petróleo e o gás.",
   "NZD": "O dólar neozelandês é moeda de commodities, ligado ao sector leiteiro do país.",
   "SGD": "O dólar de Singapura é a moeda estável do centro financeiro da Ásia.",
   "DKK": "A coroa dinamarquesa é a moeda da Dinamarca, estável perto do euro.",
   "HKD": "O dólar de Hong Kong está indexado ao dólar americano desde 1983, num intervalo de 7,75 a 7,85.",
   "THB": "O baht tailandês é a moeda de um dos destinos turísticos mais procurados da Ásia.",
   "IDR": "A rupia indonésia é a moeda do país mais populoso do Sudeste Asiático.",
   "MYR": "O ringgit da Malásia reage aos preços do óleo de palma e do petróleo.",
   "PHP": "O peso filipino é a moeda de um país onde as remessas pesam muito.",
   "VND": "O dong vietnamita é uma das moedas de menor valor unitário do mundo.",
   "LAK": "O kip é a moeda oficial do Laos, país do Sudeste Asiático.",
   "PKR": "A rúpia paquistanesa é a moeda do quinto país mais populoso do mundo.",
   "BDT": "A taka é a moeda do Bangladesh, ligada aos têxteis e às remessas.",
   "NGN": "A naira é a moeda da Nigéria, o país mais populoso de África.",
   "EGP": "A libra egípcia é a moeda do país árabe mais populoso do mundo.",
   "UAH": "A hryvnia ucraniana é a moeda oficial da Ucrânia, emitida pelo Banco Nacional.",
   "PLN": "O zloty é a moeda da Polónia, um dos mercados mais ativos do Leste Europeu.",
   "CZK": "A coroa checa é a moeda oficial da República Checa, país da UE fora da zona euro.",
   "ILS": "O novo shekel é a moeda de Israel, apoiada pela economia tecnológica do país.",
   "QAR": "O riyal catari está indexado ao dólar, apoiado pelo gás natural do país.",
 },
 "ru": {
   "USD": "Доллар США — главная резервная валюта мира и самая торгуемая на валютном рынке.",
   "EUR": "Евро — официальная валюта еврозоны, выпускаемая Европейским центральным банком.",
   "GBP": "Фунт стерлингов, выпускаемый Банком Англии, — одна из старейших валют мира.",
   "JPY": "Японская иена, выпускаемая Банком Японии, — третья по объёму торговли валюта мира.",
   "TRY": "Турецкая лира — официальная валюта Турции, страдающая от высокой инфляции.",
   "CNY": "Китайский юань управляется Народным банком Китая и входит в корзину МВФ.",
   "CHF": "Швейцарский франк — традиционная валюта-убежище во всём мире, защищающая от кризиса.",
   "INR": "Индийская рупия — валюта самой населённой страны мира, куда поступает много денежных переводов.",
   "KRW": "Южнокорейская вона — валюта страны с сильным экспортом чипов и автомобилей.",
   "AUD": "Австралийский доллар — товарная валюта, чутко реагирующая на мировые цены на сырьё.",
   "CAD": "Канадский доллар тесно связан с ценами на нефть.",
   "MXN": "Мексиканский песо — самая торгуемая валюта Латинской Америки.",
   "BRL": "Бразильский деал — самая торгуемая валюта Южной Америки.",
   "ZAR": "Южноафриканский рэнд — самая торгуемая валюта Африки, реагирует на золото и платину.",
   "RUB": "Российский рубль — валюта России, важная для мирового рынка энергоресурсов.",
   "SAR": "Саудовский риал привязан к доллару США, что обеспечивает ему стабильность.",
   "AED": "Дирхам ОАЭ привязан к доллару США, обеспечивая стабильность для торговли региона.",
   "SEK": "Шведская крона — валюта Швеции, выпускаемая Риксбанком, старейшим банком мира.",
   "NOK": "Норвежская крона — валюта Норвегии, сильно зависящая от нефти и газа.",
   "NZD": "Новозеландский доллар — сырьевая валюта, связанная с молочным экспортом.",
   "SGD": "Сингапурский доллар — стабильная валюта финансового центра Азии.",
   "DKK": "Датская крона — валюта Дании, привязанная к европейской валюте.",
   "HKD": "Гонконгский доллар привязан к доллару США в диапазоне 7,75–7,85.",
   "THB": "Тайский бат — валюта одного из самых популярных туристических направлений Азии.",
   "IDR": "Индонезийская рупия — валюта самой многонаселённой страны Юго-Восточной Азии.",
   "MYR": "Малайзийский ринггит — валюта Малайзии, чувствительная к ценам на пальмовое масло.",
   "PHP": "Филиппинский песо — валюта страны, где большую роль играют денежные переводы.",
   "VND": "Вьетнамский донг — одна из валют мира с наименьшим номиналом.",
   "LAK": "Кип — официальная валюта Лаоса, страны Юго-Восточной Азии.",
   "PKR": "Пакистанская рупия — валюта пятой по населению страны мира.",
   "BDT": "Така — валюта Бангладеша, страны с большим экспортом одежды.",
   "NGN": "Найра — валюта Нигерии, самой населённой страны Африки.",
   "EGP": "Египетский фунт — валюта самой населённой арабской страны.",
   "UAH": "Украинская гривна — официальная валюта Украины, выпускаемая Национальным банком.",
   "PLN": "Польский злотый — валюта Польши, одного из крупнейших рынков Восточной Европы.",
   "CZK": "Чешская крона — официальная валюта Чехии.",
   "ILS": "Новый израильский шекель — валюта Израиля, экономика которого основана на технологиях.",
   "QAR": "Катарский риал привязан к доллару США благодаря запасам газа.",
 },
}
