# -*- coding: utf-8 -*-
"""Content-page framework strings, 29 languages.
Fixed parts of currency/guide/support pages (nav, buttons, disclaimers).
Article bodies stay English (marked lang="en") by design."""

CONTENT_UI = {
 "en": {
        "backHome":"← Fxverter — Currency Converter",
        "allCurrencies":"All currencies",
        "allGuides":"All guides",
        "convert":"Convert",
        "rateHead":"in major currencies",
        "chartHead":"1 {code} → USD · 30 days",
        "loading":"Fetching reference rates…",
        "ratesLoaded":"Live reference rates loaded",
        "ratesFail":"Rates temporarily unavailable — showing the converter only.",
        "calcPlaceholder":"Amount in",
        "errBox":"Rates are loading or unavailable — please open the main converter instead.",
        "disclaimer":"Rates are indicative reference rates from public sources (ECB via Frankfurter, ExchangeRate-API) and updated daily — verify with your bank before transacting. © 2026 Fxverter · Currency converter",
        "supportIntro":"Fxverter is free to use, with no ads and no tracking. If it helps you, a small contribution keeps it fast, free and independent. Payments are processed by Creem as merchant of record — your payment data is handled by Creem, not by this website.",
        "supportComing":"Support tiers are coming soon — check back shortly. ♥",
        "supportFirst":"Be the first supporter — your name (with your consent) will appear here.",
        "supportThanks":"Thank you! 🙏",
        "supportChoose":"Choose a tier",
        "supportPrivacyNote":"Supporters are listed only with their consent. © 2026 Fxverter",
        "guidesIntro":"Plain-language explanations of how exchange rates work, by the Fxverter team.",
        "guidesEmpty":"Guides are coming soon.",
        "curLangIntro":"Fxverter shows live reference exchange rates for 141 world currencies. Each currency has its own page with rates, quick facts and a calculator:",
 },
 "tr": {
        "backHome":"← Fxverter — Döviz Çevirici",
        "allCurrencies":"Tüm para birimleri",
        "allGuides":"Tüm rehberler",
        "convert":"Çevir",
        "rateHead":"başlıca para birimlerinde",
        "chartHead":"1 {code} → USD · 30 gün",
        "loading":"Kurlar alınıyor…",
        "ratesLoaded":"Canlı referans kurları yüklendi",
        "ratesFail":"Kurlar geçici olarak kullanılamıyor — yalnızca çevirici gösteriliyor.",
        "calcPlaceholder":"Miktar (",
        "errBox":"Kurlar yükleniyor veya kullanılamıyor — lütfen ana çeviriciyi açın.",
        "disclaimer":"Kurlar, halka açık kaynaklardan (Frankfurter üzerinden ECB, ExchangeRate-API) gelen ve günlük güncellenen gösterge niteliğindedir — işlem öncesi bankanızla doğrulayın. © 2026 Fxverter · Döviz çevirici",
        "supportIntro":"Fxverter ücretsizdir; reklam ve takip yoktur. İşinize yarıyorsa küçük bir katkı, aracın hızlı, ücretsiz ve bağımsız kalmasını sağlar. Ödemeler kayıt satıcısı olarak Creem tarafından işlenir.",
        "supportComing":"Destek seçenekleri çok yakında — tekrar uğrayın. ♥",
        "supportFirst":"İlk destekçi siz olun — adınız (onayınızla) burada görünecek.",
        "supportThanks":"Teşekkürler! 🙏",
        "supportChoose":"Bir destek seviyesi seçin",
        "supportPrivacyNote":"Destekçiler yalnızca onaylarıyla listelenir. © 2026 Fxverter",
        "guidesIntro":"Döviz kurlarının nasıl çalıştığına dair sade anlatımlar, Fxverter ekibinden.",
        "guidesEmpty":"Rehberler çok yakında.",
        "curLangIntro":"Fxverter, 141 dünya para birimi için canlı referans kurları gösterir. Her para biriminin kendi sayfası vardır:",
 },
 "zh": {
        "backHome":"← Fxverter — 货币换算器",
        "allCurrencies":"全部币种",
        "allGuides":"全部指南",
        "convert":"换算",
        "rateHead":"对主要货币",
        "chartHead":"1 {code} → USD · 30 天",
        "loading":"正在获取汇率…",
        "ratesLoaded":"实时参考汇率已加载",
        "ratesFail":"汇率暂时不可用——仅显示换算器。",
        "calcPlaceholder":"金额（",
        "errBox":"汇率正在加载或不可用——请使用主换算页面。",
        "disclaimer":"汇率为公开来源（欧洲央行 via Frankfurter、ExchangeRate-API）的参考汇率，每日更新——交易前请与银行核实。© 2026 Fxverter · 货币换算器",
        "supportIntro":"Fxverter 完全免费，无广告、无追踪。如果它对你有帮助，一份小小的支持能让它保持快速、免费和独立。付款由 Creem 作为记录商户处理。",
        "supportComing":"支持选项即将上线——敬请期待。♥",
        "supportFirst":"成为第一位支持者——经你同意后，你的名字将出现在这里。",
        "supportThanks":"谢谢你！🙏",
        "supportChoose":"选择支持档位",
        "supportPrivacyNote":"致谢名单仅在支持者同意后列出。© 2026 Fxverter",
        "guidesIntro":"用通俗的语言讲解汇率的运作方式，来自 Fxverter 团队。",
        "guidesEmpty":"指南即将上线。",
        "curLangIntro":"Fxverter 提供 141 种世界货币的实时参考汇率。每种货币都有专属页面（汇率、档案与换算器）：",
 },
 "ja": {
        "backHome":"← Fxverter — 通貨コンバーター",
        "allCurrencies":"すべての通貨",
        "allGuides":"すべてのガイド",
        "convert":"変換",
        "rateHead":"主要通貨でのレート",
        "chartHead":"1 {code} → USD · 30日間",
        "loading":"レートを取得中…",
        "ratesLoaded":"最新の参照レートを読み込みました",
        "ratesFail":"レートは一時的に利用できません — コンバーターのみ表示しています。",
        "calcPlaceholder":"金額（",
        "errBox":"レートを読み込み中か利用できません — メインのコンバーターをご利用ください。",
        "disclaimer":"レートは公開ソース（Frankfurter経由のECB、ExchangeRate-API）による参考値で、毎日更新されます — 取引前に銀行でご確認ください。© 2026 Fxverter · 通貨コンバーター",
        "supportIntro":"Fxverterは無料で、広告もトラッキングもありません。お役に立てた場合は、少額のご支援がこのツールの維持に役立ちます。お支払いは記録事業者としてCreemが処理します。",
        "supportComing":"支援オプションは近日公開予定です。♥",
        "supportFirst":"最初のサポーターになりましょう — 同意いただければお名前がここに表示されます。",
        "supportThanks":"ありがとうございます！🙏",
        "supportChoose":"支援レベルを選択",
        "supportPrivacyNote":"サポーターは本人の同意がある場合のみ掲載します。© 2026 Fxverter",
        "guidesIntro":"為替レートの仕組みをわかりやすく解説する Fxverter チームのガイド。",
        "guidesEmpty":"ガイドは近日公開予定です。",
        "curLangIntro":"Fxverterは141の通貨のリアルタイム参照レートを提供します。各通貨には専用ページがあります：",
 },
 "de": {
        "backHome":"← Fxverter — Währungsrechner",
        "allCurrencies":"Alle Währungen",
        "allGuides":"Alle Ratgeber",
        "convert":"Umrechnen",
        "rateHead":"in Hauptwährungen",
        "chartHead":"1 {code} → USD · 30 Tage",
        "loading":"Kurse werden geladen…",
        "ratesLoaded":"Referenzkurse geladen",
        "ratesFail":"Kurse vorübergehend nicht verfügbar — nur der Rechner wird angezeigt.",
        "calcPlaceholder":"Betrag in",
        "errBox":"Kurse werden geladen oder sind nicht verfügbar — bitte den Haupt-Rechner öffnen.",
        "disclaimer":"Kurse sind Richtwerte aus öffentlichen Quellen (EZB über Frankfurter, ExchangeRate-API) und werden täglich aktualisiert — vor Transaktionen mit der Bank abstimmen. © 2026 Fxverter · Währungsrechner",
        "supportIntro":"Fxverter ist kostenlos, ohne Werbung und ohne Tracking. Eine kleine Unterstützung hilft, das Tool schnell, frei und unabhängig zu halten. Zahlungen werden von Creem als Merchant of Record abgewickelt.",
        "supportComing":"Unterstützungsstufen folgen in Kürze. ♥",
        "supportFirst":"Werden Sie erste:r Unterstützer:in — mit Ihrer Zustimmung erscheint Ihr Name hier.",
        "supportThanks":"Vielen Dank! 🙏",
        "supportChoose":"Stufe wählen",
        "supportPrivacyNote":"Unterstützer werden nur mit Zustimmung genannt. © 2026 Fxverter",
        "guidesIntro":"Verständliche Erklärungen zu Wechselkursen vom Fxverter-Team.",
        "guidesEmpty":"Ratgeber folgen in Kürze.",
        "curLangIntro":"Fxverter zeigt Referenzkurse für 141 Weltwährungen. Jede Währung hat eine eigene Seite:",
 },
 "fr": {
        "backHome":"← Fxverter — Convertisseur",
        "allCurrencies":"Toutes les devises",
        "allGuides":"Tous les guides",
        "convert":"Convertir",
        "rateHead":"dans les principales devises",
        "chartHead":"1 {code} → USD · 30 jours",
        "loading":"Récupération des taux…",
        "ratesLoaded":"Taux de référence chargés",
        "ratesFail":"Taux momentanément indisponibles — seul le convertisseur est affiché.",
        "calcPlaceholder":"Montant en",
        "errBox":"Taux en cours de chargement ou indisponibles — ouvrez le convertisseur principal.",
        "disclaimer":"Taux indicatifs issus de sources publiques (BCE via Frankfurter, ExchangeRate-API), mis à jour quotidiennement — vérifiez avec votre banque avant toute transaction. © 2026 Fxverter · Convertisseur",
        "supportIntro":"Fxverter est gratuit, sans publicité ni pistage. Une petite contribution aide à le garder rapide, gratuit et indépendant. Les paiements sont traités par Creem en tant que marchand de référence.",
        "supportComing":"Les niveaux de soutien arrivent bientôt. ♥",
        "supportFirst":"Soyez le premier soutien — votre nom apparaîtra ici avec votre accord.",
        "supportThanks":"Merci ! 🙏",
        "supportChoose":"Choisir un niveau",
        "supportPrivacyNote":"Les soutiens ne sont listés qu'avec leur consentement. © 2026 Fxverter",
        "guidesIntro":"Des explications claires sur les taux de change, par l'équipe Fxverter.",
        "guidesEmpty":"Guides bientôt disponibles.",
        "curLangIntro":"Fxverter affiche les taux de référence de 141 devises. Chaque devise a sa page dédiée :",
 },
 "es": {
        "backHome":"← Fxverter — Conversor",
        "allCurrencies":"Todas las divisas",
        "allGuides":"Todas las guías",
        "convert":"Convertir",
        "rateHead":"en divisas principales",
        "chartHead":"1 {code} → USD · 30 días",
        "loading":"Obteniendo tipos…",
        "ratesLoaded":"Tipos de referencia cargados",
        "ratesFail":"Tipos no disponibles temporalmente — se muestra solo el conversor.",
        "calcPlaceholder":"Cantidad en",
        "errBox":"Los tipos se están cargando o no están disponibles — abre el conversor principal.",
        "disclaimer":"Tipos orientativos de fuentes públicas (BCE vía Frankfurter, ExchangeRate-API), actualizados a diario — confirma con tu banco antes de operar. © 2026 Fxverter · Conversor",
        "supportIntro":"Fxverter es gratuito, sin anuncios ni rastreo. Una pequeña contribución ayuda a mantenerlo rápido, libre e independiente. Los pagos los procesa Creem como comerciante de referencia.",
        "supportComing":"Los niveles de apoyo llegarán pronto. ♥",
        "supportFirst":"Sé el primer mecenas — tu nombre aparecerá aquí con tu consentimiento.",
        "supportThanks":"¡Gracias! 🙏",
        "supportChoose":"Elige un nivel",
        "supportPrivacyNote":"Los mecenas se listan solo con su consentimiento. © 2026 Fxverter",
        "guidesIntro":"Explicaciones claras sobre los tipos de cambio, del equipo de Fxverter.",
        "guidesEmpty":"Guías muy pronto.",
        "curLangIntro":"Fxverter muestra tipos de referencia de 141 divisas. Cada divisa tiene su propia página:",
 },
 "pt": {
        "backHome":"← Fxverter — Conversor",
        "allCurrencies":"Todas as moedas",
        "allGuides":"Todos os guias",
        "convert":"Converter",
        "rateHead":"nas principais moedas",
        "chartHead":"1 {code} → USD · 30 dias",
        "loading":"Buscando taxas…",
        "ratesLoaded":"Taxas de referência carregadas",
        "ratesFail":"Taxas temporariamente indisponíveis — mostrando apenas o conversor.",
        "calcPlaceholder":"Valor em",
        "errBox":"Taxas carregando ou indisponíveis — abra o conversor principal.",
        "disclaimer":"Taxas referenciais de fontes públicas (BCE via Frankfurter, ExchangeRate-API), atualizadas diariamente — confirme com seu banco antes de transacionar. © 2026 Fxverter · Conversor",
        "supportIntro":"O Fxverter é gratuito, sem anúncios e sem rastreamento. Uma pequena contribuição ajuda a mantê-lo rápido, gratuito e independente. Os pagamentos são processados pela Creem como merchant of record.",
        "supportComing":"Níveis de apoio em breve. ♥",
        "supportFirst":"Seja o primeiro apoiador — seu nome aparecerá aqui com seu consentimento.",
        "supportThanks":"Obrigado! 🙏",
        "supportChoose":"Escolha um nível",
        "supportPrivacyNote":"Apoiadores são listados apenas com consentimento. © 2026 Fxverter",
        "guidesIntro":"Explicações simples sobre taxas de câmbio, pela equipe Fxverter.",
        "guidesEmpty":"Guias em breve.",
        "curLangIntro":"O Fxverter mostra taxas de referência de 141 moedas. Cada moeda tem sua própria página:",
 },
 "ru": {
        "backHome":"← Fxverter — Конвертер",
        "allCurrencies":"Все валюты",
        "allGuides":"Все руководства",
        "convert":"Конвертировать",
        "rateHead":"в основных валютах",
        "chartHead":"1 {code} → USD · 30 дней",
        "loading":"Загрузка курсов…",
        "ratesLoaded":"Курсы загружены",
        "ratesFail":"Курсы временно недоступны — показан только конвертер.",
        "calcPlaceholder":"Сумма в",
        "errBox":"Курсы загружаются или недоступны — откройте основной конвертер.",
        "disclaimer":"Курсы носят справочный характер из публичных источников (ЕЦБ через Frankfurter, ExchangeRate-API), обновляются ежедневно — перед сделками сверяйтесь с банком. © 2026 Fxverter · Конвертер",
        "supportIntro":"Fxverter бесплатен, без рекламы и слежки. Небольшой вклад помогает сохранять его быстрым, бесплатным и независимым. Платежи обрабатывает Creem как merchant of record.",
        "supportComing":"Уровни поддержки скоро появятся. ♥",
        "supportFirst":"Станьте первымsupporter — с вашего согласия ваше имя появится здесь.",
        "supportThanks":"Спасибо! 🙏",
        "supportChoose":"Выберите уровень",
        "supportPrivacyNote":"Спонсоры перечисляются только с их согласия. © 2026 Fxverter",
        "guidesIntro":"Понятные объяснения о курсах валют от команды Fxverter.",
        "guidesEmpty":"Руководства скоро появятся.",
        "curLangIntro":"Fxverter показывает справочные курсы 141 валюты. У каждой валюты своя страница:",
 },
 "ar": {
        "backHome":"← Fxverter — محول العملات",
        "allCurrencies":"جميع العملات",
        "allGuides":"جميع الأدلة",
        "convert":"تحويل",
        "rateHead":"في العملات الرئيسية",
        "chartHead":"1 {code} → USD · 30 يومًا",
        "loading":"جارٍ جلب الأسعار…",
        "ratesLoaded":"تم تحميل أسعار المرجع",
        "ratesFail":"الأسعار غير متاحة مؤقتًا — يُعرض المحول فقط.",
        "calcPlaceholder":"المبلغ بـ",
        "errBox":"الأسعار قيد التحميل أو غير متاحة — افتح المحول الرئيسي.",
        "disclaimer":"الأسعار مرجعية من مصادر عامة (البنك المركزي الأوروبي عبر Frankfurter، ExchangeRate-API) وتُحدَّث يوميًا — تحقق مع بنكك قبل أي معاملة. © 2026 Fxverter · محول عملات",
        "supportIntro":"Fxverter مجاني، بدون إعلانات أو تتبع. مساهمة صغيرة تساعد على بقائه سريعًا ومجانيًا ومستقلًا. تُعالج المدفوعات عبر Creem.",
        "supportComing":"مستويات الدعم قريبًا. ♥",
        "supportFirst":"كن أول داعم — سيظهر اسمك هنا بموافقتك.",
        "supportThanks":"شكرًا! 🙏",
        "supportChoose":"اختر مستوى",
        "supportPrivacyNote":"يُدرج الداعمون فقط بموافقتهم. © 2026 Fxverter",
        "guidesIntro":"شرح مبسّط لأسعار الصرف من فريق Fxverter.",
        "guidesEmpty":"الأدلة قريبًا.",
        "curLangIntro":"يعرض Fxverter أسعار مرجعية لـ 131 عملة عالمية. لكل عملة صفحة خاصة:",
 },
 "hi": {
        "backHome":"← Fxverter — करेंसी कनवर्टर",
        "allCurrencies":"सभी मुद्राएँ",
        "allGuides":"सभी गाइड",
        "convert":"बदलें",
        "rateHead":"प्रमुख मुद्राओं में",
        "chartHead":"1 {code} → USD · 30 दिन",
        "loading":"दरें प्राप्त हो रही हैं…",
        "ratesLoaded":"संदर्भ दरें लोड हो गईं",
        "ratesFail":"दरें अस्थायी रूप से उपलब्ध नहीं — केवल कनवर्टर दिख रहा है।",
        "calcPlaceholder":"राशि (",
        "errBox":"दरें लोड हो रही हैं या उपलब्ध नहीं — मुख्य कनवर्टर खोलें।",
        "disclaimer":"दरें सार्वजनिक स्रोतों (ECB via Frankfurter, ExchangeRate-API) से सांकेतिक हैं, रोज़ अपडेट होती हैं — लेन-देन से पहले बैंक से पुष्टि करें। © 2026 Fxverter · करेंसी कनवर्टर",
        "supportIntro":"Fxverter निःशुल्क है, बिना विज्ञापन और ट्रैकिंग। छोटा सहयोग इसे तेज़, मुफ़्त और स्वतंत्र बनाए रखता है। भुगतान Creem द्वारा संसाधित होता है।",
        "supportComing":"सहयोग स्तर जल्द आ रहे हैं। ♥",
        "supportFirst":"पहले समर्थक बनें — आपकी सहमति से आपका नाम यहाँ दिखेगा।",
        "supportThanks":"धन्यवाद! 🙏",
        "supportChoose":"स्तर चुनें",
        "supportPrivacyNote":"समर्थक केवल सहमति से सूचीबद्ध होते हैं। © 2026 Fxverter",
        "guidesIntro":"विनिमय दरों की सरल व्याख्या, Fxverter टीम से।",
        "guidesEmpty":"गाइड जल्द आ रहे हैं।",
        "curLangIntro":"Fxverter 141 मुद्राओं की लाइव दरें दिखाता है। प्रत्येक मुद्रा का अपना पृष्ठ है:",
 },
 "id": {
        "backHome":"← Fxverter — Konverter",
        "allCurrencies":"Semua mata uang",
        "allGuides":"Semua panduan",
        "convert":"Konversi",
        "rateHead":"dalam mata uang utama",
        "chartHead":"1 {code} → USD · 30 hari",
        "loading":"Mengambil kurs…",
        "ratesLoaded":"Kurs referensi dimuat",
        "ratesFail":"Kurs sementara tidak tersedia — hanya konverter yang ditampilkan.",
        "calcPlaceholder":"Jumlah dalam",
        "errBox":"Kurs sedang dimuat atau tidak tersedia — buka konverter utama.",
        "disclaimer":"Kurs bersifat indikatif dari sumber publik, diperbarui harian — konfirmasi dengan bank Anda. © 2026 Fxverter · Konverter",
        "supportIntro":"Fxverter gratis, tanpa iklan dan pelacakan. Kontribusi kecil membantu menjaganya tetap cepat, gratis, dan independen. Pembayaran diproses oleh Creem.",
        "supportComing":"Tingkat dukungan segera hadir. ♥",
        "supportFirst":"Jadi pendukung pertama — nama Anda akan tampil di sini dengan persetujuan Anda.",
        "supportThanks":"Terima kasih! 🙏",
        "supportChoose":"Pilih tingkat",
        "supportPrivacyNote":"Pendukung hanya ditampilkan dengan persetujuan. © 2026 Fxverter",
        "guidesIntro":"Penjelasan sederhana tentang kurs dari tim Fxverter.",
        "guidesEmpty":"Panduan segera hadir.",
        "curLangIntro":"Fxverter menampilkan kurs referensi untuk 141 mata uang. Setiap mata uang punya halamannya sendiri:",
 },
 "ms": {
        "backHome":"← Fxverter — Penukar",
        "allCurrencies":"Semua mata wang",
        "allGuides":"Semua panduan",
        "convert":"Tukar",
        "rateHead":"dalam mata wang utama",
        "chartHead":"1 {code} → USD · 30 hari",
        "loading":"Mendapatkan kadar…",
        "ratesLoaded":"Kadar rujukan dimuatkan",
        "ratesFail":"Kadar tidak tersedia buat sementara — hanya penukar dipaparkan.",
        "calcPlaceholder":"Jumlah dalam",
        "errBox":"Kadar sedang dimuatkan atau tidak tersedia — buka penukar utama.",
        "disclaimer":"Kadar adalah indikatif daripada sumber awam, dikemas kini setiap hari — sahkan dengan bank anda. © 2026 Fxverter · Penukar",
        "supportIntro":"Fxverter percuma, tanpa iklan dan penjejakan. Sumbangan kecil membantu mengekalkannya pantas, percuma dan bebas. Bayaran diproses oleh Creem.",
        "supportComing":"Tahap sokongan akan datang tidak lama lagi. ♥",
        "supportFirst":"Jadi penyokong pertama — nama anda akan dipaparkan di sini dengan kebenaran anda.",
        "supportThanks":"Terima kasih! 🙏",
        "supportChoose":"Pilih tahap",
        "supportPrivacyNote":"Penyokong hanya disenaraikan dengan kebenaran mereka. © 2026 Fxverter",
        "guidesIntro":"Penjelasan ringkas tentang kadar pertukaran daripada pasukan Fxverter.",
        "guidesEmpty":"Panduan akan datang tidak lama lagi.",
        "curLangIntro":"Fxverter memaparkan kadar rujukan untuk 141 mata wang. Setiap mata wang mempunyai halaman sendiri:",
 },
 "ko": {
        "backHome":"← Fxverter — 환율 계산기",
        "allCurrencies":"모든 통화",
        "allGuides":"모든 가이드",
        "convert":"변환",
        "rateHead":"주요 통화 대비",
        "chartHead":"1 {code} → USD · 30일",
        "loading":"환율 가져오는 중…",
        "ratesLoaded":"기준 환율 로드됨",
        "ratesFail":"환율을 일시적으로 사용할 수 없습니다 — 변환기만 표시됩니다.",
        "calcPlaceholder":"금액 (",
        "errBox":"환율을 로드 중이거나 사용할 수 없습니다 — 메인 변환기를 여세요.",
        "disclaimer":"환율은 공개 소스의 참고용이며 매일 갱신됩니다 — 거래 전 은행에 확인하세요. © 2026 Fxverter · 환율 계산기",
        "supportIntro":"Fxverter는 무료이며 광고와 추적이 없습니다. 작은 후원이 이 도구를 빠르고 무료로 유지합니다. 결제는 Creem이 처리합니다.",
        "supportComing":"후원 옵션은 곧 공개됩니다. ♥",
        "supportFirst":"첫 후원자가 되어보세요 — 동의하시면 이름이 여기 표시됩니다.",
        "supportThanks":"감사합니다! 🙏",
        "supportChoose":"후원 수준 선택",
        "supportPrivacyNote":"후원자는 동의한 경우에만 표시됩니다. © 2026 Fxverter",
        "guidesIntro":"환율 작동 방식에 대한 쉬운 설명, Fxverter 팀.",
        "guidesEmpty":"가이드가 곧 공개됩니다.",
        "curLangIntro":"Fxverter는 141개 통화의 실시간 참조 환율을 제공합니다. 각 통화마다 전용 페이지가 있습니다:",
 },
 "vi": {
        "backHome":"← Fxverter — Chuyển đổi tiền tệ",
        "allCurrencies":"Tất cả tiền tệ",
        "allGuides":"Tất cả cẩm nang",
        "convert":"Chuyển đổi",
        "rateHead":"trong các tiền tệ chính",
        "chartHead":"1 {code} → USD · 30 ngày",
        "loading":"Đang lấy tỷ giá…",
        "ratesLoaded":"Đã tải tỷ giá tham chiếu",
        "ratesFail":"Tỷ giá tạm thời không khả dụng — chỉ hiển thị bộ chuyển đổi.",
        "calcPlaceholder":"Số tiền (",
        "errBox":"Tỷ giá đang tải hoặc không khả dụng — hãy mở bộ chuyển đổi chính.",
        "disclaimer":"Tỷ giá mang tính tham khảo, cập nhật hàng ngày — xác nhận với ngân hàng trước khi giao dịch. © 2026 Fxverter · Chuyển đổi tiền tệ",
        "supportIntro":"Fxverter miễn phí, không quảng cáo và không theo dõi. Một đóng góp nhỏ giúp duy trì công cụ nhanh, miễn phí và độc lập. Thanh toán được Creem xử lý.",
        "supportComing":"Các mức ủng hộ sắp ra mắt. ♥",
        "supportFirst":"Hãy là người ủng hộ đầu tiên — tên bạn sẽ xuất hiện ở đây nếu bạn đồng ý.",
        "supportThanks":"Cảm ơn! 🙏",
        "supportChoose":"Chọn mức",
        "supportPrivacyNote":"Người ủng hộ chỉ được liệt kê khi đồng ý. © 2026 Fxverter",
        "guidesIntro":"Giải thích dễ hiểu về tỷ giá, từ đội ngũ Fxverter.",
        "guidesEmpty":"Cẩm nang sắp ra mắt.",
        "curLangIntro":"Fxverter hiển thị tỷ giá tham chiếu của 141 tiền tệ. Mỗi tiền tệ có trang riêng:",
 },
 "th": {
        "backHome":"← Fxverter — ตัวแปลงสกุลเงิน",
        "allCurrencies":"สกุลเงินทั้งหมด",
        "allGuides":"คู่มือทั้งหมด",
        "convert":"แปลง",
        "rateHead":"ในสกุลเงินหลัก",
        "chartHead":"1 {code} → USD · 30 วัน",
        "loading":"กำลังดึงอัตรา…",
        "ratesLoaded":"โหลดอัตราอ้างอิงแล้ว",
        "ratesFail":"อัตราใช้งานไม่ได้ชั่วคราว — แสดงเฉพาะตัวแปลง",
        "calcPlaceholder":"จำนวน (",
        "errBox":"กำลังโหลดอัตราหรือไม่พร้อมใช้งาน — โปรดเปิดตัวแปลงหลัก",
        "disclaimer":"อัตราเป็นข้อมูลอ้างอิง อัปเดตรายวัน — ตรวจสอบกับธนาคารก่อนทำธุรกรรม © 2026 Fxverter · ตัวแปลงสกุลเงิน",
        "supportIntro":"Fxverter ฟรี ไม่มีโฆษณาและการติดตาม การสนับสนุนเล็กน้อยช่วยให้เครื่องมือเร็ว ฟรี และเป็นอิสระ การชำระเงินดำเนินการโดย Creem",
        "supportComing":"ระดับการสนับสนุนมาเร็ว ๆ นี้ ♥",
        "supportFirst":"เป็นผู้สนับสนุนคนแรก — ชื่อของคุณจะแสดงที่นี่หากคุณยินยอม",
        "supportThanks":"ขอบคุณ! 🙏",
        "supportChoose":"เลือกระดับ",
        "supportPrivacyNote":"แสดงรายชื่อผู้สนับสนุนเฉพาะเมื่อได้รับความยินยอม © 2026 Fxverter",
        "guidesIntro":"คำอธิบายง่าย ๆ เกี่ยวกับอัตราแลกเปลี่ยน จากทีม Fxverter",
        "guidesEmpty":"คู่มือมาเร็ว ๆ นี้",
        "curLangIntro":"Fxverter แสดงอัตราอ้างอิงของ 141 สกุลเงิน แต่ละสกุลเงินมีหน้าของตัวเอง:",
 },
 "fa": {
        "backHome":"← Fxverter — مبدل ارز",
        "allCurrencies":"همه ارزها",
        "allGuides":"همه راهنماها",
        "convert":"تبدیل",
        "rateHead":"در ارزهای اصلی",
        "chartHead":"1 {code} → USD · 30 روز",
        "loading":"در حال دریافت نرخ…",
        "ratesLoaded":"نرخ مرجع بارگذاری شد",
        "ratesFail":"نرخ‌ها موقتاً در دسترس نیستند — فقط مبدل نمایش داده می‌شود.",
        "calcPlaceholder":"مبلغ (",
        "errBox":"نرخ‌ها در حال بارگذاری‌اند یا در دسترس نیستند — مبدل اصلی را باز کنید.",
        "disclaimer":"نرخ‌ها راهنما و روزانه به‌روزرسانی می‌شوند — پیش از تراکنش با بانک تأیید کنید. © 2026 Fxverter · مبدل ارز",
        "supportIntro":"Fxverter رایگان است، بدون تبلیغ و ردیابی. کمک کوچک آن را سریع، رایگان و مستقل نگه می‌دارد. پرداخت‌ها توسط Creem پردازش می‌شود.",
        "supportComing":"سطوح حمایت به‌زودی. ♥",
        "supportFirst":"اولین حامی شوید — نام شما با موافقتتان اینجا نمایش داده می‌شود.",
        "supportThanks":"ممنون! 🙏",
        "supportChoose":"انتخاب سطح",
        "supportPrivacyNote":"حامیان فقط با رضایت خود فهرست می‌شوند. © 2026 Fxverter",
        "guidesIntro":"توضیح ساده درباره نرخ ارز، از تیم Fxverter.",
        "guidesEmpty":"راهنماها به‌زودی.",
        "curLangIntro":"Fxverter نرخ مرجع 141 ارز را نمایش می‌دهد. هر ارز صفحه مخصوص خود را دارد:",
 },
 "uk": {
        "backHome":"← Fxverter — Конвертер",
        "allCurrencies":"Усі валюти",
        "allGuides":"Усі посібники",
        "convert":"Конвертувати",
        "rateHead":"в основних валютах",
        "chartHead":"1 {code} → USD · 30 днів",
        "loading":"Завантаження курсів…",
        "ratesLoaded":"Курси завантажено",
        "ratesFail":"Курси тимчасово недоступні — показано лише конвертер.",
        "calcPlaceholder":"Сума в",
        "errBox":"Курси завантажуються або недоступні — відкрийте основний конвертер.",
        "disclaimer":"Курси довідкові, щодня оновлюються — перед операціями звірте з банком. © 2026 Fxverter · Конвертер",
        "supportIntro":"Fxverter безкоштовний, без реклами й відстеження. Невеликий внесок допомагає зберігати його швидким і незалежним. Платежі обробляє Creem.",
        "supportComing":"Рівні підтримки незабаром. ♥",
        "supportFirst":"Станьте першим прихильником — за вашої згоди ваше ім'я з'явиться тут.",
        "supportThanks":"Дякуємо! 🙏",
        "supportChoose":"Оберіть рівень",
        "supportPrivacyNote":"Прихильники перелічуються лише зі згоди. © 2026 Fxverter",
        "guidesIntro":"Зрозумілі пояснення про курси валют від команди Fxverter.",
        "guidesEmpty":"Посібники незабаром.",
        "curLangIntro":"Fxverter показує довідкові курси 141 валюти. Кожна валюта має власну сторінку:",
 },
 "el": {
        "backHome":"← Fxverter — Μετατροπέας",
        "allCurrencies":"Όλα τα νομίσματα",
        "allGuides":"Όλοι οι οδηγοί",
        "convert":"Μετατροπή",
        "rateHead":"σε κύρια νομίσματα",
        "chartHead":"1 {code} → USD · 30 ημέρες",
        "loading":"Λήψη ισοτιμιών…",
        "ratesLoaded":"Οι ισοτιμίες αναφοράς φορτώθηκαν",
        "ratesFail":"Οι ισοτιμίες είναι προσωρινά μη διαθέσιμες.",
        "calcPlaceholder":"Ποσό σε",
        "errBox":"Οι ισοτιμίες φορτώνονται ή δεν είναι διαθέσιμες — ανοίξτε τον κύριο μετατροπέα.",
        "disclaimer":"Οι ισοτιμίες είναι ενδεικτικές, ενημερώνονται καθημερινά — επιβεβαιώστε με την τράπεζά σας. © 2026 Fxverter · Μετατροπέας",
        "supportIntro":"Το Fxverter είναι δωρεάν, χωρίς διαφημίσεις και παρακολούθηση. Μια μικρή συνεισφορά το κρατά γρήγορο και ανεξάρτητο. Οι πληρωμές επεξεργάζονται από την Creem.",
        "supportComing":"Τα επίπεδα υποστήριξης έρχονται σύντομα. ♥",
        "supportFirst":"Γίνετε ο πρώτος υποστηρικτής — το όνομά σας θα εμφανιστεί εδώ με τη συγκατάθεσή σας.",
        "supportThanks":"Ευχαριστούμε! 🙏",
        "supportChoose":"Επιλέξτε επίπεδο",
        "supportPrivacyNote":"Οι υποστηρικτές παρατίθενται μόνο με συγκατάθεση. © 2026 Fxverter",
        "guidesIntro":"Απλές εξηγήσεις για τις ισοτιμίες, από την ομάδα του Fxverter.",
        "guidesEmpty":"Οι οδηγοί έρχονται σύντομα.",
        "curLangIntro":"Το Fxverter δείχνει ισοτιμίες αναφοράς για 141 νομίσματα. Κάθε νόμισμα έχει τη δική του σελίδα:",
 },
 "bn": {
        "backHome":"← Fxverter — কারেন্সি কনভার্টার",
        "allCurrencies":"সব মুদ্রা",
        "allGuides":"সব গাইড",
        "convert":"রূপান্তর",
        "rateHead":"প্রধান মুদ্রায়",
        "chartHead":"1 {code} → USD · 30 দিন",
        "loading":"রেট আনা হচ্ছে…",
        "ratesLoaded":"রেফারেন্স রেট লোড হয়েছে",
        "ratesFail":"রেট সাময়িকভাবে অনুপলব্ধ।",
        "calcPlaceholder":"পরিমাণ (",
        "errBox":"রেট লোড হচ্ছে বা অনুপলব্ধ — মূল কনভার্টার খুলুন।",
        "disclaimer":"রেট নির্দেশক, প্রতিদিন হালনাগাদ — লেনদেনের আগে ব্যাংকের সাথে যাচাই করুন। © 2026 Fxverter · কারেন্সি কনভার্টার",
        "supportIntro":"Fxverter বিনামূল্যে, বিজ্ঞাপন ও ট্র্যাকিং ছাড়া। একটি ছোট অবদান এটিকে দ্রুত ও স্বাধীন রাখে। পেমেন্ট Creem প্রক্রিয়া করে।",
        "supportComing":"সাপোর্ট স্তর শীঘ্রই আসছে। ♥",
        "supportFirst":"প্রথম সমর্থক হোন — আপনার সম্মতিতে আপনার নাম এখানে দেখা যাবে।",
        "supportThanks":"ধন্যবাদ! 🙏",
        "supportChoose":"স্তর বেছে নিন",
        "supportPrivacyNote":"সমর্থকদের নাম শুধু সম্মতিতে তালিকাভুক্ত। © 2026 Fxverter",
        "guidesIntro":"বিনিময় হার নিয়ে সহজ ব্যাখ্যা, Fxverter টিম থেকে।",
        "guidesEmpty":"গাইড শীঘ্রই আসছে।",
        "curLangIntro":"Fxverter 141টি মুদ্রার লাইভ রেফারেন্স রেট দেখায়। প্রতিটি মুদ্রার নিজস্ব পৃষ্ঠা রয়েছে:",
 },
 "pl": {
        "backHome":"← Fxverter — Przelicznik",
        "allCurrencies":"Wszystkie waluty",
        "allGuides":"Wszystkie poradniki",
        "convert":"Przelicz",
        "rateHead":"w głównych walutach",
        "chartHead":"1 {code} → USD · 30 dni",
        "loading":"Pobieranie kursów…",
        "ratesLoaded":"Kursy referencyjne wczytane",
        "ratesFail":"Kursy chwilowo niedostępne.",
        "calcPlaceholder":"Kwota w",
        "errBox":"Kursy się ładują lub są niedostępne — otwórz główny przelicznik.",
        "disclaimer":"Kursy orientacyjne, aktualizowane codziennie — potwierdź w banku przed transakcją. © 2026 Fxverter · Przelicznik",
        "supportIntro":"Fxverter jest darmowy, bez reklam i śledzenia. Mały wkład pomaga utrzymać go szybkim i niezależnym. Płatności obsługuje Creem.",
        "supportComing":"Poziomy wsparcia wkrótce. ♥",
        "supportFirst":"Bądź pierwszym wspierającym — Twoje imię pojawi się tutaj za Twoją zgodą.",
        "supportThanks":"Dziękujemy! 🙏",
        "supportChoose":"Wybierz poziom",
        "supportPrivacyNote":"Wspierający są wymieniani tylko za zgodą. © 2026 Fxverter",
        "guidesIntro":"Proste wyjaśnienia kursów walut od zespołu Fxverter.",
        "guidesEmpty":"Poradniki wkrótce.",
        "curLangIntro":"Fxverter pokazuje kursy referencyjne 141 walut. Każda waluta ma własną stronę:",
 },
 "nl": {
        "backHome":"← Fxverter — Omrekenner",
        "allCurrencies":"Alle valuta's",
        "allGuides":"Alle gidsen",
        "convert":"Omrekenen",
        "rateHead":"in belangrijke valuta's",
        "chartHead":"1 {code} → USD · 30 dagen",
        "loading":"Koersen ophalen…",
        "ratesLoaded":"Referentiekoersen geladen",
        "ratesFail":"Koersen tijdelijk niet beschikbaar.",
        "calcPlaceholder":"Bedrag in",
        "errBox":"Koersen worden geladen of zijn niet beschikbaar — open de hoofdomrekenner.",
        "disclaimer":"Koersen zijn indicatief, dagelijks bijgewerkt — controleer bij uw bank. © 2026 Fxverter · Omrekenner",
        "supportIntro":"Fxverter is gratis, zonder advertenties of tracking. Een kleine bijdrage houdt het snel en onafhankelijk. Betalingen worden verwerkt door Creem.",
        "supportComing":"Ondersteuningsniveaus volgen binnenkort. ♥",
        "supportFirst":"Word de eerste supporter — uw naam verschijnt hier met uw toestemming.",
        "supportThanks":"Bedankt! 🙏",
        "supportChoose":"Kies een niveau",
        "supportPrivacyNote":"Supporters worden alleen met toestemming vermeld. © 2026 Fxverter",
        "guidesIntro":"Begrijpelijke uitleg over wisselkoersen, van het Fxverter-team.",
        "guidesEmpty":"Gidsen volgen binnenkort.",
        "curLangIntro":"Fxverter toont referentiekoersen van 141 valuta. Elke valuta heeft een eigen pagina:",
 },
 "it": {
        "backHome":"← Fxverter — Convertitore",
        "allCurrencies":"Tutte le valute",
        "allGuides":"Tutte le guide",
        "convert":"Converti",
        "rateHead":"nelle valute principali",
        "chartHead":"1 {code} → USD · 30 giorni",
        "loading":"Recupero dei tassi…",
        "ratesLoaded":"Tassi di riferimento caricati",
        "ratesFail":"Tassi temporaneamente non disponibili.",
        "calcPlaceholder":"Importo in",
        "errBox":"I tassi si stanno caricando o non sono disponibili — apri il convertitore principale.",
        "disclaimer":"Tassi indicativi, aggiornati quotidianamente — verifica con la tua banca. © 2026 Fxverter · Convertitore",
        "supportIntro":"Fxverter è gratuito, senza pubblicità né tracciamento. Un piccolo contributo lo mantiene rapido e indipendente. I pagamenti sono processati da Creem.",
        "supportComing":"Livelli di supporto in arrivo. ♥",
        "supportFirst":"Sii il primo sostenitore — il tuo nome apparirà qui con il tuo consenso.",
        "supportThanks":"Grazie! 🙏",
        "supportChoose":"Scegli un livello",
        "supportPrivacyNote":"I sostenitori sono elencati solo con il loro consenso. © 2026 Fxverter",
        "guidesIntro":"Spiegazioni semplici sui tassi di cambio, dal team Fxverter.",
        "guidesEmpty":"Guide in arrivo.",
        "curLangIntro":"Fxverter mostra tassi di riferimento per 141 valute. Ogni valuta ha una pagina dedicata:",
 },
 "ro": {
        "backHome":"← Fxverter — Convertor",
        "allCurrencies":"Toate valutele",
        "allGuides":"Toate ghidurile",
        "convert":"Convertește",
        "rateHead":"în valutele principale",
        "chartHead":"1 {code} → USD · 30 zile",
        "loading":"Se preiau cursurile…",
        "ratesLoaded":"Cursuri de referință încărcate",
        "ratesFail":"Cursuri temporar indisponibile.",
        "calcPlaceholder":"Suma în",
        "errBox":"Cursurile se încarcă sau nu sunt disponibile — deschide convertorul principal.",
        "disclaimer":"Cursuri orientative, actualizate zilnic — verifică cu banca ta. © 2026 Fxverter · Convertor",
        "supportIntro":"Fxverter este gratuit, fără reclame și fără urmărire. O contribuție mică îl menține rapid și independent. Plățile sunt procesate de Creem.",
        "supportComing":"Niveluri de sprijin în curând. ♥",
        "supportFirst":"Fii primul susținător — numele tău va apărea aici cu acordul tău.",
        "supportThanks":"Mulțumim! 🙏",
        "supportChoose":"Alege un nivel",
        "supportPrivacyNote":"Susținătorii sunt enumerați doar cu acordul lor. © 2026 Fxverter",
        "guidesIntro":"Explicații simple despre cursurile valutare, de la echipa Fxverter.",
        "guidesEmpty":"Ghiduri în curând.",
        "curLangIntro":"Fxverter afișează cursuri de referință pentru 141 valute. Fiecare valută are propria pagină:",
 },
 "cs": {
        "backHome":"← Fxverter — Převodník",
        "allCurrencies":"Všechny měny",
        "allGuides":"Všechny průvodce",
        "convert":"Převést",
        "rateHead":"v hlavních měnách",
        "chartHead":"1 {code} → USD · 30 dní",
        "loading":"Načítání kurzů…",
        "ratesLoaded":"Referenční kurzy načteny",
        "ratesFail":"Kurzy jsou dočasně nedostupné.",
        "calcPlaceholder":"Částka v",
        "errBox":"Kurzy se načítají nebo nejsou k dispozici — otevřete hlavní převodník.",
        "disclaimer":"Kurzy jsou orientační, denně aktualizované — před transakcí ověřte u banky. © 2026 Fxverter · Převodník",
        "supportIntro":"Fxverter je zdarma, bez reklam a sledování. Malý příspěvek jej udržuje rychlý a nezávislý. Platby zpracovává Creem.",
        "supportComing":"Úrovně podpory brzy. ♥",
        "supportFirst":"Buďte první podporovatel — se souhlasem se vaše jméno objeví zde.",
        "supportThanks":"Děkujeme! 🙏",
        "supportChoose":"Vyberte úroveň",
        "supportPrivacyNote":"Podporovatelé jsou uvedeni jen se souhlasem. © 2026 Fxverter",
        "guidesIntro":"Srozumitelná vysvětlení kurzů od týmu Fxverter.",
        "guidesEmpty":"Průvodci brzy.",
        "curLangIntro":"Fxverter zobrazuje referenční kurzy 141 měn. Každá měna má vlastní stránku:",
 },
 "da": {
        "backHome":"← Fxverter — Valutaomregner",
        "allCurrencies":"Alle valutaer",
        "allGuides":"Alle guider",
        "convert":"Omregn",
        "rateHead":"i vigtige valutaer",
        "chartHead":"1 {code} → USD · 30 dage",
        "loading":"Henter valutakurser…",
        "ratesLoaded":"Referenzkurser indlæst",
        "ratesFail":"Kurser midlertidigt utilgængelige.",
        "calcPlaceholder":"Beløb i",
        "errBox":"Kurserne indlæses eller er utilgængelige — åbn hovedomregneren.",
        "disclaimer":"Kurser er vejledende, opdateres dagligt — bekræft med din bank. © 2026 Fxverter · Valutaomregner",
        "supportIntro":"Fxverter er gratis, uden annoncer og sporing. Et lille bidrag holder det hurtigt og uafhængigt. Betalinger behandles af Creem.",
        "supportComing":"Understøttelsesniveauer kommer snart. ♥",
        "supportFirst":"Bliv den første støtte — dit navn vises her med din tilladelse.",
        "supportThanks":"Tak! 🙏",
        "supportChoose":"Vælg et niveau",
        "supportPrivacyNote":"Støtter nævnes kun med deres samtykke. © 2026 Fxverter",
        "guidesIntro":"Klare forklaringer på valutakurser fra Fxverter-teamet.",
        "guidesEmpty":"Guider kommer snart.",
        "curLangIntro":"Fxverter viser referenzkurser for 141 valutaer. Hver valuta har sin egen side:",
 },
 "sv": {
        "backHome":"← Fxverter — Valutaomvandlare",
        "allCurrencies":"Alla valutor",
        "allGuides":"Alla guider",
        "convert":"Konvertera",
        "rateHead":"i större valutor",
        "chartHead":"1 {code} → USD · 30 dagar",
        "loading":"Hämtar kurser…",
        "ratesLoaded":"Referenskurser inlästa",
        "ratesFail":"Kurser tillfälligt otillgängliga.",
        "calcPlaceholder":"Belopp i",
        "errBox":"Kurserna läses in eller är otillgängliga — öppna huvudomvandlaren.",
        "disclaimer":"Kurser är vägledande, uppdateras dagligen — bekräfta med din bank. © 2026 Fxverter · Valutaomvandlare",
        "supportIntro":"Fxverter är gratis, utan annonser och spårning. Ett litet bidrag håller det snabbt och oberoende. Betalningar hanteras av Creem.",
        "supportComing":"Stödnivåer kommer snart. ♥",
        "supportFirst":"Bli den första supportern — ditt namn visas här med ditt medgivande.",
        "supportThanks":"Tack! 🙏",
        "supportChoose":"Välj en nivå",
        "supportPrivacyNote":"Supportrar listas endast med sitt medgivande. © 2026 Fxverter",
        "guidesIntro":"Klara förklaringar om växelkurser från Fxverter-teamet.",
        "guidesEmpty":"Guider kommer snart.",
        "curLangIntro":"Fxverter visar referenskurser för 141 valutor. Varje valuta har en egen sida:",
 },
 "lo": {
        "backHome":"← Fxverter — ຕົວແປງສະກຸນເງິນ",
        "allCurrencies":"ສະກຸນເງິນທັງໝົດ",
        "allGuides":"ຄູ່ມືທັງໝົດ",
        "convert":"ແປງ",
        "rateHead":"ໃນສະກຸນເງິນຫຼັກ",
        "chartHead":"1 {code} → USD · 30 ວັນ",
        "loading":"ກຳລັງດຶງອັດຕາ…",
        "ratesLoaded":"ໂຫລດອັດຕາອ້າງອີງແລ້ວ",
        "ratesFail":"ອັດຕາໃຊ້ບໍ່ໄດ້ຊົ່ວຄາວ.",
        "calcPlaceholder":"ຈຳນວນ (",
        "errBox":"ອັດຕາກຳລັງໂຫລດ ຫຼື ໃຊ້ບໍ່ໄດ້ — ກະລຸນາເປີດຕົວແປງຫຼັກ.",
        "disclaimer":"ອັດຕາເປັນຂໍ້ມູນອ້າງອີງ, ອັບເດດປະຈຳວັນ — ຢືນຢັນກັບທະນາຄານກ່ອນທຸລະກຳ. © 2026 Fxverter · ຕົວແປງສະກຸນເງິນ",
        "supportIntro":"Fxverter ຟຣີ ບໍ່ມີໂຄສະນາ ແລະ ການຕິດຕາມ. ການສະໜັບສະໜູນເລັກນ້ອຍຊ່ວຍໃຫ້ມັນໄວ ແລະ ເປັນເອກະລາດ. ການຊຳລະເງິນດຳເນີນການໂດຍ Creem.",
        "supportComing":"ລະດັບການສະໜັບສະໜູນມາໃໝ່ໃນເວລາອັນໃກ້ນີ້. ♥",
        "supportFirst":"ເປັນຜູ້ສະໜັບສະໜູນຄົນທຳອິດ — ຊື່ຂອງເຈົ້າຈະປາກົດຢູ່ນີ້ເມື່ອເຈົ້າຍິນຍອມ.",
        "supportThanks":"ຂອບໃຈ! 🙏",
        "supportChoose":"ເລືອກລະດັບ",
        "supportPrivacyNote":"ລິສຕາຊື່ຜູ້ສະໜັບສະໜູນພຽງແຕ່ເມື່ອໄດ້ຮັບຄວາມຍິນຍອມ. © 2026 Fxverter",
        "guidesIntro":"ຄຳອະທິບາຍງ່າຍໆກ່ຽວກັບອັດຕາແລກປ່ຽນ ຈາກທີມ Fxverter.",
        "guidesEmpty":"ຄູ່ມືມາໃໝ່ໃນເວລາອັນໃກ້ນີ້.",
        "curLangIntro":"Fxverter ສະແດງອັດຕາອ້າງອີງຂອງ 141 ສະກຸນເງິນ. ແຕ່ລະສະກຸນເງິນມີໜ້າຂອງຕົນເອງ:",
 },
 "tl": {
        "backHome":"← Fxverter — Tagapagpalit",
        "allCurrencies":"Lahat ng pera",
        "allGuides":"Lahat ng gabay",
        "convert":"I-convert",
        "rateHead":"sa mga pangunahing pera",
        "chartHead":"1 {code} → USD · 30 araw",
        "loading":"Kinukuha ang mga rate…",
        "ratesLoaded":"Na-load ang reference rates",
        "ratesFail":"Pansamantalang hindi available ang mga rate.",
        "calcPlaceholder":"Halaga sa",
        "errBox":"Naglo-load o hindi available ang mga rate — buksan ang pangunahing converter.",
        "disclaimer":"Ang mga rate ay sanggunian, ina-update araw-araw — kumpirmahin sa bangko bago mag-transact. © 2026 Fxverter · Tagapagpalit",
        "supportIntro":"Libre ang Fxverter, walang ads at tracking. Ang maliit na suporta ay nakakatulong itong manatiling mabilis at independyente. Pinoproseso ng Creem ang mga bayad.",
        "supportComing":"Paparating na ang support levels. ♥",
        "supportFirst":"Maging unang supporter — lalabas ang pangalan mo rito kung papayag ka.",
        "supportThanks":"Salamat! 🙏",
        "supportChoose":"Pumili ng antas",
        "supportPrivacyNote":"Nakalista ang supporters kung pumayag sila. © 2026 Fxverter",
        "guidesIntro":"Malinaw na paliwanag tungkol sa exchange rates, mula sa Fxverter team.",
        "guidesEmpty":"Paparating na ang mga gabay.",
        "curLangIntro":"Nagpapakita ang Fxverter ng reference rates para sa 141 pera. May sariling page ang bawat pera:",
 },
}
