GUIDE_L10N = {
    "exchange-rate-risk": {
        "title": "Risque de change — Guide pour les indépendants et les petites entreprises",
        "description": "Si vous facturez ou payez dans une devise étrangère, votre activité est déjà exposée au risque de change. Voici comment l’identifier, le mesurer et le réduire sans devenir cambiste.",
        "sections": [
            ("p", "Si un client vous paie dans une devise que vous ne dépensez pas, ou si votre fournisseur vous facture dans une devise que vous ne gagnez pas, vous êtes exposé au **risque de change**, que vous y ayez pensé ou non. Une variation de 5 % en votre défaveur peut effacer toute la marge d’un projet. La bonne nouvelle : nul besoin de devenir cambiste pour maîtriser ce risque — quelques bonnes habitudes suffisent."),
            ("h", "D’abord, repérez où se situe le risque"),
            ("p", "Tracez deux colonnes : ce que vous **gagnez** et ce que vous **dépensez**, chacune dans sa devise."),
            ("li", "Un indépendant qui facture des clients américains mais vit avec des euros gagne des dollars et dépense des euros : chaque facture reste exposée au taux jusqu’à son paiement et sa conversion."),
            ("li", "Un importateur qui achète en Asie et vend dans son pays fait l’inverse : le coût lui parvient d’abord dans une devise étrangère."),
            ("li", "Une entreprise SaaS qui facture partout dans le monde a une exposition mixte, qui ne s’équilibre que si les devises sont réellement diversifiées."),
            ("p", "L’écart entre ces deux colonnes — ce que vous devez convertir, dans quel sens et à quel moment — constitue votre exposition. Si elle est faible et occasionnelle, ce guide se lit en dix minutes. Si elle est importante et récurrente, les habitudes ci-dessous seront vite rentabilisées."),
            ("h", "Habitude 1 : facturez dans votre propre devise lorsque c’est possible"),
            ("p", "La façon la plus simple de réduire le risque consiste à en faire le problème du **client** : fixez le prix dans votre devise et indiquez clairement que le montant est établi dans celle-ci. Beaucoup de clients l’acceptent sans broncher ; certains résistent, et une remise peut coûter moins cher qu’une année de fluctuations. Les grands clients préfèrent souvent leur propre devise : c’est là que les autres habitudes deviennent utiles."),
            ("h", "Habitude 2 : convertissez rapidement, selon une règle"),
            ("p", "Si vous recevez une devise étrangère et la gardez « en attendant un taux favorable », vous spéculez avec des revenus dont vous pourriez avoir besoin. Une règle simple — convertir dans un nombre de jours défini après réception, ou lorsque le taux atteint un niveau acceptable pour vous — transforme la chance en méthode. La plupart des applications bancaires et de transfert proposent justement des alertes de taux."),
            ("h", "Habitude 3 : utilisez un solde multidevise"),
            ("p", "Les comptes professionnels modernes vous permettent de **conserver** des devises étrangères au lieu de les convertir automatiquement. Si vous payez certains fournisseurs ou prestataires dans la même devise que celle de vos factures, faire correspondre les deux réduit naturellement une partie du risque : pas de conversion, pas de frais, pas de décision à prendre."),
            ("h", "Habitude 4 : fractionnez les conversions importantes"),
            ("p", "Pour un paiement important ponctuel — équipement, acompte, impôt — fractionner la conversion en deux ou trois opérations sur plusieurs jours permet de lisser le taux et évite de tout convertir le pire jour du mois. Pour des paiements futurs vraiment importants et prévisibles, les banques proposent des **contrats à terme** qui bloquent le taux d’aujourd’hui pour une date située plusieurs mois plus tard ; en contrepartie, vous renoncez à profiter d’une évolution favorable."),
            ("h", "Habitude 5 : prévoyez une marge dans vos prix"),
            ("p", "Si vous devez établir un devis dans la devise du client, ajoutez une marge pour couvrir une variation du taux entre le devis et le paiement — et précisez que le prix n’est valable que pendant une période limitée. Les indépendants qui indiquent « valable 30 jours » transforment discrètement un risque connu en risque encadré."),
            ("h", "Ce qu’il ne faut pas faire"),
            ("li", "Ne faites pas de spéculation sur les devises « à côté » avec l’argent dont votre activité a besoin : ce n’est plus de la couverture."),
            ("li", "Ne négligez pas le **coût** de conversion en gérant le taux : un écart de 3 % coûte plus cher que la plupart des gains obtenus en choisissant le bon moment."),
            ("li", "Ne laissez pas le risque sans mesure : notez ce que vous gagnez et dépensez chaque année dans chaque devise, puis examinez l’écart."),
            ("p", "Gérés ainsi, les taux de change cessent d’être un billet de loterie attaché à vos revenus et deviennent ce qu’ils devraient être : un poste que vous comprenez et dont vous maîtrisez le coût."),
        ],
    },
    "hidden-currency-fees": {
        "title": "Les frais cachés de conversion de devises (et comment les éviter)",
        "description": "Les frais affichés ne représentent presque jamais le coût total. Écarts de taux, conversion dynamique, frais de retrait et frais d’intermédiaires prélèvent tous leur part : voici comment les repérer et préserver la différence.",
        "sections": [
            ("p", "Les frais affichés à l’écran sont rarement ceux que vous payez réellement. Les coûts de conversion de devises se cachent sous quatre formes, et le plus important n’apparaît jamais comme des frais."),
            ("h", "1. La marge sur le taux de change"),
            ("p", "Lorsqu’un prestataire vous propose un taux inférieur de 2 % au taux moyen du marché, ces 2 % sont des frais — même si cela n’en a pas l’air. Pour un transfert de 5 000 unités, une marge de 2 % coûte 100 unités, tandis que la bannière « sans frais » récolte les applaudissements. C’est le coût le plus élevé dans la plupart des conversions ; le seul moyen de le voir est de comparer le taux proposé au **taux de référence moyen du marché** avant de confirmer."),
            ("h", "2. La conversion dynamique de devises (DCC)"),
            ("p", "Le bouton le plus coûteux en voyage : lorsqu’un terminal de paiement ou un distributeur à l’étranger vous propose de vous facturer **dans votre devise habituelle**, il vous propose de convertir au taux qu’il a lui-même fixé — généralement 3 à 10 % moins avantageux que celui de votre banque. Choisissez toujours de payer dans la **devise locale** et laissez votre banque effectuer la conversion."),
            ("h", "3. Les frais de distributeur et de carte"),
            ("li", "Les exploitants de distributeurs à l’étranger ajoutent souvent des **frais fixes** à chaque retrait."),
            ("li", "Votre propre banque peut aussi appliquer une **commission sur les paiements à l’étranger** (souvent de 1 à 3 %)."),
            ("li", "Retirez des montants plus importants moins souvent pour répartir les frais fixes, et privilégiez les **distributeurs affiliés à une banque** plutôt que les appareils indépendants installés dans les commerces."),
            ("h", "4. Les frais de virement et d’intermédiaires"),
            ("p", "Les virements bancaires internationaux peuvent passer par une ou deux **banques intermédiaires**, qui prélèvent chacune leurs frais avant que l’argent n’arrive : le bénéficiaire reçoit donc nettement moins que le montant envoyé, sans détail expliquant où la différence est passée. Les services de transfert spécialisés affichent leurs frais à l’avance, ce qui explique précisément pourquoi ils sont généralement moins chers."),
            ("h", "La comparaison qui ne trompe jamais"),
            ("p", "Ne tenez compte ni des frais annoncés ni des taux mis en avant. Pour chaque prestataire, une seule question permet de tout trancher :"),
            ("p", "**Si j’envoie X aujourd’hui, quel montant exact sera reçu, dans la devise du bénéficiaire et après déduction de tout ?**"),
            ("p", "Recueillez ce montant auprès de deux ou trois prestataires le même jour et choisissez le plus élevé. Les taux évoluent chaque jour : refaites la comparaison lors de votre prochain envoi, car le prestataire le moins cher l’an dernier ne l’est pas forcément aujourd’hui."),
            ("h", "Petite liste de vérification"),
            ("li", "Comparez d’abord le taux proposé au taux moyen du marché."),
            ("li", "À l’étranger, payez toujours en devise locale et refusez les offres de conversion."),
            ("li", "Regroupez les retraits aux distributeurs pour diluer les frais fixes."),
            ("li", "Préférez les prestataires qui indiquent à l’avance le « montant total reçu »."),
            ("li", "Refaites la vérification avant chaque transfert, pas une seule fois par an."),
            ("p", "Aucune de ces étapes ne prend plus de quelques minutes et, ensemble, elles permettent régulièrement d’économiser 2 à 5 % par conversion — ce qui représente une somme bien réelle sur une année de transferts."),
        ],
    },
    "how-exchange-rates-work": {
        "title": "Comment les taux de change sont déterminés",
        "description": "Qui décide de la valeur d’une devise ? Une explication en langage simple des régimes de change fixe, flottant et administré.",
        "sections": [
            ("p", "Un taux de change répond à une question : quelle quantité d’une devise faut-il pour en acheter une autre ? Mais qui fixe ce chiffre ? La réponse dépend de la devise : il existe trois grands systèmes."),
            ("h", "Les taux flottants"),
            ("p", "La plupart des grandes devises — le dollar américain, l’euro, le yen japonais et la livre sterling — **flottent librement**. Leur valeur est déterminée en continu par l’offre et la demande sur le marché mondial des changes, le plus grand marché financier du monde, dont le volume quotidien dépasse 7 000 milliards de dollars américains."),
            ("h", "Les taux fixes (ancrés)"),
            ("p", "Certaines devises sont **ancrées** à une autre. Le riyal saoudien et le dirham des Émirats arabes unis sont fixés par rapport au dollar américain ; la couronne danoise est ancrée à l’euro. La banque centrale s’engage à acheter ou à vendre sa devise afin de maintenir le taux dans une bande étroite."),
            ("h", "Les taux administrés"),
            ("p", "De nombreuses devises, comme le yuan chinois, sont **administrées** : la banque centrale autorise les fluctuations du marché, mais intervient lorsque le taux sort d’une fourchette jugée acceptable."),
            ("h", "D’où viennent les taux de Fxverter"),
            ("p", "Fxverter affiche des **taux de référence** : des taux de fin de journée publiés par la Banque centrale européenne et d’autres sources publiques. Ils sont très utiles pour comparer, planifier et estimer — mais les banques et les réseaux de cartes ajoutent leurs propres marges et frais : le taux réellement appliqué à un transfert sera donc différent. Confirmez toujours le taux final auprès de votre banque ou de votre prestataire."),
        ],
    },
    "inflation-and-exchange-rates": {
        "title": "Inflation et taux de change — quel est le lien ?",
        "description": "Une inflation élevée érode une devise au fil des années, et les banques centrales la combattent avec les taux d’intérêt. Comprendre ces deux forces permet d’expliquer la plupart des évolutions monétaires à long terme.",
        "sections": [
            ("p", "Demandez pourquoi une devise s’est affaiblie en dix ans : la réponse commence généralement par l’inflation. Demandez pourquoi elle s’est renforcée ce mois-ci : la réponse commence généralement par les taux d’intérêt. Ces deux forces sont liées — voici comment fonctionne le mécanisme."),
            ("h", "L’inflation érode lentement une devise"),
            ("p", "Au fond, une devise représente un droit sur les biens et les services d’une économie. Si les prix doublent alors que la quantité de monnaie reste la même, chaque unité de cette monnaie permet d’acheter deux fois moins — et les investisseurs étrangers paieront proportionnellement moins pour l’obtenir. Au fil des années, un pays dont l’inflation est **durablement supérieure à celle de ses partenaires commerciaux** voit généralement sa devise se déprécier par rapport aux leurs."),
            ("p", "Les exemples les plus parlants sont les devises qui ont perdu la plus grande partie de leur valeur en une génération : la livre turque, le peso argentin et le bolivar vénézuélien. Dans chaque cas, des années de création monétaire et d’inflation à deux chiffres ont conduit au résultat prédit par la logique du pouvoir d’achat."),
            ("h", "La parité de pouvoir d’achat : l’ancrage à long terme"),
            ("p", "Cette idée s’appelle la **parité de pouvoir d’achat (PPA)** : à long terme, les taux de change s’ajustent de sorte qu’un même panier de biens coûte à peu près la même chose partout. Si un panier coûte 100 unités chez vous et deux fois plus à l’étranger après conversion, le taux de change est déséquilibré — et, avec le temps, le taux ou les prix évoluent pour réduire l’écart."),
            ("p", "La PPA ne sert à rien pour prévoir la semaine prochaine. Elle est étonnamment utile pour déterminer si une devise est **manifestement surévaluée ou sous-évaluée** après une forte évolution — d’où la publication régulière de comparaisons comme l’indice Big Mac."),
            ("h", "Les taux d’intérêt : le levier à court terme"),
            ("p", "Les banques centrales combattent l’inflation en relevant les taux d’intérêt. Des taux plus élevés rendent les dépôts et les obligations libellés dans cette devise plus attrayants, attirent des capitaux étrangers et soutiennent le taux de change — du moins tant que les investisseurs pensent que la banque centrale maintiendra le cap."),
            ("p", "C’est pourquoi le même schéma se répète dans le monde entier : une banque centrale **relève fortement ses taux**, la devise se renforce ; elle **baisse ses taux ou perd sa crédibilité**, la devise s’affaiblit. La livre turque a chuté lorsque les taux ont été abaissés malgré la hausse de l’inflation, puis s’est redressée quand la politique est redevenue orthodoxe. Le réal brésilien tire sa vigueur de taux d’intérêt réels parmi les plus élevés au monde."),
            ("h", "Ce sont les taux réels qui comptent"),
            ("p", "Ce qui fait bouger les capitaux, ce n’est pas le taux nominal, mais le **taux réel** : le taux directeur moins l’inflation. Un taux directeur de 40 % avec une inflation de 50 % reste profondément négatif : l’argent qui y est placé perd chaque année de son pouvoir d’achat, ce qui explique précisément pourquoi les habitants préfèrent les dollars. À l’inverse, un taux de 5 % avec une inflation de 2 % est réellement attrayant."),
            ("h", "Ce que cela signifie pour vous"),
            ("li", "**Voyageurs :** les destinations à forte inflation deviennent moins chères au fil du temps lorsqu’on les mesure en devises fortes — mais vérifiez les taux actuels, car le marché a généralement déjà intégré une partie de cette évolution."),
            ("li", "**Épargnants :** conserver son épargne dans une devise fortement inflationniste assortie de taux réels négatifs entraîne une perte lente, même si le compte « rapporte des intérêts »."),
            ("li", "**Entreprises :** libellez les contrats de longue durée en devise forte ou indexez-les sur l’inflation lorsque la devise de votre partenaire manque de crédibilité."),
            ("p", "L’inflation est la marée lente qui décide où finissent les devises. Les taux d’intérêt sont les vagues qui décident de leur direction ce mois-ci."),
        ],
    },
    "mid-market-rate": {
        "title": "Qu’est-ce que le taux moyen du marché ?",
        "description": "Le taux moyen du marché est le point médian entre le prix payé par les acheteurs et celui accepté par les vendeurs — c’est aussi la référence à laquelle comparer les transferts d’argent.",
        "sections": [
            ("p", "Lorsque vous envoyez de l’argent à l’étranger ou achetez des devises, les prestataires vous proposent un taux majoré. Pour savoir si l’offre est équitable, vous avez besoin d’un chiffre : le **taux moyen du marché**."),
            ("h", "Définition"),
            ("p", "Le taux moyen du marché est le point médian entre le **cours acheteur** (ce que les acheteurs sont actuellement prêts à payer) et le **cours vendeur** (ce que les vendeurs acceptent) sur le marché mondial des devises. C’est l’instantané le plus équitable de la valeur d’une devise — le même taux que celui affiché sur Fxverter, Google et les sites d’actualités financières."),
            ("h", "Pourquoi le taux de votre banque est moins avantageux"),
            ("p", "Les banques et les services de transfert dissimulent généralement une marge **dans** le taux de change — souvent de 1 à 4 %, parfois bien davantage — à laquelle s’ajoutent des frais. Une marge de 3 % sur un transfert de 10 000 unités vous coûte discrètement 300 unités, généralement plus que les « frais » explicitement annoncés."),
            ("h", "Comment l’utiliser"),
            ("li", "Comparez le taux proposé au taux Fxverter pour la même paire de devises."),
            ("li", "Demandez au prestataire le **coût total dans la devise reçue**, frais et marges compris."),
            ("li", "De faibles écarts sont normaux — les prestataires doivent dégager une marge —, mais un écart de plusieurs pour cent justifie de comparer d’autres offres."),
            ("h", "Limites à connaître"),
            ("p", "Les taux moyens du marché sont des taux de référence, généralement actualisés une ou quelques fois par jour, et non des cours de négociation en temps réel. Le taux exact de tout transfert réel sera légèrement différent : le taux moyen du marché est une référence, pas une garantie contractuelle."),
        ],
    },
    "reading-exchange-rate-quotes": {
        "title": "Comment lire les cotations de change",
        "description": "Devise de base, devise de cotation, pips et écarts : un guide de cinq minutes pour comprendre ce qu’indique réellement une cotation de change.",
        "sections": [
            ("p", "Une cotation de change semble simple — **EUR/USD 1,08** — mais ce chiffre contient plusieurs informations. Voici comment le lire et repérer quand un taux proposé dissimule un coût."),
            ("h", "Quelle devise est laquelle ?"),
            ("p", "Dans toute paire, la **devise de base** apparaît en premier et la **devise de cotation** en second. Le chiffre indique la quantité de devise de cotation achetée par une unité de devise de base :"),
            ("li", "**EUR/USD 1,08** → 1 euro achète 1,08 dollar américain."),
            ("li", "**USD/JPY 150,00** → 1 dollar américain achète 150 yens japonais."),
            ("p", "L’ordre est une convention de marché, pas un choix : certaines paires apparaissent toujours dans un sens (EUR/USD, GBP/USD), d’autres dans l’autre (USD/JPY, USD/CAD). Lorsque vous consultez un taux, vérifiez quelle devise est la devise de base — sinon, vous pourriez lire 150 yens comme 150 dollars."),
            ("h", "Le grand chiffre et les pips"),
            ("p", "Dans EUR/USD 1,0850, le **grand chiffre** est 1,08 et les deux derniers chiffres — les pips — sont 50. La plupart des paires sont cotées avec quatre ou cinq décimales, et les paires impliquant le yen avec deux ou trois. Les variations quotidiennes des principales paires ne sont souvent que de quelques dizaines de pips, d’où le caractère exceptionnel d’une variation de 1 % en une journée."),
            ("h", "Pourquoi vous voyez un taux quand le marché en voit deux"),
            ("p", "Les marchés professionnels affichent **deux prix** : le cours acheteur (ce que les acheteurs paient) et le cours vendeur (ce que les vendeurs acceptent). L’écart entre les deux est l’**écart acheteur-vendeur**, c’est-à-dire le coût de transaction inhérent au marché. Pour EUR/USD, il peut représenter une fraction de pip ; pour une paire exotique, il peut être des centaines de fois plus large."),
            ("p", "Lorsque vous changez de l’argent en tant que particulier, vous ne voyez généralement qu’**un seul taux**. Il s’agit du taux moyen du marché, auquel s’ajoute la marge du prestataire. Plus l’écart entre le taux moyen du marché et le taux proposé est grand, plus la conversion coûte réellement cher — quelle que soit la somme indiquée dans la colonne des frais."),
            ("h", "Les taux croisés : pourquoi le dollar est partout"),
            ("p", "La plupart des paires de devises ne sont pas négociées directement. Si vous voulez convertir des couronnes danoises en réaux brésiliens, le marché établit le cours par deux étapes liées : DKK→USD puis USD→BRL. C’est pourquoi les taux de référence exprimés en dollars sont utiles pour toutes les devises et pourquoi certaines paires inhabituelles ont des écarts acheteur-vendeur plus larges : vous payez deux conversions même si vous n’en voyez qu’une."),
            ("h", "Une méthode pratique pour lire une cotation"),
            ("li", "1. Trouvez le **taux moyen du marché** de votre paire (Fxverter, Google ou toute autre source de référence)."),
            ("li", "2. Demandez au prestataire le **montant total reçu** pour votre transfert."),
            ("li", "3. Divisez le montant reçu par celui qu’aurait donné le taux moyen du marché : l’écart correspond au coût réel."),
            ("li", "4. Recommencez avec un deuxième prestataire ; c’est l’écart, et non les frais affichés, qui désigne la meilleure offre."),
            ("p", "Une fois que vous savez lire une cotation de cette façon, les arguments marketing du type « sans commission » ne fonctionnent plus : vous ne regardez plus le chiffre qu’on veut vous faire voir."),
        ],
    },
    "send-money-abroad": {
        "title": "Comment envoyer de l’argent à l’étranger sans trop payer",
        "description": "Les banques dissimulent 1 à 4 % dans le taux de change. Voici comment comparer en trois minutes le coût total d’un transfert international et conserver cette marge dans votre poche.",
        "sections": [
            ("p", "Lorsque vous envoyez de l’argent à l’étranger, vous ne payez que rarement les seuls « frais » affichés à l’écran. Le coût réel est caché dans le taux de change — et représente généralement la plus grande partie de la facture."),
            ("h", "Le coût caché : la marge sur le taux"),
            ("p", "Les banques et de nombreux services de transfert vous proposent un taux moins avantageux que le taux moyen du marché (le point médian entre les cours acheteur et vendeur affichés sur Fxverter ou Google). La différence représente généralement une marge de **1 à 4 %**, parfois bien plus sur les corridors exotiques. Pour un transfert de 10 000 unités, une marge de 3 % vous coûte discrètement 300 unités, généralement plus que les frais annoncés."),
            ("h", "Comparez le montant total reçu, pas les frais"),
            ("p", "Le seul chiffre qui compte est **le montant qui arrive**. Pour chaque prestataire, calculez :"),
            ("li", "les frais facturés, plus"),
            ("li", "l’écart entre son taux et le taux moyen du marché."),
            ("p", "Convertissez ces deux éléments dans la devise de destination et vous obtenez le coût réel. Un prestataire « sans frais » qui applique une marge de 4 % coûte bien plus cher qu’un prestataire qui facture 5 $ de frais clairement affichés et applique une marge de 0,3 %."),
            ("h", "Trois minutes de vérifications"),
            ("li", "Vérifiez le **taux moyen du marché** de votre paire juste avant l’envoi : les taux évoluent."),
            ("li", "Demandez au prestataire le **montant total dans la devise du bénéficiaire**, tout compris."),
            ("li", "Comparez au moins deux prestataires le même jour : les marges varient énormément selon le corridor."),
            ("li", "Pour les montants importants, demandez s’il existe un **palier de taux préférentiel** : de nombreux services négocient leurs tarifs au-delà de certains montants."),
            ("li", "Méfiez-vous des **taux promotionnels** qui ne s’appliquent qu’au premier transfert."),
            ("h", "Moment et méthode"),
            ("p", "Pour la plupart des corridors destinés aux particuliers, les services spécialisés dans les transferts sont moins chers que les virements bancaires, pour une rapidité similaire (de quelques minutes à une journée). Évitez de changer des espèces dans les aéroports : leurs marges sont les pires du secteur. Si le transfert n’est pas urgent, surveiller le taux quelques jours et définir une alerte à un niveau favorable peut rapporter davantage qu’une réduction des frais."),
            ("h", "La règle en une phrase"),
            ("p", "**Ignorez les frais, comparez le montant reçu.** Tout le reste relève du marketing."),
        ],
    },
    "travel-money": {
        "title": "Argent en voyage — espèces, carte ou change ?",
        "description": "Combien d’espèces emporter à l’étranger, quelle carte utiliser et pourquoi l’option « payer dans votre devise » est le bouton le plus coûteux de tout terminal de paiement.",
        "sections": [
            ("p", "Chaque voyage commence par la même question : combien d’argent changer avant de partir et quel moyen de paiement utiliser une fois sur place ? La réponse dépend moins de la destination que de trois choix que vous faites au terminal."),
            ("h", "La règle d’or à chaque terminal"),
            ("p", "Lorsqu’un terminal ou un distributeur vous propose de vous facturer **dans votre devise habituelle plutôt que dans la devise locale**, refusez toujours. Cette option s’appelle la conversion dynamique de devises (DCC) et dissimule une majoration de 3 à 10 % derrière un écran qui semble pratique. Choisissez de **toujours payer en devise locale** et laissez votre banque effectuer la conversion : même des taux bancaires médiocres sont presque toujours meilleurs que ceux de la DCC."),
            ("h", "Combien d’espèces emporter ?"),
            ("li", "**Destinations où les espèces sont très utilisées :** le Japon, l’Allemagne, l’Asie du Sud-Est hors grandes villes, ainsi que les marchés et les zones rurales partout dans le monde."),
            ("li", "**Destinations où la carte est privilégiée :** les pays nordiques, le Royaume-Uni, la Chine (paiements mobiles) et la plupart des zones urbaines d’Amérique du Nord."),
            ("li", "Un bon point de départ : emportez l’équivalent de **un à deux jours de dépenses** en espèces locales et réalimentez-vous aux distributeurs plutôt que de changer une grosse somme à l’avance."),
            ("h", "La bonne stratégie au distributeur"),
            ("p", "Les bureaux de change des aéroports ont les marges les plus élevées du secteur : ne les utilisez qu’en cas d’urgence. Les retraits dans les distributeurs affiliés à une banque sur place vous donnent généralement un taux proche du taux moyen du marché. La méthode habituelle consiste à retirer de quoi couvrir quelques jours afin de répartir les frais fixes des distributeurs, puis à refuser leur proposition de conversion (le même piège de la DCC)."),
            ("h", "Les cartes adaptées aux voyages"),
            ("li", "Les cartes **sans frais sur les opérations en devises étrangères** vous font économiser la majoration habituelle de 1 à 3 % sur chaque achat."),
            ("li", "Les **cartes prépayées de voyage** permettent de bloquer un taux : pratique pour établir un budget, mais vous ne profitez pas d’une évolution favorable du taux."),
            ("li", "Les **portefeuilles mobiles** (Apple Pay, Google Pay) reprennent les conditions de votre carte et sont acceptés plus largement que beaucoup de voyageurs ne le pensent."),
            ("h", "Gardez une petite réserve en devise forte"),
            ("p", "Une réserve de **dollars américains ou d’euros** pliée dans vos affaires est une solution de secours universelle : elle peut être changée dans tous les pays du monde et vous dépannera si les cartes ne fonctionnent plus, si les distributeurs sont en panne ou si une monnaie locale traverse une crise. Vous n’en aurez probablement jamais besoin — c’est précisément le rôle d’une réserve."),
            ("h", "La liste de vérification"),
            ("li", "1. Prévenez votre banque ou, mieux encore, utilisez une carte sans frais à l’étranger."),
            ("li", "2. Emportez un peu d’espèces dans votre devise habituelle pour les premières heures, pas tout votre budget."),
            ("li", "3. Retirez de l’argent sur place aux distributeurs des banques et refusez les offres de conversion."),
            ("li", "4. Payez toujours en devise locale."),
            ("li", "5. Gardez une réserve en USD/EUR à part de votre portefeuille."),
            ("p", "En suivant ces cinq conseils, vous obtiendrez un meilleur taux que la plupart des voyageurs, sans avoir à vous préoccuper de votre argent jusqu’au vol du retour."),
        ],
    },
    "when-to-exchange": {
        "title": "Quel est le meilleur moment pour changer des devises ?",
        "description": "Personne ne peut prévoir les taux de change de façon fiable ; mais vous pouvez éviter les pires moments, utiliser des alertes plutôt que de deviner et fractionner les grosses conversions pour lisser votre taux.",
        "sections": [
            ("p", "Commençons par la réponse honnête : **personne ne prévoit les taux de change de façon fiable** — ni les banques, ni les analystes, ni les algorithmes. Les cambistes professionnels, qui disposent de meilleures données que nous, n’ont guère plus de chances d’avoir raison qu’un pile ou face à court terme. L’objectif n’est donc pas de deviner le moment parfait, mais d’éviter les pires moments et de laisser de simples mécanismes faire le reste."),
            ("h", "Ce qui fait vraiment bouger les taux à court terme"),
            ("p", "Les variations quotidiennes sont entraînées par l’actualité : décisions des banques centrales, chiffres de l’inflation, données sur l’emploi et événements politiques. Ces événements sont annoncés à l’avance ou surviennent soudainement, et le marché réagit en quelques secondes. Quand un titre sur la « vigueur du dollar » vous parvient, le mouvement a généralement déjà eu lieu."),
            ("p", "Sur plusieurs semaines ou plusieurs mois, les taux évoluent au gré des écarts de taux d’intérêt et de la dynamique économique. Sur plusieurs années, les devises tendent à revenir vers des niveaux justifiés par leur économie — mais « plusieurs années » n’est pas un horizon de planification adapté à un voyage ou à une facture."),
            ("h", "Utilisez des alertes plutôt que des prévisions"),
            ("p", "La plupart des applications bancaires et de transfert proposent des **alertes de taux** : vous définissez le niveau qui vous semble favorable et recevez une notification lorsque le marché l’atteint. Vous remplacez ainsi les suppositions par une règle. Si le taux n’atteint jamais ce niveau, vous aurez tout de même effectué la conversion — simplement sans avoir eu de chance. S’il l’atteint, vous aurez fait un peu mieux que l’utilisateur moyen du marché, et cet avantage s’accumule au fil d’une année de transferts."),
            ("h", "Fractionnez les conversions importantes"),
            ("p", "Si vous transférez une somme importante — frais de scolarité, acompte immobilier, paiement professionnel — envisagez de **la répartir en plusieurs opérations** sur quelques jours ou quelques semaines. Vous n’obtiendrez ni le meilleur ni le pire taux de la période, mais vous en aurez la **moyenne**, généralement proche d’un taux équitable, et vous éviterez de tout convertir le seul pire jour du mois."),
            ("h", "Les pires moments pour convertir"),
            ("li", "**Les comptoirs de change des aéroports** — leurs marges sont les pires du secteur, quelle que soit l’heure."),
            ("li", "**La pression d’une échéance de dernière minute** — si vous devez convertir aujourd’hui, vous n’avez aucun pouvoir de négociation."),
            ("li", "**Les périodes de vacances** — la demande augmente autour des grandes fêtes du pays de destination."),
            ("li", "**Juste après un gros titre spectaculaire** — la volatilité est maximale lorsque tout le monde réagit, et les écarts acheteur-vendeur s’élargissent."),
            ("h", "Pour les entreprises : arrêtez de choisir le moment, couvrez le risque"),
            ("p", "Les entreprises qui reçoivent régulièrement des factures en devises étrangères ne devraient pas chercher à choisir le bon moment. Les outils habituels sont simples : facturer dans votre propre devise lorsque c’est possible, conserver un solde multidevise pour payer et recevoir directement dans les devises concernées et, pour les paiements importants et prévisibles, demander à votre banque un **contrat à terme**. Celui-ci bloque le taux d’aujourd’hui pour une date future et transforme un coût imprévisible en coût connu."),
            ("h", "À retenir"),
            ("p", "Définissez une alerte, évitez les moments réputés défavorables, fractionnez les grosses sommes et passez à autre chose. Le temps que vous ne passez pas à surveiller les graphiques vaut davantage que la fraction de pour cent que vous pourriez gagner en les regardant."),
        ],
    },
}
