GUIDE_L10N = {
    "exchange-rate-risk": {
        "title": "Wechselkursrisiko – ein Leitfaden für Freiberufler und kleine Unternehmen",
        "description": "Wenn Sie Rechnungen in einer Fremdwährung stellen oder bezahlen, gehört das Wechselkursrisiko bereits zu Ihrem Geschäft. So erkennen, messen und verringern Sie es, ohne zum Devisenhändler zu werden.",
        "sections": [
            ("p", "Wenn ein Kunde Sie in einer Währung bezahlt, in der Sie Ihre Ausgaben nicht tätigen, oder Ihr Lieferant in einer Währung abrechnet, die Sie nicht einnehmen, tragen Sie ein **Wechselkursrisiko** – ob Sie schon darüber nachgedacht haben oder nicht. Eine Bewegung von 5 % zu Ihren Ungunsten kann die Marge eines Projekts vollständig aufzehren. Die gute Nachricht: Sie müssen kein Devisenhändler werden, um das Risiko in den Griff zu bekommen – ein paar gute Gewohnheiten reichen."),
            ("h", "Erst einmal: Finden Sie heraus, wo das Risiko liegt"),
            ("p", "Ziehen Sie zwei Linien: was Sie **einnehmen** und was Sie **ausgeben**, jeweils in der entsprechenden Währung."),
            ("li", "Ein Freiberufler, der US-amerikanische Kunden abrechnet, aber in Europa lebt, nimmt US-Dollar ein und gibt Euro aus – jede Rechnung ist bis zur Zahlung und Umrechnung einem Wechselkursrisiko ausgesetzt."),
            ("li", "Ein Importeur, der in Asien einkauft und im Inland verkauft, hat die umgekehrte Situation: Die Kosten fallen zuerst in einer Fremdwährung an."),
            ("li", "Ein SaaS-Unternehmen mit Kunden auf der ganzen Welt hat ein gemischtes Währungsrisiko, das sich nur dann ausgleicht, wenn die Währungen tatsächlich breit gestreut sind."),
            ("p", "Die Lücke zwischen diesen beiden Linien – was Sie umrechnen müssen, in welche Richtung und wann – ist Ihr Währungsrisiko. Ist es gering und tritt selten auf, ist dieser ganze Leitfaden in zehn Minuten gelesen. Ist es hoch und wiederkehrend, machen sich die folgenden Gewohnheiten schnell bezahlt."),
            ("h", "Gewohnheit 1: Stellen Sie Rechnungen nach Möglichkeit in Ihrer eigenen Währung"),
            ("p", "Am einfachsten verringern Sie das Risiko, indem Sie es zum **Problem des Kunden** machen: Setzen Sie den Preis in Ihrer Währung fest und geben Sie klar an, dass der Betrag in dieser Währung gilt. Viele Kunden akzeptieren das ohne zu zögern; manche wehren sich, und ein Rabatt kann günstiger sein als ein Jahr voller Wechselkursschwankungen. Große Kunden bestehen oft auf ihrer eigenen Währung – dann kommen die anderen Gewohnheiten ins Spiel."),
            ("h", "Gewohnheit 2: Rechnen Sie nach einer festen Regel zeitnah um"),
            ("p", "Wenn Sie Fremdwährung erhalten und sie behalten, „bis der Kurs gut aussieht“, spekulieren Sie mit Einnahmen, die Sie vielleicht brauchen. Eine einfache Regel – etwa innerhalb einer festgelegten Anzahl von Tagen nach Eingang umzurechnen oder bei Erreichen eines für Sie akzeptablen Kursniveaus – macht aus Glück einen planbaren Prozess. Die meisten Banking- und Überweisungs-Apps bieten genau dafür Kursalarme."),
            ("h", "Gewohnheit 3: Nutzen Sie ein Mehrwährungskonto"),
            ("p", "Moderne Geschäftskonten ermöglichen es Ihnen, Fremdwährungen **zu halten**, statt sie automatisch umzurechnen. Wenn Sie einige Lieferanten oder Auftragnehmer in derselben Währung bezahlen, in der Sie Rechnungen stellen, gleichen sich Teile des Risikos auf natürliche Weise aus – keine Umrechnung, keine Kosten, keine Entscheidung."),
            ("h", "Gewohnheit 4: Teilen Sie größere Umtauschbeträge auf"),
            ("p", "Bei einer einzelnen großen Zahlung – etwa für Ausrüstung, eine Anzahlung oder eine Steuerrechnung – verteilt eine Umrechnung in zwei oder drei Teilbeträge über mehrere Tage das Wechselkursrisiko. So vermeiden Sie, den gesamten Betrag am schlechtesten Tag des Monats umzutauschen. Für wirklich große und absehbare Zahlungen in der Zukunft bieten Banken **Termingeschäfte** an, mit denen sich der heutige Kurs für einen Zeitpunkt in einigen Monaten festschreiben lässt. Der Nachteil: Von einer günstigen Kursentwicklung profitieren Sie dann nicht."),
            ("h", "Gewohnheit 5: Kalkulieren Sie einen Puffer ein"),
            ("p", "Wenn Sie in der Währung des Kunden anbieten müssen, kalkulieren Sie einen Puffer für mögliche Wechselkursbewegungen zwischen Angebot und Zahlung ein – und geben Sie an, dass der Preis nur für einen begrenzten Zeitraum gilt. Freiberufler, die Angebote mit „30 Tage gültig“ versehen, machen aus einem bekannten Risiko stillschweigend ein begrenztes Risiko."),
            ("h", "Was Sie vermeiden sollten"),
            ("li", "Handeln Sie nicht nebenbei mit Währungen, wenn Ihr Unternehmen das Geld braucht – das ist keine Absicherung mehr."),
            ("li", "Ignorieren Sie bei der Steuerung des Wechselkurses nicht die Umrechnungskosten: Ein Spread von 3 % frisst mehr weg als die meisten Gewinne durch gutes Timing."),
            ("li", "Lassen Sie das Risiko nicht ungemessen: Notieren Sie, wie viel Sie jährlich in jeder Währung einnehmen und ausgeben, und prüfen Sie die Differenz."),
            ("p", "Wenn Sie so vorgehen, sind Wechselkurse kein Lottoschein mehr, der an Ihrem Einkommen hängt, sondern das, was sie sein sollten: ein verständlicher Posten mit kontrollierbaren Kosten."),
        ],
    },
    "hidden-currency-fees": {
        "title": "Versteckte Kosten beim Währungsumtausch (und wie Sie sie vermeiden)",
        "description": "Die angezeigte Gebühr macht selten die gesamten Kosten aus. Wechselkursaufschläge, dynamische Währungsumrechnung sowie Geldautomaten- und Zwischenbankgebühren kosten Sie Geld – so erkennen Sie sie und behalten mehr davon.",
        "sections": [
            ("p", "Die Gebühr, die auf dem Bildschirm steht, ist selten die Gebühr, die Sie tatsächlich zahlen. Die Kosten einer Währungsumrechnung treten in vier Verkleidungen auf – und die größte davon wird überhaupt nicht als Gebühr ausgewiesen."),
            ("h", "1. Der Wechselkursaufschlag"),
            ("p", "Wenn ein Anbieter Ihnen einen Kurs nennt, der 2 % schlechter ist als der Mittelkurs, sind diese 2 % eine Gebühr – sie sieht nur nicht so aus. Bei einer Überweisung von 5.000 Einheiten kostet ein Aufschlag von 2 % ganze 100 Einheiten, während das Versprechen „keine Gebühren“ die Lorbeeren erntet. Bei den meisten Umtauschvorgängen ist dies der größte Kostenpunkt. Er lässt sich nur erkennen, indem Sie den angebotenen Kurs vor dem Abschluss mit dem **Mittelkurs als Referenz** vergleichen."),
            ("h", "2. Dynamische Währungsumrechnung (DCC)"),
            ("p", "Die teuerste Taste auf Reisen: Wenn Ihnen ein Kartenterminal oder Geldautomat im Ausland anbietet, **in Ihrer Heimatwährung** abzurechnen, rechnet der Betreiber zum eigenen Kurs um – meist 3–10 % schlechter als Ihre Bank. Wählen Sie immer die Zahlung in der **Landeswährung** und überlassen Sie die Umrechnung Ihrer Bank."),
            ("h", "3. Gebühren für Geldautomaten und Karten"),
            ("li", "Ausländische Geldautomatenbetreiber erheben häufig eine **Pauschalgebühr** pro Abhebung."),
            ("li", "Ihre eigene Bank kann zusätzlich einen **Auslandseinsatzaufschlag** berechnen (oft 1–3 %)."),
            ("li", "Heben Sie seltener größere Beträge ab, damit die Pauschalgebühren weniger ins Gewicht fallen, und bevorzugen Sie **Geldautomaten von Banken** statt frei stehender Automaten in Geschäften."),
            ("h", "4. Überweisungs- und Zwischenbankgebühren"),
            ("p", "Internationale Banküberweisungen laufen mitunter über eine oder zwei **Zwischenbanken**. Jede zieht ihre eigene Gebühr ab, bevor das Geld ankommt – der Empfänger erhält dadurch deutlich weniger als Sie überwiesen haben, ohne dass eine Position erklärt, wohin der fehlende Betrag geflossen ist. Spezialisierte Überweisungsdienste weisen ihre Gebühren vorab aus – genau deshalb sind sie meist günstiger."),
            ("h", "Der Vergleich, der nicht täuscht"),
            ("p", "Ignorieren Sie beworbene Gebühren und auffällige Wechselkurse. Bei jedem Anbieter entscheidet eine Frage:"),
            ("p", "**Wenn ich heute X sende, wie viel genau kommt an – in der Währung des Empfängers und nach Abzug aller Kosten?**"),
            ("p", "Holen Sie diese Zahl am selben Tag bei zwei oder drei Anbietern ein und wählen Sie den höchsten Betrag. Da sich Kurse täglich ändern, sollten Sie den Vergleich bei der nächsten Überweisung wiederholen – der günstigste Anbieter im letzten Jahr ist nicht automatisch heute der günstigste."),
            ("h", "Eine kurze Checkliste"),
            ("li", "Vergleichen Sie zuerst den angebotenen Kurs mit dem Mittelkurs."),
            ("li", "Zahlen Sie im Ausland immer in Landeswährung und lehnen Sie Umrechnungsangebote ab."),
            ("li", "Bündeln Sie Geldautomatenabhebungen, damit Pauschalgebühren weniger ins Gewicht fallen."),
            ("li", "Bevorzugen Sie Anbieter, die den „Auszahlungsbetrag“ vorab nennen."),
            ("li", "Prüfen Sie vor jeder Überweisung erneut – nicht nur einmal im Jahr."),
            ("p", "Keiner dieser Schritte dauert länger als ein paar Minuten. Zusammen sparen sie bei jeder Umrechnung regelmäßig 2–5 % – bei einem Jahr voller Überweisungen ist das bares Geld."),
        ],
    },
    "how-exchange-rates-work": {
        "title": "Wie Wechselkurse festgelegt werden",
        "description": "Wer bestimmt, was eine Währung wert ist? Eine leicht verständliche Erklärung fester, frei schwankender und gesteuerter Wechselkurssysteme.",
        "sections": [
            ("p", "Wechselkurse beantworten eine Frage: Wie viel von einer Währung benötigen Sie, um eine andere zu kaufen? Aber wer legt diese Zahl fest? Das hängt von der Währung ab – es gibt drei grundlegende Systeme."),
            ("h", "Flexible Wechselkurse"),
            ("p", "Die meisten großen Währungen – US-Dollar, Euro, japanischer Yen und britisches Pfund – **schwanken frei**. Ihr Wert wird laufend durch Angebot und Nachfrage am globalen Devisenmarkt bestimmt, dem größten Finanzmarkt der Welt mit einem täglichen Umsatz von mehr als 7 Billionen US-Dollar."),
            ("h", "Feste (gebundene) Wechselkurse"),
            ("p", "Manche Währungen sind an eine andere Währung **gebunden**. Der saudi-arabische Riyal und der Dirham der Vereinigten Arabischen Emirate sind fest an den US-Dollar gekoppelt; die dänische Krone ist an den Euro gebunden. Die Zentralbank verpflichtet sich, ihre Währung zu kaufen oder zu verkaufen, damit der Wechselkurs innerhalb einer engen Bandbreite bleibt."),
            ("h", "Gesteuerte Wechselkurse"),
            ("p", "Viele Währungen, etwa der chinesische Yuan, werden **gesteuert**: Die Zentralbank lässt Bewegungen am Markt zu, greift aber ein, wenn sich der Kurs außerhalb eines akzeptablen Bereichs bewegt."),
            ("h", "Woher die Kurse von Fxverter stammen"),
            ("p", "Fxverter zeigt **Referenzkurse**: Tagesendkurse, die von der Europäischen Zentralbank und anderen öffentlichen Quellen veröffentlicht werden. Sie eignen sich hervorragend zum Vergleichen, Planen und Schätzen – doch Banken und Kartennetzwerke schlagen eigene Margen und Gebühren auf, daher weicht der Kurs, den Sie bei einer Überweisung tatsächlich zahlen, davon ab. Bestätigen Sie den endgültigen Kurs immer bei Ihrer Bank oder Ihrem Anbieter."),
        ],
    },
    "inflation-and-exchange-rates": {
        "title": "Inflation und Wechselkurse – wie sie zusammenhängen",
        "description": "Hohe Inflation entwertet eine Währung über Jahre, und Zentralbanken bekämpfen sie mit Zinssätzen. Wer beide Kräfte versteht, kann die meisten langfristigen Währungstrends nachvollziehen.",
        "sections": [
            ("p", "Fragt man, warum eine Währung über ein Jahrzehnt an Wert verloren hat, beginnt die Antwort meist bei der Inflation. Fragt man, warum sie diesen Monat stärker geworden ist, geht es meist um Zinssätze. Beide Kräfte hängen zusammen – hier erfahren Sie, wie dieser Mechanismus funktioniert."),
            ("h", "Inflation entwertet eine Währung langsam"),
            ("p", "Im Grunde ist eine Währung ein Anspruch auf die Waren und Dienstleistungen einer Volkswirtschaft. Verdoppeln sich die Preise, während die Geldmenge gleich bleibt, kann jede Geldeinheit nur noch halb so viel kaufen – und ausländische Anleger zahlen entsprechend weniger dafür. Über Jahre hinweg wertet die Währung eines Landes gegenüber denen seiner Handelspartner tendenziell ab, wenn dort **dauerhaft höhere Inflation herrscht**."),
            ("p", "Die deutlichsten Beispiele sind Währungen, die innerhalb einer Generation den größten Teil ihres Wertes verloren haben: die türkische Lira, der argentinische Peso und der venezolanische Bolívar. In jedem dieser Fälle führten jahrelanges Gelddrucken und zweistellige Inflationsraten zu dem Ergebnis, das die Kaufkraftlogik erwarten ließ."),
            ("h", "Kaufkraftparität: der langsame Anker"),
            ("p", "Die Idee dahinter heißt **Kaufkraftparität (KKP)**: Langfristig passen sich Wechselkurse so an, dass derselbe Warenkorb überall ungefähr gleich viel kostet. Kostet ein Warenkorb im Inland 100 Einheiten und nach der Umrechnung im Ausland doppelt so viel, stimmt der Wechselkurs nicht – mit der Zeit bewegen sich entweder der Kurs oder die Preise, bis sich die Lücke schließt."),
            ("p", "Für eine Prognose der nächsten Woche ist die KKP nutzlos. Erstaunlich nützlich ist sie dagegen, um zu beurteilen, ob eine Währung nach einer starken Bewegung **offensichtlich überdehnt** ist. Deshalb veröffentlichen Ökonomen immer wieder Vergleiche nach Art des Big-Mac-Index."),
            ("h", "Zinssätze: der schnelle Hebel"),
            ("p", "Zentralbanken bekämpfen Inflation, indem sie die Zinssätze anheben. Höhere Zinsen machen Einlagen und Anleihen in der betreffenden Währung attraktiver, ziehen ausländisches Kapital an und stützen den Wechselkurs – zumindest solange Anleger glauben, dass die Zentralbank an ihrem Kurs festhält."),
            ("p", "Deshalb wiederholt sich weltweit dasselbe Muster: Eine Zentralbank **hebt die Zinsen kräftig an**, und die Währung wird stärker; sie **senkt die Zinsen oder verliert an Glaubwürdigkeit**, und die Währung wird schwächer. Die türkische Lira fiel, als die Zinsen trotz steigender Inflation gesenkt wurden, und erholte sich, als die Politik zum orthodoxen Kurs zurückkehrte. Brasiliens Real profitiert von einigen der höchsten Realzinsen weltweit."),
            ("h", "Entscheidend sind die Realzinsen"),
            ("p", "Was Kapital bewegt, ist nicht der Nominalzins, sondern der **Realzins**: der Leitzins abzüglich der Inflation. Ein Leitzins von 40 % bei 50 % Inflation ist weiterhin stark negativ – dort angelegtes Geld verliert jedes Jahr an Kaufkraft. Genau deshalb bevorzugen Einheimische US-Dollar. Ein Zinssatz von 5 % bei 2 % Inflation ist dagegen tatsächlich attraktiv."),
            ("h", "Was das für Sie bedeutet"),
            ("li", "**Reisende:** Reiseziele mit hoher Inflation werden in Hartwährungen mit der Zeit günstiger – prüfen Sie aber die aktuellen Kurse, denn der Markt hat einen Teil dieser Entwicklung meist bereits eingepreist."),
            ("li", "**Sparer:** Wer Ersparnisse in einer Währung mit hoher Inflation und negativen Realzinsen hält, verliert langsam an Wert, selbst wenn das Konto „Zinsen zahlt“."),
            ("li", "**Unternehmen:** Wenn die Währung des Vertragspartners an Glaubwürdigkeit verliert, sollten Sie langfristige Verträge in einer Hartwährung bepreisen oder an die Inflation koppeln."),
            ("p", "Die Inflation ist die langsame Strömung, die darüber entscheidet, wo Währungen langfristig landen. Die Zinssätze sind die Wellen, die bestimmen, wohin sie sich in diesem Monat bewegen."),
        ],
    },
    "mid-market-rate": {
        "title": "Was ist der Mittelkurs?",
        "description": "Der Mittelkurs liegt zwischen dem Kauf- und Verkaufskurs und ist der Vergleichswert, an dem Sie internationale Geldtransfers messen sollten.",
        "sections": [
            ("p", "Wenn Sie Geld ins Ausland überweisen oder Fremdwährung kaufen, nennen Anbieter Ihnen einen Kurs mit Aufschlag. Um beurteilen zu können, ob das Angebot fair ist, brauchen Sie eine Zahl: den **Mittelkurs**."),
            ("h", "Definition"),
            ("p", "Der Mittelkurs ist der Mittelwert zwischen dem **Geldkurs** (dem Preis, den Käufer aktuell zu zahlen bereit sind) und dem **Briefkurs** (dem Preis, den Verkäufer akzeptieren) am globalen Devisenmarkt. Er ist die fairste einzelne Momentaufnahme des Währungswerts – derselbe Kurs, den Sie bei Fxverter, Google und auf Finanznachrichtenseiten sehen."),
            ("h", "Warum der Kurs Ihrer Bank schlechter ist"),
            ("p", "Banken und Überweisungsdienste verstecken üblicherweise eine Marge **im** Wechselkurs – oft 1–4 %, manchmal deutlich mehr – und berechnen zusätzlich Gebühren. Bei einer Überweisung über 10.000 Einheiten kostet eine Marge von 3 % unbemerkt 300 Einheiten, meist mehr als jede ausgewiesene „Gebühr“."),
            ("h", "So nutzen Sie den Mittelkurs"),
            ("li", "Vergleichen Sie den angebotenen Kurs mit dem Fxverter-Kurs für dasselbe Währungspaar."),
            ("li", "Fragen Sie den Anbieter nach den **Gesamtkosten in der Zielwährung**, einschließlich aller Gebühren und Aufschläge."),
            ("li", "Kleinere Abweichungen sind normal – Anbieter benötigen eine Marge –, aber bei mehreren Prozent lohnt sich ein Vergleich."),
            ("h", "Was Sie beachten sollten"),
            ("p", "Mittelkursangaben sind Referenzkurse, die meist einmal oder einige Male am Tag aktualisiert werden, keine Live-Handelspreise. Der genaue Kurs einer tatsächlichen Überweisung wird leicht abweichen. Der Mittelkurs ist der Vergleichswert, nicht der vertraglich zugesicherte Kurs."),
        ],
    },
    "reading-exchange-rate-quotes": {
        "title": "Wechselkursangaben richtig lesen",
        "description": "Basiswährung, Kurswährung, Pips und Spreads – ein Leitfaden in fünf Minuten, um zu verstehen, was eine Wechselkursangabe tatsächlich aussagt.",
        "sections": [
            ("p", "Eine Wechselkursangabe wirkt einfach – **EUR/USD 1,08** –, enthält aber mehrere Informationen in einer einzigen Zahl. So lesen Sie sie richtig und erkennen, wenn ein angegebener Kurs Kosten verschleiert."),
            ("h", "Welche Währung ist welche?"),
            ("p", "Bei jedem Währungspaar steht die **Basiswährung** zuerst und die **Kurswährung** an zweiter Stelle. Die Zahl gibt an, wie viel Kurswährung Sie für eine Einheit der Basiswährung erhalten:"),
            ("li", "**EUR/USD 1,08** → 1 Euro entspricht 1,08 US-Dollar."),
            ("li", "**USD/JPY 150,00** → 1 US-Dollar entspricht 150 japanischen Yen."),
            ("p", "Die Reihenfolge ist eine Marktübereinkunft und keine freie Wahl: Manche Paare werden immer in einer Richtung notiert (EUR/USD, GBP/USD), andere umgekehrt (USD/JPY, USD/CAD). Wenn Sie einen Kurs nachschlagen, vergewissern Sie sich, welche Währung die Basiswährung ist – sonst könnten Sie 150 Yen für 150 Dollar halten."),
            ("h", "Die große Zahl und die Pips"),
            ("p", "Bei EUR/USD 1,0850 ist **die große Zahl** 1,08; die letzten beiden Stellen – die Pips – sind 50. Die meisten Paare werden mit vier oder fünf Nachkommastellen notiert, Yen-Paare mit zwei oder drei. Die täglichen Bewegungen wichtiger Währungspaare betragen oft nur einige Dutzend Pips. Deshalb gilt eine Bewegung von 1 % an einem Tag als groß."),
            ("h", "Warum Sie einen Kurs sehen, der Markt aber zwei"),
            ("p", "An den professionellen Märkten werden **zwei Preise** notiert: der Geldkurs (zu dem der Anbieter kauft) und der Briefkurs (zu dem der Anbieter verkauft). Die Differenz dazwischen ist der **Spread** – die Transaktionskosten des Marktes. Bei EUR/USD kann er einen Bruchteil eines Pips betragen; bei einem exotischen Währungspaar kann er hunderte Male größer sein."),
            ("p", "Wenn Sie als Kunde Geld umtauschen, sehen Sie in der Regel **einen Kurs**. Dieser entspricht dem Mittelkurs zuzüglich der Marge des Anbieters. Je größer die Differenz zwischen dem Mittelkurs und dem angebotenen Kurs, desto mehr kostet Sie die Umrechnung tatsächlich – unabhängig davon, was in der Gebührenspalte steht."),
            ("h", "Kreuzkurse: Warum der Dollar überall vorkommt"),
            ("p", "Die meisten Währungspaare werden nicht direkt gehandelt. Wenn Sie dänische Kronen in brasilianische Real umtauschen möchten, setzt der Markt den Kurs aus DKK→USD und USD→BRL zusammen. Darum sind dollarbasierte Referenzkurse für alle Währungen nützlich und Spreads bei manchen ungewöhnlichen Paaren breiter: Sie bezahlen für zwei Umrechnungen, obwohl Sie nur eine sehen."),
            ("h", "Ein praktischer Ablauf"),
            ("li", "Ermitteln Sie den **Mittelkurs** Ihres Währungspaars (bei Fxverter, Google oder einer anderen Referenzquelle)."),
            ("li", "Lassen Sie sich vom Anbieter den **Auszahlungsbetrag** für Ihre Überweisung nennen."),
            ("li", "Teilen Sie den Auszahlungsbetrag durch den Betrag, den der Mittelkurs ergeben würde – die Differenz sind die tatsächlichen Kosten."),
            ("li", "Wiederholen Sie den Vergleich mit einem zweiten Anbieter. Die Differenz entscheidet, nicht die Gebühr."),
            ("p", "Wenn Sie Kursangaben auf diese Weise lesen, zieht das Marketingversprechen „keine Provision“ bei Ihnen nicht mehr – denn Sie achten dann nicht länger nur auf die Zahl, die der Anbieter Ihnen zeigen möchte."),
        ],
    },
    "send-money-abroad": {
        "title": "Geld ins Ausland überweisen, ohne zu viel zu bezahlen",
        "description": "Banken verstecken 1–4 % im Wechselkurs. So vergleichen Sie in drei Minuten die Gesamtkosten einer Auslandsüberweisung und behalten den Aufschlag in der eigenen Tasche.",
        "sections": [
            ("p", "Wenn Sie Geld über Landesgrenzen hinweg überweisen, zahlen Sie selten nur die „Gebühr“, die Sie auf dem Bildschirm sehen. Die tatsächlichen Kosten verstecken sich im Wechselkurs – und machen meist den größeren Teil der Rechnung aus."),
            ("h", "Die versteckten Kosten: der Wechselkursaufschlag"),
            ("p", "Banken und viele Überweisungsdienste bieten Ihnen einen schlechteren Kurs als den Mittelkurs (den Mittelwert aus Kauf- und Verkaufskurs, den Sie bei Fxverter oder Google sehen). Die Differenz beträgt üblicherweise **1–4 %**, bei exotischen Währungskorridoren manchmal deutlich mehr. Bei einer Überweisung von 10.000 Einheiten kostet eine Marge von 3 % unbemerkt 300 Einheiten – meist mehr als jede beworbene Gebühr."),
            ("h", "Vergleichen Sie den Auszahlungsbetrag, nicht die Gebühr"),
            ("p", "Entscheidend ist nur eine Zahl: **wie viel ankommt**. Berechnen Sie bei jedem Anbieter:"),
            ("li", "die berechnete Gebühr, plus"),
            ("li", "die Differenz zwischen dem angebotenen Kurs und dem Mittelkurs."),
            ("p", "Berücksichtigen Sie beides in der Zielwährung, erhalten Sie die tatsächlichen Kosten. Ein Anbieter ohne Gebühr, aber mit 4 % Aufschlag ist viel teurer als einer mit einer sichtbaren Gebühr von 5 US-Dollar und einer Marge von 0,3 %."),
            ("h", "Drei Minuten sorgfältiger Vergleich"),
            ("li", "Prüfen Sie den **Mittelkurs** Ihres Währungspaars unmittelbar vor der Überweisung – Kurse bewegen sich."),
            ("li", "Fragen Sie den Anbieter nach dem **Gesamtbetrag in der Währung des Empfängers**, einschließlich aller Kosten."),
            ("li", "Vergleichen Sie am selben Tag mindestens zwei Anbieter; die Margen unterscheiden sich je nach Währungskorridor stark."),
            ("li", "Fragen Sie bei größeren Beträgen nach einer **besseren Kursstufe** – viele Dienste bieten ab bestimmten Beträgen bessere Konditionen an."),
            ("li", "Achten Sie auf **Werbekurse**, die nur für die erste Überweisung gelten."),
            ("h", "Zeitpunkt und Überweisungsart"),
            ("p", "Bei den meisten gängigen Überweisungsstrecken sind spezialisierte Anbieter günstiger als Banküberweisungen; die Geschwindigkeit ist ähnlich (von wenigen Minuten bis zu einem Tag). Vermeiden Sie den Bargeldumtausch am Flughafen – dort sind die Margen branchenweit am höchsten. Ist die Überweisung nicht dringend, kann es sich eher lohnen, den Kurs einige Tage zu beobachten und bei einem günstigen Stand einen Alarm einzurichten, als nur einen Gebührennachlass auszuhandeln."),
            ("h", "Die Regel in einem Satz"),
            ("p", "**Ignorieren Sie die Gebühr und vergleichen Sie den Auszahlungsbetrag.** Alles andere ist Marketing."),
        ],
    },
    "travel-money": {
        "title": "Geld auf Reisen – Bargeld, Karte oder Umtausch?",
        "description": "Wie viel Bargeld Sie im Ausland dabeihaben sollten, mit welcher Karte Sie zahlen und warum „in der eigenen Währung bezahlen“ die teuerste Taste an jedem Zahlungsterminal ist.",
        "sections": [
            ("p", "Jede Reise beginnt mit derselben Frage: Wie viel Geld sollte man vor der Abreise umtauschen, und wie bezahlt man vor Ort? Die Antwort hängt weniger vom Reiseziel ab als von drei Entscheidungen, die Sie am Terminal treffen."),
            ("h", "Die goldene Regel an jedem Terminal"),
            ("p", "Wenn Ihnen ein Kartenterminal oder Geldautomat anbietet, **in Ihrer Heimatwährung statt in der Landeswährung abzurechnen**, lehnen Sie immer ab. Das heißt dynamische Währungsumrechnung (DCC) und verbirgt einen Aufschlag von 3–10 % hinter einer scheinbar bequemen Bildschirmoption. Wählen Sie **immer die Zahlung in Landeswährung** und lassen Sie Ihre eigene Bank umrechnen – selbst mäßige Bankkurse sind fast immer besser als DCC."),
            ("h", "Wie viel Bargeld Sie dabeihaben sollten"),
            ("li", "**Bargeldlastige Reiseziele:** Japan, Deutschland, Südostasien außerhalb der Großstädte sowie Märkte und ländliche Gegenden überall."),
            ("li", "**Kartenfreundliche Reiseziele:** die nordischen Länder, Großbritannien, China (mobiles Bezahlen) und die meisten Städte Nordamerikas."),
            ("li", "Eine vernünftige Faustregel: Nehmen Sie **Bargeld in Landeswährung für ein bis zwei Tage** mit und heben Sie bei Bedarf am Geldautomaten nach, statt vorab große Beträge umzutauschen."),
            ("h", "Die richtige Strategie am Geldautomaten"),
            ("p", "Wechselstuben an Flughäfen haben die höchsten Margen der Branche – nutzen Sie sie nur im Notfall. Abhebungen an Geldautomaten von Banken im Zielland bieten meist einen Kurs nahe dem Mittelkurs. Üblicherweise lohnt es sich, Bargeld für einige Tage auf einmal abzuheben, damit feste Geldautomatengebühren weniger ins Gewicht fallen. Lehnen Sie das Umrechnungsangebot des Automaten ab – es ist dieselbe DCC-Falle."),
            ("h", "Karten, die sich auf Reisen bewähren"),
            ("li", "Karten **ohne Auslandseinsatzgebühr** sparen den üblichen Aufschlag von 1–3 % bei jedem Einkauf."),
            ("li", "Mit **aufladbaren Reisekarten** können Sie sich einen Kurs sichern – praktisch für die Budgetplanung, aber Sie profitieren nicht von einer günstigen Kursbewegung."),
            ("li", "**Digitale Geldbörsen** (Apple Pay, Google Pay) übernehmen die Konditionen Ihrer Karte und werden häufiger akzeptiert, als viele Reisende erwarten."),
            ("h", "Halten Sie eine kleine Reserve in einer Hartwährung bereit"),
            ("p", "Ein gefalteter Vorrat an **US-Dollar oder Euro** ist die universelle Reserve: Er lässt sich in jedem Land der Welt umtauschen und ist die klassische Notlösung, wenn Karten nicht funktionieren, Geldautomaten ausgefallen sind oder eine Landeswährung in Turbulenzen gerät. Wahrscheinlich werden Sie ihn nie brauchen – genau dafür ist eine Reserve gedacht."),
            ("h", "Die Checkliste"),
            ("li", "Informieren Sie Ihre Bank oder – noch besser – nutzen Sie eine Karte ohne Auslandseinsatzgebühr."),
            ("li", "Nehmen Sie etwas Bargeld aus der Heimat für die ersten Stunden mit, nicht das gesamte Reisebudget."),
            ("li", "Heben Sie im Zielland an Bankautomaten Bargeld ab und lehnen Sie Umrechnungsangebote ab."),
            ("li", "Zahlen Sie immer in der Landeswährung."),
            ("li", "Bewahren Sie eine USD-/EUR-Reserve getrennt von Ihrer Geldbörse auf."),
            ("p", "Befolgen Sie diese fünf Tipps, bekommen Sie einen besseren Kurs als die meisten Reisenden – und müssen bis zum Rückflug nicht mehr über Geld nachdenken."),
        ],
    },
    "when-to-exchange": {
        "title": "Wann ist der beste Zeitpunkt, Währungen umzutauschen?",
        "description": "Niemand kann Wechselkurse zuverlässig vorhersagen. Sie können aber die ungünstigsten Zeitpunkte vermeiden, statt zu raten, Kursalarme zu nutzen und größere Umtauschbeträge aufzuteilen, um einen Durchschnittskurs zu erzielen.",
        "sections": [
            ("p", "Zuerst die ehrliche Antwort: **Niemand kann Wechselkurse zuverlässig vorhersagen** – weder Banken noch Analysten noch Algorithmen. Professionelle Devisenhändler mit besseren Daten als wir alle zusammen liegen bei kurzen Prognosezeiträumen kaum öfter richtig als ein Münzwurf. Es geht also nicht darum, den perfekten Zeitpunkt zu erraten, sondern die schlechtesten Momente zu vermeiden und einfache Mechanismen für sich arbeiten zu lassen."),
            ("h", "Was die Kurse kurzfristig tatsächlich bewegt"),
            ("p", "Tägliche Kursbewegungen werden durch Nachrichten ausgelöst: Entscheidungen der Zentralbanken, Inflationszahlen, Arbeitsmarktdaten und politische Ereignisse. Manches davon ist geplant, anderes kommt plötzlich – der Markt reagiert innerhalb von Sekunden. Wenn Sie eine Schlagzeile über einen „starken Dollar“ lesen, ist die Bewegung meist schon geschehen."),
            ("p", "Über Wochen und Monate bewegen sich die Kurse im Einklang mit Zinsdifferenzen und der wirtschaftlichen Dynamik. Über Jahre kehren Währungen tendenziell zu einem Wert zurück, den die wirtschaftlichen Fundamentaldaten rechtfertigen – doch „Jahre“ sind kein sinnvoller Planungshorizont für eine Reise oder Rechnung."),
            ("h", "Nutzen Sie Kursalarme statt Prognosen"),
            ("p", "Die meisten Bank- und Überweisungs-Apps bieten **Kursalarme**: Sie legen einen für Sie günstigen Kurs fest und werden benachrichtigt, wenn der Markt ihn erreicht. So ersetzen Sie das Raten durch eine klare Regel. Erreicht der Kurs Ihren Zielwert nicht, haben Sie trotzdem umgetauscht – nur ohne Glückstreffer. Erreicht er ihn doch, schneiden Sie etwas besser ab als der durchschnittliche Marktteilnehmer. Über ein Jahr voller Überweisungen summiert sich das."),
            ("h", "Teilen Sie größere Umtauschbeträge auf"),
            ("p", "Wenn Sie einen großen Betrag überweisen – etwa für Studiengebühren, eine Immobilienanzahlung oder eine geschäftliche Zahlung –, sollten Sie ihn **über mehrere Tage oder Wochen aufteilen**. Den Höchst- oder Tiefstkurs werden Sie damit nicht treffen, aber Sie erhalten den **Durchschnittskurs** des Zeitraums. Der liegt meist nahe am fairen Kurs und nimmt Ihnen das Risiko, alles ausgerechnet am schlechtesten Tag des Monats umzutauschen."),
            ("h", "Die ungünstigsten Zeitpunkte für den Umtausch"),
            ("li", "**Wechselstuben am Flughafen** – zu jeder Tageszeit die höchsten Margen der Branche."),
            ("li", "**Zeitdruck in letzter Minute** – wenn Sie heute umtauschen müssen, haben Sie keinerlei Verhandlungsspielraum."),
            ("li", "**Ferienansturm** – in den Zielländern steigt die Nachfrage während großer Feiertage."),
            ("li", "**Unmittelbar nach einer dramatischen Schlagzeile** – genau dann, wenn alle reagieren, ist die Volatilität am höchsten und die Spreads werden breiter."),
            ("h", "Für Unternehmen: Schluss mit Timing, her mit der Absicherung"),
            ("p", "Unternehmen mit wiederkehrenden Rechnungen in Fremdwährungen sollten gar nicht erst versuchen, den richtigen Zeitpunkt zu treffen. Die üblichen Instrumente sind einfach: Stellen Sie Rechnungen nach Möglichkeit in Ihrer eigenen Währung, nutzen Sie ein Mehrwährungskonto, um Zahlungen und Einnahmen natürlich auszugleichen, und fragen Sie Ihre Bank bei großen, planbaren Zahlungen nach einem **Termingeschäft**. Damit sichern Sie sich den heutigen Kurs für einen zukünftigen Zeitpunkt und machen aus unvorhersehbaren Kosten einen bekannten Betrag."),
            ("h", "Das Wichtigste"),
            ("p", "Richten Sie einen Kursalarm ein, vermeiden Sie die bekannten ungünstigen Zeitpunkte, teilen Sie große Beträge auf und machen Sie weiter mit Ihrem Leben. Die Zeit, die Sie nicht mit dem Beobachten von Kursdiagrammen verbringen, ist mehr wert als der Bruchteil eines Prozents, den Sie vielleicht durch Beobachten erwischen."),
        ],
    },
}
