GUIDE_L10N = {
    "exchange-rate-risk": {
        "title": "Risco cambial — um guia para freelancers e pequenas empresas",
        "description": "Se você fatura ou paga em moeda estrangeira, o risco cambial já faz parte do seu negócio. Veja como identificá-lo, medi-lo e reduzi-lo sem precisar virar operador do mercado financeiro.",
        "sections": [
            ("p", "Se um cliente paga a você em uma moeda que não usa no dia a dia, ou se um fornecedor cobra em uma moeda que você não recebe, você está exposto ao **risco cambial**, tenha pensado nisso ou não. Uma variação de 5% contra você pode eliminar toda a margem de um projeto. A boa notícia: não é preciso virar operador de câmbio para controlar esse risco — bastam alguns hábitos."),
            ("h", "Primeiro, descubra onde está o risco"),
            ("p", "Trace duas linhas: o que você **ganha** e o que **gasta**, cada coisa na respectiva moeda."),
            ("li", "Um freelancer que fatura de clientes americanos, mas vive na zona do euro, ganha dólares e gasta euros — cada fatura fica exposta à cotação até ser paga e convertida"),
            ("li", "Um importador que compra da Ásia e vende no mercado interno faz o contrário: primeiro, assume um custo em moeda estrangeira"),
            ("li", "Uma empresa de SaaS que cobra clientes no mundo todo tem uma exposição diversificada, que só se compensa se as moedas estiverem de fato bem distribuídas"),
            ("p", "A diferença entre essas duas linhas — o que você precisa converter, em que direção e quando — é a sua exposição. Se ela for pequena e esporádica, este guia inteiro leva dez minutos para ler. Se for grande e recorrente, os hábitos a seguir logo se pagam."),
            ("h", "Hábito 1: fature na sua própria moeda quando puder"),
            ("p", "A forma mais simples de reduzir o risco é deixá-lo com o **cliente**: defina o preço na sua moeda e deixe claro que o valor é fixo nela. Muitos clientes aceitam sem hesitar; alguns resistem, e oferecer um desconto pode sair mais barato do que passar um ano sujeito às oscilações cambiais. Clientes grandes muitas vezes preferem pagar na própria moeda — é aí que os outros hábitos fazem diferença."),
            ("h", "Hábito 2: converta logo, seguindo uma regra"),
            ("p", "Se você recebe moeda estrangeira e a mantém parada “até a cotação parecer boa”, está especulando com uma receita de que talvez precise. Uma regra simples — converter dentro de um número definido de dias após o recebimento ou quando a cotação atingir um patamar aceitável para você — transforma sorte em processo. A maioria dos aplicativos bancários e de remessas oferece alertas de cotação justamente para isso."),
            ("h", "Hábito 3: use uma conta multimoeda"),
            ("p", "As contas empresariais modernas permitem **manter** saldo em moeda estrangeira, em vez de convertê-lo automaticamente. Se você paga alguns fornecedores ou prestadores na mesma moeda em que fatura, compensar esses valores reduz naturalmente parte do risco — sem conversão, sem custo e sem decisão."),
            ("h", "Hábito 4: divida as conversões grandes"),
            ("p", "Para um pagamento grande e pontual — equipamentos, um sinal ou um imposto — dividir a conversão em duas ou três partes ao longo de alguns dias ajuda a fazer uma média da cotação e evita converter tudo no pior dia do mês. Para pagamentos futuros realmente grandes e previsíveis, os bancos oferecem **contratos a termo**, que fixam a cotação de hoje para uma data daqui a alguns meses; a contrapartida é abrir mão de qualquer variação favorável."),
            ("h", "Hábito 5: inclua uma margem de segurança no preço"),
            ("p", "Se você precisa fazer um orçamento na moeda do cliente, inclua uma margem para cobrir a variação cambial entre o orçamento e o pagamento — e informe que o preço vale por um período limitado. Freelancers que dizem “válido por 30 dias” transformam discretamente um risco conhecido em um risco com limites."),
            ("h", "O que não fazer"),
            ("li", "Não opere no mercado de câmbio “por fora” com dinheiro de que sua empresa precisa — isso já não é proteção contra o risco"),
            ("li", "Não ignore o **custo** da conversão enquanto administra a cotação: um spread de 3% consome mais do que a maioria dos ganhos obtidos ao tentar acertar o momento"),
            ("li", "Não deixe o risco sem medir: anote quanto você ganha e gasta em cada moeda por ano e avalie a diferença"),
            ("p", "Administradas dessa forma, as taxas de câmbio deixam de ser um bilhete de loteria preso à sua renda e passam a ser o que deveriam: um item de custo que você entende e controla."),
        ],
    },
    "hidden-currency-fees": {
        "title": "Taxas ocultas na conversão de moedas (e como evitá-las)",
        "description": "A taxa exibida na tela raramente representa o custo total. Spreads, conversão dinâmica de moeda, tarifas de caixa eletrônico e taxas de bancos intermediários ficam com uma parte — veja como identificá-los e evitar essa perda.",
        "sections": [
            ("p", "A taxa que você vê na tela raramente é a que acaba pagando. Os custos de conversão de moeda aparecem disfarçados de quatro formas, e o maior deles nem sequer aparece como taxa."),
            ("h", "1. A margem na taxa de câmbio"),
            ("p", "Quando um provedor oferece uma cotação 2% pior que a taxa média de mercado, esses 2% são uma taxa — só não parecem uma. Em uma transferência de 5.000 unidades, uma margem de 2% custa 100 unidades, enquanto a chamada “taxa zero” fica com os aplausos. Esse é o maior custo na maioria das conversões, e a única maneira de percebê-lo é comparar a cotação oferecida com a **taxa de referência média de mercado** antes de confirmar."),
            ("h", "2. Conversão dinâmica de moeda (DCC)"),
            ("p", "O botão mais caro durante uma viagem: quando uma maquininha ou um caixa eletrônico no exterior oferece cobrar **na sua moeda de origem**, está propondo converter pela própria cotação — geralmente de 3% a 10% pior que a do seu banco. Escolha sempre pagar na **moeda local** e deixe seu banco fazer a conversão."),
            ("h", "3. Tarifas de caixas eletrônicos e cartões"),
            ("li", "Caixas eletrônicos de outros países costumam cobrar uma **tarifa fixa** por saque"),
            ("li", "Seu próprio banco também pode cobrar uma **sobretaxa por transação internacional** (em geral, de 1% a 3%)"),
            ("li", "Faça saques maiores com menos frequência para diluir as tarifas fixas e prefira **caixas de bancos** a máquinas independentes instaladas em lojas"),
            ("h", "4. Tarifas de transferências e bancos intermediários"),
            ("p", "Transferências bancárias internacionais podem passar por um ou dois **bancos intermediários**, cada um descontando a própria tarifa antes de o dinheiro chegar — por isso o destinatário recebe visivelmente menos do que você enviou, sem nenhum item explicar para onde foi a diferença. Serviços especializados em transferências informam as tarifas antecipadamente, e é justamente por isso que costumam ser mais baratos."),
            ("h", "A comparação que não engana"),
            ("p", "Ignore as tarifas anunciadas e as cotações destacadas. Para qualquer provedor, uma pergunta resolve tudo:"),
            ("p", "**Se eu enviar X hoje, exatamente quanto chegará — na moeda do destinatário e depois de todos os custos?**"),
            ("p", "Consulte esse valor com dois ou três provedores no mesmo dia e escolha o maior. As cotações mudam diariamente, então compare de novo quando fizer a próxima remessa — o provedor mais barato no ano passado não é necessariamente o mais barato agora."),
            ("h", "Lista rápida"),
            ("li", "Compare primeiro a cotação oferecida com a taxa média de mercado"),
            ("li", "No exterior, pague sempre na moeda local — recuse ofertas de conversão"),
            ("li", "Agrupe os saques em caixas eletrônicos para diluir as tarifas fixas"),
            ("li", "Prefira provedores que informem antecipadamente o “total a receber”"),
            ("li", "Confira novamente antes de cada transferência, não apenas uma vez por ano"),
            ("p", "Nenhuma dessas medidas leva mais do que alguns minutos e, juntas, costumam economizar de 2% a 5% por conversão — o que, ao longo de um ano de transferências, representa dinheiro de verdade."),
        ],
    },
    "how-exchange-rates-work": {
        "title": "Como as taxas de câmbio são definidas",
        "description": "Quem decide quanto vale uma moeda? Uma explicação simples sobre sistemas cambiais fixos, flutuantes e administrados.",
        "sections": [
            ("p", "As taxas de câmbio respondem a uma pergunta: de quanto você precisa de uma moeda para comprar outra? Mas quem define esse número? A resposta depende da moeda — há três sistemas principais."),
            ("h", "Taxas flutuantes"),
            ("p", "A maioria das principais moedas — dólar americano, euro, iene japonês e libra esterlina — **flutua livremente**. Seu valor é definido continuamente pela oferta e pela demanda no mercado global de câmbio, o maior mercado financeiro do mundo, com um volume diário negociado superior a 7 trilhões de dólares americanos."),
            ("h", "Taxas fixas (atreladas)"),
            ("p", "Algumas moedas são **atreladas** a outra. O rial saudita e o dirham dos Emirados Árabes Unidos têm paridade fixa com o dólar americano; a coroa dinamarquesa é atrelada ao euro. O banco central se compromete a comprar ou vender sua moeda para manter a taxa dentro de uma faixa estreita."),
            ("h", "Taxas administradas"),
            ("p", "Muitas moedas, como o yuan chinês, são **administradas**: o banco central permite que o mercado provoque variações, mas intervém quando a cotação sai de uma faixa considerada aceitável."),
            ("h", "De onde vêm as taxas da Fxverter"),
            ("p", "A Fxverter exibe **taxas de referência**: cotações de fim de dia publicadas pelo Banco Central Europeu e por outras fontes públicas. Elas são ótimas para comparar, planejar e estimar — mas bancos e bandeiras de cartão acrescentam as próprias margens e tarifas, então a cotação que você efetivamente paga por uma transferência será diferente. Confirme sempre a taxa final com seu banco ou provedor."),
        ],
    },
    "inflation-and-exchange-rates": {
        "title": "Inflação e taxas de câmbio — como se relacionam",
        "description": "A inflação alta corrói o valor de uma moeda ao longo dos anos, e os bancos centrais combatem esse processo com taxas de juros. Entender essas duas forças explica a maioria das histórias cambiais de longo prazo.",
        "sections": [
            ("p", "Pergunte por que uma moeda perdeu força ao longo de uma década e a resposta geralmente começa pela inflação. Pergunte por que ela se valorizou neste mês e a resposta geralmente começa pelas taxas de juros. As duas forças estão ligadas — veja como esse mecanismo funciona."),
            ("h", "A inflação corrói uma moeda lentamente"),
            ("p", "No fundo, uma moeda representa o direito de comprar bens e serviços de uma economia. Se os preços dobram enquanto a quantidade de dinheiro permanece igual, cada unidade desse dinheiro compra metade do que comprava — e investidores estrangeiros pagarão proporcionalmente menos por ela. Ao longo dos anos, um país com **inflação persistentemente mais alta que a de seus parceiros comerciais** tende a ver sua moeda se desvalorizar em relação às deles."),
            ("p", "Os exemplos mais claros são as moedas que mais perderam valor ao longo de uma geração: a lira turca, o peso argentino e o bolívar venezuelano. Em cada caso, anos de emissão de moeda e inflação de dois dígitos terminaram como previa a lógica do poder de compra."),
            ("h", "Paridade do poder de compra: a âncora de longo prazo"),
            ("p", "A ideia por trás disso é chamada **paridade do poder de compra (PPC)**: no longo prazo, as taxas de câmbio se ajustam para que a mesma cesta de produtos custe aproximadamente o mesmo em todos os lugares. Se uma cesta custa 100 unidades no seu país e, depois da conversão, a mesma cesta custa o dobro no exterior, a taxa de câmbio está desalinhada — e, com o tempo, a cotação ou os preços se movem para reduzir essa diferença."),
            ("p", "A PPC não serve para prever a próxima semana. É surpreendentemente útil para avaliar se uma moeda está **claramente esticada** depois de uma grande variação — por isso economistas continuam publicando comparações no estilo do Índice Big Mac."),
            ("h", "Taxas de juros: a alavanca rápida"),
            ("p", "Os bancos centrais combatem a inflação aumentando as taxas de juros. Juros mais altos tornam depósitos e títulos naquela moeda mais atraentes, atraem capital estrangeiro e dão sustentação à taxa de câmbio — pelo menos enquanto os investidores acreditarem que o banco central manterá o rumo."),
            ("p", "É por isso que o padrão se repete no mundo todo: o banco central **eleva os juros com força**, e a moeda se valoriza; o banco **corta os juros ou perde credibilidade**, e a moeda se desvaloriza. A lira turca caiu durante uma experiência de redução dos juros em meio à inflação crescente e se recuperou quando a política voltou à ortodoxia. O real brasileiro ganha força com algumas das maiores taxas de juros reais do mundo."),
            ("h", "O que importa são os juros reais"),
            ("p", "O que movimenta o dinheiro não é a taxa nominal, mas a **taxa real**: a taxa básica de juros menos a inflação. Uma taxa básica de 40% com inflação de 50% ainda é profundamente negativa — o dinheiro mantido ali perde poder de compra todos os anos; é exatamente por isso que os residentes preferem dólares. Já uma taxa de 5% com inflação de 2% é realmente atraente."),
            ("h", "O que isso significa para você"),
            ("li", "**Viajantes:** destinos com inflação alta ficam mais baratos ao longo do tempo quando medidos em moedas fortes — mas confira as cotações atuais, pois o mercado geralmente já antecipou parte dessa história"),
            ("li", "**Quem poupa:** manter as economias em uma moeda com inflação alta e juros reais negativos é uma perda gradual, mesmo que a conta “pague juros”"),
            ("li", "**Empresas:** em contratos longos, cobre em moeda forte ou indexe os valores à inflação quando a moeda da outra parte tiver problemas de credibilidade"),
            ("p", "A inflação é a maré lenta que determina onde as moedas vão parar. As taxas de juros são as ondas que determinam para onde elas vão neste mês."),
        ],
    },
    "mid-market-rate": {
        "title": "O que é a taxa média de mercado?",
        "description": "A taxa média de mercado é o ponto intermediário entre o que os compradores pagam e o que os vendedores aceitam — e a referência com a qual você deve comparar transferências de dinheiro.",
        "sections": [
            ("p", "Quando você envia dinheiro para o exterior ou compra moeda estrangeira, os provedores oferecem uma cotação com acréscimo. Para saber se a oferta é justa, você precisa de um número: a **taxa média de mercado**."),
            ("h", "Definição"),
            ("p", "A taxa média de mercado é o ponto intermediário entre o **preço de compra (bid)** — o que os compradores estão dispostos a pagar naquele momento — e o **preço de venda (ask)** — o que os vendedores aceitam — no mercado global de moedas. É o retrato mais justo do valor de uma moeda em um único momento: a mesma taxa que aparece na Fxverter, no Google e em sites de notícias financeiras."),
            ("h", "Por que a taxa do seu banco é pior"),
            ("p", "Bancos e serviços de transferência geralmente escondem uma margem **dentro** da taxa de câmbio — muitas vezes de 1% a 4%, e às vezes bem mais — e ainda acrescentam tarifas. Uma margem de 3% em uma transferência de 10.000 unidades custa silenciosamente 300 unidades, normalmente mais do que qualquer “tarifa” declarada."),
            ("h", "Como usar essa taxa"),
            ("li", "Compare a cotação oferecida com a taxa da Fxverter para o mesmo par de moedas"),
            ("li", "Peça ao provedor o **custo total na moeda recebida**, incluindo todas as tarifas e margens"),
            ("li", "Pequenas diferenças são normais — os provedores precisam de alguma margem —, mas diferenças de vários pontos percentuais justificam pesquisar outras opções"),
            ("h", "Limitações que você deve conhecer"),
            ("p", "Taxas médias de mercado são taxas de referência, geralmente atualizadas uma vez ou algumas vezes por dia, e não cotações de negociação em tempo real. A taxa exata de uma transferência real será um pouco diferente; a taxa média de mercado é uma referência, não o valor contratado."),
        ],
    },
    "reading-exchange-rate-quotes": {
        "title": "Como interpretar cotações de câmbio",
        "description": "Moeda-base, moeda de cotação, pips e spreads — um guia de cinco minutos para entender o que uma cotação de câmbio realmente informa.",
        "sections": [
            ("p", "Uma cotação de câmbio parece simples — **EUR/USD 1,08** —, mas reúne várias informações em um único número. Veja como interpretá-la e identificar quando uma cotação esconde um custo."),
            ("h", "Qual moeda é qual"),
            ("p", "Em qualquer par, a **moeda-base** vem primeiro e a **moeda de cotação**, em segundo. O número informa quanto da moeda de cotação se compra com uma unidade da moeda-base:"),
            ("li", "**EUR/USD 1,08** → 1 euro compra 1,08 dólar americano"),
            ("li", "**USD/JPY 150,00** → 1 dólar americano compra 150 ienes japoneses"),
            ("p", "A ordem segue uma convenção de mercado, não é uma escolha: alguns pares sempre aparecem de um jeito (EUR/USD, GBP/USD) e outros, na ordem inversa (USD/JPY, USD/CAD). Ao consultar uma cotação, confira qual moeda é a base — caso contrário, você pode interpretar 150 ienes como 150 dólares."),
            ("h", "O número principal e os pips"),
            ("p", "Em EUR/USD 1,0850, o **número principal** é 1,08 e os dois últimos algarismos — os pips — são 50. A maioria dos pares é cotada com quatro ou cinco casas decimais; os pares com iene, com duas ou três. As variações diárias dos principais pares costumam ser de apenas algumas dezenas de pips, por isso uma mudança de 1% em um dia é considerada grande."),
            ("h", "Por que você vê uma cotação e o mercado vê duas"),
            ("p", "Os mercados profissionais cotam **dois preços**: o bid (o que os compradores pagam) e o ask (o que os vendedores aceitam). A diferença entre eles é o **spread** — o próprio custo de transação do mercado. No EUR/USD, pode ser uma fração de pip; em um par exótico, pode ser centenas de vezes maior."),
            ("p", "Quando você troca dinheiro como cliente, geralmente vê **uma única cotação**. Ela é a taxa média de mercado acrescida da margem do provedor. Quanto maior a diferença entre a taxa média de mercado e a cotação oferecida, maior o custo efetivo da conversão — independentemente do que aparece na coluna de tarifas."),
            ("h", "Taxas cruzadas: por que o dólar aparece em toda parte"),
            ("p", "A maioria dos pares de moedas não é negociada diretamente. Se você quiser converter coroas dinamarquesas em reais, o mercado calcula a operação combinando DKK→USD e USD→BRL. É por isso que as taxas de referência baseadas no dólar são úteis para todo tipo de conversão e que alguns pares incomuns têm spreads mais amplos — você paga por duas conversões mesmo quando só vê uma."),
            ("h", "Um procedimento prático para interpretar cotações"),
            ("li", "1. Encontre a **taxa média de mercado** do seu par (Fxverter, Google ou outra fonte de referência)"),
            ("li", "2. Consulte o valor **total a receber** informado pelo provedor para a sua transferência"),
            ("li", "3. Divida o valor recebido pelo que a taxa média de mercado geraria — a diferença é o custo real"),
            ("li", "4. Repita com outro provedor; quem vence é definido pela diferença, não pela tarifa"),
            ("p", "Quando você aprende a interpretar uma cotação dessa forma, a propaganda de “sem comissão” deixa de funcionar — porque você já não está olhando apenas para o número que querem que você veja."),
        ],
    },
    "send-money-abroad": {
        "title": "Como enviar dinheiro para o exterior sem pagar demais",
        "description": "Os bancos embutem de 1% a 4% na taxa de câmbio. Veja como comparar em três minutos o custo total de uma transferência internacional e evitar pagar essa margem.",
        "sections": [
            ("p", "Quando você envia dinheiro para outro país, raramente paga apenas a “tarifa” que vê na tela. O custo real fica escondido na taxa de câmbio — e geralmente representa a maior parte da conta."),
            ("h", "O custo oculto: a margem na cotação"),
            ("p", "Bancos e muitos serviços de transferência oferecem uma cotação pior que a taxa média de mercado (o ponto médio entre os preços de compra e venda que você vê na Fxverter ou no Google). A diferença costuma ser uma margem de **1% a 4%** — às vezes bem maior em rotas menos comuns. Em uma transferência de 10.000 unidades, uma margem de 3% custa silenciosamente 300 unidades, geralmente mais do que qualquer tarifa anunciada."),
            ("h", "Compare o total recebido, não a tarifa"),
            ("p", "O único número que importa é **quanto chega ao destino**. Para cada provedor, calcule:"),
            ("li", "A tarifa cobrada, mais"),
            ("li", "A diferença entre a cotação oferecida e a taxa média de mercado"),
            ("p", "Considere ambos os valores na moeda de destino para chegar ao custo real. Um provedor “sem tarifa” com margem de 4% é muito mais caro do que outro que cobra US$ 5 de forma explícita e aplica uma margem de 0,3%."),
            ("h", "Três minutos de pesquisa"),
            ("li", "Confira a **taxa média de mercado** do seu par imediatamente antes de enviar — as cotações mudam"),
            ("li", "Peça ao provedor o **valor total na moeda do destinatário**, incluindo todos os custos"),
            ("li", "Compare pelo menos dois provedores no mesmo dia; as margens variam muito de uma rota para outra"),
            ("li", "Para valores altos, pergunte se há uma **faixa de cotação melhor** — muitos serviços negociam acima de determinados valores"),
            ("li", "Fique atento a **cotações promocionais** válidas apenas para a primeira transferência"),
            ("h", "Momento e método"),
            ("p", "Na maioria das rotas de varejo, serviços especializados em transferências custam menos do que transferências bancárias internacionais, e a velocidade é parecida (de alguns minutos a um dia). Evite trocar dinheiro em espécie no aeroporto — as margens estão entre as piores do setor. Se a transferência não for urgente, acompanhar a cotação por alguns dias e configurar um alerta para um nível favorável pode valer mais do que qualquer desconto na tarifa."),
            ("h", "A regra em uma linha"),
            ("p", "**Ignore a tarifa e compare o valor recebido.** Todo o resto é propaganda."),
        ],
    },
    "travel-money": {
        "title": "Dinheiro em viagens — espécie, cartão ou câmbio?",
        "description": "Quanto dinheiro em espécie levar para o exterior, qual cartão usar e por que “pagar na sua própria moeda” é o botão mais caro de qualquer maquininha.",
        "sections": [
            ("p", "Toda viagem começa com a mesma dúvida: quanto dinheiro trocar antes de sair e como pagar quando chegar. A resposta depende menos do destino do que de três decisões que você toma na maquininha."),
            ("h", "A regra de ouro em toda maquininha"),
            ("p", "Quando uma maquininha ou um caixa eletrônico oferece cobrar **na sua moeda de origem em vez da moeda local**, recuse sempre. Isso se chama conversão dinâmica de moeda (DCC) e esconde uma margem de 3% a 10% sob a aparência de conveniência. Escolha **sempre pagar na moeda local** e deixe seu banco fazer a conversão — mesmo as cotações bancárias comuns são melhores que a DCC quase todas as vezes."),
            ("h", "Quanto levar em espécie"),
            ("li", "**Destinos que usam muito dinheiro vivo:** Japão, Alemanha, Sudeste Asiático fora das grandes cidades, mercados e áreas rurais em qualquer lugar"),
            ("li", "**Destinos que priorizam cartões:** países nórdicos, Reino Unido, China (pagamentos por celular) e a maior parte das áreas urbanas da América do Norte"),
            ("li", "Um valor razoável como padrão: leve em espécie local o equivalente a **um ou dois dias de gastos** e complete o saldo em caixas eletrônicos, em vez de trocar uma grande quantia de uma só vez"),
            ("h", "Estratégia para usar caixas eletrônicos"),
            ("p", "Os balcões de câmbio dos aeroportos têm algumas das piores margens do setor — use-os apenas em emergências. Sacar em caixas de bancos no destino geralmente oferece uma cotação próxima da taxa média de mercado. A estratégia habitual: saque o suficiente para alguns dias de cada vez, para diluir as tarifas fixas, e recuse a oferta da máquina para fazer a conversão (a mesma armadilha da DCC)."),
            ("h", "Cartões que funcionam bem em viagens"),
            ("li", "Cartões **sem tarifa por transação internacional** economizam a sobretaxa habitual de 1% a 3% em cada compra"),
            ("li", "**Cartões pré-pagos para viagem** fixam uma cotação — são úteis para controlar o orçamento, mas você perde a vantagem se a cotação mudar a seu favor"),
            ("li", "**Carteiras digitais** (Apple Pay, Google Pay) seguem as condições do seu cartão e são aceitas em mais lugares do que muitos viajantes imaginam"),
            ("h", "Mantenha uma pequena reserva em moeda forte"),
            ("p", "Um pequeno valor guardado de **dólares americanos ou euros** é uma reserva universal: pode ser trocado em qualquer país e é a saída clássica quando os cartões não funcionam, os caixas ficam fora do ar ou a moeda local entra em crise. Provavelmente você nunca vai precisar dele — e é exatamente para isso que serve uma reserva."),
            ("h", "Lista de conferência"),
            ("li", "1. Avise seu banco ou, melhor ainda, use um cartão sem tarifa por transação internacional"),
            ("li", "2. Leve uma pequena quantia em dinheiro do seu país para as primeiras horas, não o orçamento inteiro"),
            ("li", "3. Faça saques locais em caixas de bancos e recuse ofertas de conversão"),
            ("li", "4. Pague sempre na moeda local"),
            ("li", "5. Mantenha uma reserva em dólares/euros separada da carteira"),
            ("p", "Siga essas cinco recomendações e você conseguirá uma cotação melhor do que a da maioria dos viajantes, sem precisar voltar a pensar em dinheiro até o voo de volta."),
        ],
    },
    "when-to-exchange": {
        "title": "Qual é o melhor momento para trocar moeda?",
        "description": "Ninguém consegue prever as taxas de câmbio com confiabilidade — mas você pode evitar os piores momentos, usar alertas em vez de adivinhar e dividir conversões grandes para obter uma cotação média.",
        "sections": [
            ("p", "Vamos começar pela resposta sincera: **ninguém prevê taxas de câmbio com confiabilidade** — nem bancos, nem analistas, nem algoritmos. Operadores profissionais de câmbio, com dados melhores do que os nossos, acertam pouco mais do que uma moeda lançada ao ar em períodos curtos. Portanto, o objetivo não é adivinhar o momento perfeito, mas evitar os piores e deixar que mecanismos simples façam o resto."),
            ("h", "O que realmente movimenta as cotações no curto prazo"),
            ("p", "As variações diárias são impulsionadas por notícias: decisões de bancos centrais, dados de inflação, números de emprego e acontecimentos políticos. Esses eventos são programados ou inesperados, e o mercado reage em segundos. Quando uma manchete sobre um “dólar forte” chega até você, a variação geralmente já aconteceu."),
            ("p", "Ao longo de semanas e meses, as cotações variam com as diferenças entre as taxas de juros e com o ritmo da economia. Em períodos de anos, as moedas tendem a voltar a níveis justificados pelas respectivas economias — mas “anos” não é um horizonte de planejamento para uma viagem ou uma fatura."),
            ("h", "Use alertas em vez de previsões"),
            ("p", "A maioria dos aplicativos bancários e de transferência oferece **alertas de cotação**: você define um nível que consideraria bom e recebe uma notificação quando o mercado o atinge. Isso substitui palpites por uma regra. Se a cotação nunca chegar ao nível desejado, você ainda fará a conversão — apenas sem contar com a sorte. Se chegar, você terá um resultado um pouco melhor do que a média dos usuários do mercado, e essa diferença se acumula ao longo de um ano de transferências."),
            ("h", "Divida as conversões grandes"),
            ("p", "Se você vai movimentar uma quantia grande — mensalidades, o sinal de um imóvel ou um pagamento empresarial —, considere **dividi-la em partes** ao longo de dias ou semanas. Você não vai acertar o topo nem o fundo, mas obterá a **média** do período, que costuma ficar próxima de uma cotação justa e elimina o risco de converter tudo no pior dia do mês."),
            ("h", "Os piores momentos para converter"),
            ("li", "**Guichês de aeroporto** — as piores margens do setor, a qualquer hora"),
            ("li", "**Pressão de prazos de última hora** — se você precisa converter hoje, não tem poder para negociar"),
            ("li", "**Picos de movimento em feriados** — a demanda aumenta perto dos principais feriados do país de destino"),
            ("li", "**Logo após uma manchete dramática** — a volatilidade está no auge justamente quando todos estão reagindo; os spreads aumentam"),
            ("h", "Para empresas: pare de tentar acertar o momento e comece a se proteger"),
            ("p", "Empresas com faturas recorrentes em moeda estrangeira não deveriam tentar acertar o momento da conversão. As ferramentas padrão são simples: fature na sua própria moeda quando possível, mantenha um saldo multimoeda para receber e pagar naturalmente e, para pagamentos grandes e previsíveis, pergunte ao banco sobre um **contrato a termo** — ele fixa a cotação de hoje para uma data futura, transformando um custo imprevisível em um valor conhecido."),
            ("h", "Em resumo"),
            ("p", "Configure um alerta, evite os momentos sabidamente ruins, divida os valores grandes e siga com a sua vida. O tempo que você deixa de gastar olhando gráficos vale mais do que a fração de um ponto percentual que talvez conseguisse capturar acompanhando-os."),
        ],
    },
}
