GUIDE_L10N = {
    "exchange-rate-risk": {
        "title": "Riesgo cambiario: guía para autónomos y pequeñas empresas",
        "description": "Si facturas o pagas en moneda extranjera, el riesgo cambiario ya forma parte de tu negocio. Aquí te explicamos cómo detectarlo, medirlo y reducirlo sin convertirte en operador de divisas.",
        "sections": [
            ("p", "Si un cliente te paga en una moneda que no usas, o tu proveedor te factura en una moneda que no ganas, estás expuesto al **riesgo cambiario**, lo hayas pensado o no. Una variación del 5 % en tu contra puede borrar por completo el margen de un proyecto. La buena noticia: no hace falta convertirse en operador de divisas para controlar el riesgo; basta con adoptar unos cuantos hábitos."),
            ("h", "Primero, identifica dónde está el riesgo"),
            ("p", "Traza dos líneas: lo que **ingresas** y lo que **gastas**, cada una en su moneda."),
            ("li", "Un autónomo que factura a clientes estadounidenses pero vive con euros gana dólares y gasta euros: cada factura está expuesta al tipo de cambio hasta que se cobra y se convierte."),
            ("li", "Un importador que compra en Asia y vende en su país hace lo contrario: primero asume un coste en moneda extranjera."),
            ("li", "Una empresa de software como servicio que cobra en todo el mundo tiene una exposición mixta que solo se compensa si las monedas están realmente diversificadas."),
            ("p", "La diferencia entre esas dos líneas —lo que tienes que convertir, en qué dirección y cuándo— es tu exposición. Si es pequeña y poco frecuente, esta guía se lee en diez minutos. Si es grande y recurrente, los hábitos que siguen se amortizan rápidamente."),
            ("h", "Hábito 1: factura en tu propia moneda cuando puedas"),
            ("p", "La forma más sencilla de reducir el riesgo es convertirlo en un problema del **cliente**: fija el precio en tu moneda y deja claro que el importe está establecido en ella. Muchos clientes lo aceptan sin objeciones; algunos se resisten, y ofrecer un descuento puede salir más barato que soportar un año de fluctuaciones cambiarias. Los clientes grandes suelen preferir su propia moneda de todos modos; ahí es cuando importan los demás hábitos."),
            ("h", "Hábito 2: convierte pronto y siguiendo una regla"),
            ("p", "Si recibes moneda extranjera y la guardas «hasta que el tipo de cambio parezca bueno», estás especulando con ingresos que quizá necesites. Una regla sencilla —convertir dentro de un número fijo de días desde el cobro o cuando el tipo alcance un nivel que aceptarías— convierte la suerte en un proceso. La mayoría de las aplicaciones bancarias y de transferencias permiten configurar alertas de tipo de cambio precisamente para esto."),
            ("h", "Hábito 3: usa un saldo multidivisa"),
            ("p", "Las cuentas empresariales modernas permiten **mantener** divisas en vez de convertirlas automáticamente. Si pagas a algunos proveedores o contratistas en la misma moneda en que facturas, compensar esos cobros y pagos reduce el riesgo de forma natural: sin conversión, sin coste y sin tener que decidir."),
            ("h", "Hábito 4: divide las conversiones grandes"),
            ("p", "Para un pago único de importe elevado —equipos, un depósito o un impuesto—, dividir la conversión en dos o tres partes a lo largo de varios días promedia el tipo de cambio y evita convertirlo todo en el peor día del mes. Para pagos futuros realmente grandes y previsibles, los bancos ofrecen **contratos a plazo** que fijan el tipo de hoy para una fecha situada varios meses adelante; la contrapartida es renunciar a cualquier evolución favorable."),
            ("h", "Hábito 5: fija los precios con un margen de seguridad"),
            ("p", "Si tienes que cotizar en la moneda del cliente, añade un margen por si el tipo cambia entre la cotización y el pago, e indica que el precio es válido durante un plazo limitado. Los autónomos que especifican «válido durante 30 días» convierten discretamente un riesgo conocido en uno acotado."),
            ("h", "Qué no hacer"),
            ("li", "No operes con divisas «por tu cuenta» usando dinero que necesita tu negocio: eso ya no es cobertura."),
            ("li", "No ignores el **coste** de conversión mientras gestionas el tipo de cambio: un diferencial del 3 % se come más que la mayoría de las ganancias por acertar el momento."),
            ("li", "No dejes el riesgo sin medir: anota cuánto ingresas y gastas al año en cada moneda y calcula la diferencia."),
            ("p", "Si gestionas así los tipos de cambio, dejarán de ser un billete de lotería pegado a tus ingresos y pasarán a ser lo que deberían: una partida que entiendes y cuyo coste controlas."),
        ],
    },
    "hidden-currency-fees": {
        "title": "Comisiones ocultas al cambiar divisas (y cómo evitarlas)",
        "description": "La comisión que aparece en pantalla rara vez refleja el coste total. Los diferenciales, la conversión dinámica de divisa, las comisiones de cajero y los cargos de intermediarios se llevan su parte. Te explicamos cómo detectarlos y quedarte con la diferencia.",
        "sections": [
            ("p", "La comisión que ves en pantalla rara vez es la que acabas pagando. Los costes de conversión de divisas se presentan de cuatro formas distintas, y la mayor ni siquiera aparece como comisión."),
            ("h", "1. El margen sobre el tipo de cambio"),
            ("p", "Cuando un proveedor te ofrece un tipo un 2 % peor que el tipo medio del mercado, ese 2 % es una comisión, aunque no lo parezca. En una transferencia de 5.000 unidades, un margen del 2 % cuesta 100 unidades mientras el anuncio de «cero comisiones» se lleva los aplausos. Es el mayor coste de la mayoría de las conversiones, y la única forma de verlo es comparar el tipo ofrecido con el **tipo medio de referencia del mercado** antes de aceptar."),
            ("h", "2. Conversión dinámica de divisa (DCC)"),
            ("p", "El botón más caro cuando viajas: un terminal de pago o cajero en el extranjero te ofrece cobrarte **en tu moneda de origen** y, con ello, convertir al tipo que él mismo fija, normalmente entre un 3 % y un 10 % peor que el de tu banco. Elige siempre pagar en la **moneda local** y deja que tu banco haga la conversión."),
            ("h", "3. Comisiones de cajero y de tarjeta"),
            ("li", "Los operadores de cajeros extranjeros suelen cobrar una **comisión fija** por retirada."),
            ("li", "Tu propio banco puede añadir un **recargo por transacción en moneda extranjera**, a menudo del 1 % al 3 %."),
            ("li", "Retira importes mayores con menos frecuencia para repartir mejor las comisiones fijas y prefiere los **cajeros vinculados a bancos** en lugar de los cajeros independientes de las tiendas."),
            ("h", "4. Comisiones por transferencias y de intermediarios"),
            ("p", "Las transferencias bancarias internacionales pueden pasar por uno o dos **bancos intermediarios**, cada uno de los cuales descuenta su propia comisión antes de que llegue el dinero. Así, el destinatario recibe bastante menos de lo que enviaste y no hay ningún concepto que explique dónde fue a parar la diferencia. Los servicios especializados en transferencias publican sus comisiones por adelantado; precisamente por eso suelen ser más baratos."),
            ("h", "La comparación que nunca engaña"),
            ("p", "No te fijes en las comisiones anunciadas ni en los tipos destacados. Para cualquier proveedor, una pregunta lo decide todo:"),
            ("p", "**Si envío X hoy, ¿cuánto llega exactamente, en la moneda del destinatario y después de descontarlo todo?**"),
            ("p", "Pide esa cifra a dos o tres proveedores el mismo día y elige la más alta. Los tipos cambian a diario, así que repite la comparación cuando vuelvas a enviar dinero: el proveedor más barato el año pasado no necesariamente lo será ahora."),
            ("h", "Lista rápida"),
            ("li", "Compara primero el tipo ofrecido con el tipo medio del mercado."),
            ("li", "En el extranjero, paga siempre en moneda local y rechaza las ofertas de conversión."),
            ("li", "Agrupa las retiradas de cajero para repartir las comisiones fijas."),
            ("li", "Prefiere proveedores que indiquen por adelantado el «importe total que recibirá» el destinatario."),
            ("li", "Vuelve a comparar antes de cada transferencia, no una vez al año."),
            ("p", "Ninguno de estos pasos lleva más de unos minutos y, en conjunto, suele ahorrar entre un 2 % y un 5 % por conversión; a lo largo de un año de transferencias, es dinero de verdad."),
        ],
    },
    "how-exchange-rates-work": {
        "title": "Cómo se determinan los tipos de cambio",
        "description": "¿Quién decide cuánto vale una moneda? Una explicación sencilla de los sistemas de tipo de cambio fijo, flotante y gestionado.",
        "sections": [
            ("p", "Los tipos de cambio responden a una pregunta: ¿cuánta cantidad de una moneda necesitas para comprar una unidad de otra? Pero ¿quién fija esa cifra? Depende de la moneda: existen tres sistemas principales."),
            ("h", "Tipos de cambio flotantes"),
            ("p", "La mayoría de las principales monedas —el dólar estadounidense, el euro, el yen japonés y la libra esterlina— **flotan libremente**. Su valor se determina continuamente por la oferta y la demanda en el mercado mundial de divisas, el mayor mercado financiero del mundo, con un volumen diario de operaciones superior a los 7 billones de dólares estadounidenses."),
            ("h", "Tipos de cambio fijos (vinculados)"),
            ("p", "Algunas monedas están **vinculadas** a otra. El rial saudí y el dírham de los Emiratos Árabes Unidos mantienen un tipo fijo frente al dólar estadounidense; la corona danesa está vinculada al euro. El banco central se compromete a comprar o vender su moneda para mantener el tipo dentro de una banda estrecha."),
            ("h", "Tipos de cambio gestionados"),
            ("p", "Muchas monedas, como el yuan chino, tienen un tipo **gestionado**: el banco central permite que el mercado influya en su valor, pero interviene si el tipo se sale del intervalo aceptable."),
            ("h", "De dónde proceden los tipos de Fxverter"),
            ("p", "Fxverter muestra **tipos de referencia**: tipos de cierre publicados por el Banco Central Europeo y otras fuentes públicas. Son excelentes para comparar, planificar y hacer estimaciones, pero los bancos y las redes de tarjetas añaden sus propios márgenes y comisiones, por lo que el tipo que realmente pagas por una transferencia será distinto. Confirma siempre el tipo final con tu banco o proveedor."),
        ],
    },
    "inflation-and-exchange-rates": {
        "title": "Inflación y tipos de cambio: cómo se relacionan",
        "description": "La inflación alta erosiona una moneda con el paso de los años, y los bancos centrales la combaten con tipos de interés. Entender ambas fuerzas ayuda a explicar la mayoría de las tendencias cambiarias a largo plazo.",
        "sections": [
            ("p", "Si preguntas por qué una moneda se debilitó a lo largo de una década, la respuesta suele empezar por la inflación. Si preguntas por qué se fortaleció este mes, suele empezar por los tipos de interés. Ambas fuerzas están conectadas; así funciona el mecanismo."),
            ("h", "La inflación erosiona una moneda lentamente"),
            ("p", "En el fondo, una moneda es un derecho sobre los bienes y servicios de una economía. Si los precios se duplican mientras la cantidad de dinero sigue igual, cada unidad monetaria compra la mitad; los inversores extranjeros estarán dispuestos a pagar correspondientemente menos por ella. Con el paso de los años, un país con **una inflación persistentemente superior a la de sus socios comerciales** tiende a ver cómo su moneda se deprecia frente a las de estos."),
            ("p", "Los ejemplos más claros son las monedas que más valor han perdido en una generación: la lira turca, el peso argentino y el bolívar venezolano. En todos los casos, años de emisión de dinero e inflación de dos dígitos terminaron como predecía la lógica del poder adquisitivo."),
            ("h", "Paridad del poder adquisitivo: el ancla lenta"),
            ("p", "La idea que subyace a esto se llama **paridad del poder adquisitivo (PPA)**: a largo plazo, los tipos de cambio se ajustan para que una misma cesta de bienes cueste aproximadamente lo mismo en todas partes. Si una cesta cuesta 100 unidades en tu país y, tras convertir la moneda, esa misma cesta cuesta el doble en el extranjero, el tipo de cambio está desajustado; con el tiempo, cambiará el tipo o cambiarán los precios para cerrar la brecha."),
            ("p", "La PPA no sirve para predecir lo que ocurrirá la semana que viene. Es sorprendentemente útil para determinar si una moneda está **claramente sobrevalorada o infravalorada** tras un gran movimiento; por eso los economistas siguen publicando comparaciones al estilo del índice Big Mac."),
            ("h", "Tipos de interés: la palanca rápida"),
            ("p", "Los bancos centrales combaten la inflación subiendo los tipos de interés. Unos tipos más altos hacen más atractivos los depósitos y bonos denominados en esa moneda, atraen capital extranjero y sostienen el tipo de cambio, al menos mientras los inversores crean que el banco central mantendrá el rumbo."),
            ("p", "Por eso el patrón se repite en todo el mundo: un banco central **sube mucho los tipos** y la moneda se fortalece; el banco **los baja o pierde credibilidad** y la moneda se debilita. La lira turca cayó durante un experimento de recortes de tipos en plena subida de la inflación y se recuperó cuando la política volvió a criterios ortodoxos. El real brasileño se beneficia de unos de los tipos de interés reales más altos del mundo."),
            ("h", "Lo que importa son los tipos reales"),
            ("p", "Lo que mueve el dinero no es el tipo nominal, sino el **tipo real**: el tipo de interés oficial menos la inflación. Un tipo oficial del 40 % con una inflación del 50 % sigue siendo profundamente negativo: el dinero depositado allí pierde poder adquisitivo cada año, que es precisamente por lo que la población local prefiere los dólares. En cambio, un tipo del 5 % con una inflación del 2 % sí resulta realmente atractivo."),
            ("h", "Qué significa esto para ti"),
            ("li", "**Viajeros:** con el tiempo, los destinos de alta inflación se abaratan medidos en monedas fuertes; aun así, consulta los tipos actuales, porque el mercado ya suele haber descontado parte de esa evolución."),
            ("li", "**Ahorradores:** mantener los ahorros en una moneda con inflación alta y tipos reales negativos supone una pérdida lenta, aunque la cuenta «pague intereses»."),
            ("li", "**Empresas:** si la moneda de la otra parte tiene problemas de credibilidad, fija los contratos largos en una moneda fuerte o indexa sus importes a la inflación."),
            ("p", "La inflación es la marea lenta que determina dónde acaban las monedas. Los tipos de interés son las olas que deciden hacia dónde se dirigen este mes."),
        ],
    },
    "mid-market-rate": {
        "title": "¿Qué es el tipo medio del mercado?",
        "description": "El tipo medio del mercado es el punto intermedio entre lo que pagan los compradores y aceptan los vendedores, y el valor de referencia con el que deberías comparar tus transferencias.",
        "sections": [
            ("p", "Cuando envías dinero al extranjero o compras moneda extranjera, los proveedores te ofrecen un tipo con recargo. Para saber si la oferta es justa, necesitas conocer una cifra: el **tipo medio del mercado**."),
            ("h", "Definición"),
            ("p", "El tipo medio del mercado es el punto medio entre el **precio comprador** (el precio al que el mercado compra la moneda base) y el **precio vendedor** (el precio al que el mercado la vende) en el mercado mundial de divisas. Es la instantánea más justa del valor de una moneda: el mismo tipo que ves en Fxverter, Google y los sitios web de noticias financieras."),
            ("h", "Por qué el tipo de tu banco es peor"),
            ("p", "Los bancos y los servicios de transferencia suelen ocultar un margen **dentro** del tipo de cambio —a menudo del 1 % al 4 %, y a veces mucho más— y además cobran comisiones. Un margen del 3 % en una transferencia de 10.000 unidades cuesta 300 unidades sin que te des cuenta, normalmente más que cualquier «comisión» declarada."),
            ("h", "Cómo utilizarlo"),
            ("li", "Compara el tipo que te ofrecen con el tipo de Fxverter para el mismo par de monedas."),
            ("li", "Pide al proveedor el **coste total en la moneda de destino**, incluidas todas las comisiones y los márgenes."),
            ("li", "Las diferencias pequeñas son normales —los proveedores necesitan cierto margen—, pero si son de varios puntos porcentuales, vale la pena comparar otras opciones."),
            ("h", "Limitaciones que debes conocer"),
            ("p", "Los tipos medios del mercado son tipos de referencia, que suelen actualizarse una vez o unas pocas veces al día; no son precios de negociación en tiempo real. El tipo exacto de una transferencia real variará ligeramente: el tipo medio del mercado sirve como referencia, no como tipo contractual."),
        ],
    },
    "reading-exchange-rate-quotes": {
        "title": "Cómo leer las cotizaciones de tipos de cambio",
        "description": "Moneda base, moneda cotizada, pips y diferenciales: una guía de cinco minutos para entender qué dice realmente una cotización de tipo de cambio.",
        "sections": [
            ("p", "Una cotización de tipo de cambio parece sencilla —**EUR/USD 1,08**—, pero concentra varios datos en una sola cifra. Así puedes interpretarla y detectar si un tipo cotizado oculta un coste."),
            ("h", "Cuál es cada moneda"),
            ("p", "En cualquier par, primero aparece la **moneda base** y después la **moneda cotizada**. La cifra indica cuánta moneda cotizada se obtiene por una unidad de la moneda base:"),
            ("li", "**EUR/USD 1,08** → 1 euro compra 1,08 dólares estadounidenses."),
            ("li", "**USD/JPY 150,00** → 1 dólar estadounidense compra 150 yenes japoneses."),
            ("p", "El orden responde a una convención del mercado, no es una elección: algunos pares siempre aparecen en un sentido (EUR/USD, GBP/USD) y otros en el inverso (USD/JPY, USD/CAD). Cuando consultes un tipo, asegúrate de saber cuál es la moneda base; de lo contrario, podrías interpretar 150 yenes como 150 dólares."),
            ("h", "La cifra principal y los pips"),
            ("p", "En EUR/USD 1,0850, la **cifra principal** es 1,08 y los dos últimos dígitos —los pips— son 50. La mayoría de los pares se cotizan con cuatro o cinco decimales, y los pares con yenes, con dos o tres. Las variaciones diarias de los principales pares suelen ser de apenas unas decenas de pips; por eso, una variación del 1 % en un día se considera grande."),
            ("h", "Por qué tú ves un tipo y el mercado ve dos"),
            ("p", "Los mercados profesionales cotizan **dos precios**: el precio comprador (el precio al que el mercado compra la moneda base) y el precio vendedor (el precio al que el mercado la vende). La diferencia entre ambos es el **diferencial**: el coste de transacción propio del mercado. En EUR/USD puede ser una fracción de pip; en un par exótico puede ser cientos de veces más amplio."),
            ("p", "Cuando cambias dinero como cliente, normalmente ves **un solo tipo**. Ese tipo es el tipo medio del mercado más el margen del proveedor. Cuanto mayor sea la diferencia entre el tipo medio del mercado y el que te ofrecen, más te cuesta realmente la conversión, independientemente de lo que indique la columna de comisiones."),
            ("h", "Tipos cruzados: por qué el dólar aparece en todas partes"),
            ("p", "La mayoría de los pares de monedas no se negocia directamente. Si quieres convertir coronas danesas a reales brasileños, el mercado calcula el tipo combinando DKK→USD y USD→BRL. Por eso los tipos de referencia basados en el dólar son útiles para todo y algunos pares poco habituales tienen diferenciales más amplios: pagas por dos conversiones aunque solo veas una."),
            ("h", "Una rutina práctica para interpretar cotizaciones"),
            ("li", "1. Busca el **tipo medio del mercado** para tu par (Fxverter, Google o cualquier fuente de referencia)."),
            ("li", "2. Averigua el **importe total que recibirá** el destinatario de tu transferencia."),
            ("li", "3. Divide el importe recibido por lo que obtendrías con el tipo medio del mercado: la diferencia es el coste real."),
            ("li", "4. Repite el cálculo con un segundo proveedor; gana quien tenga la menor diferencia, no quien cobre menos comisión."),
            ("p", "Cuando sabes interpretar una cotización así, la publicidad de «sin comisión» deja de convencerte, porque ya no te fijas en la cifra que quieren que veas."),
        ],
    },
    "send-money-abroad": {
        "title": "Cómo enviar dinero al extranjero sin pagar de más",
        "description": "Los bancos ocultan entre un 1 % y un 4 % en el tipo de cambio. Te explicamos cómo comparar en tres minutos el coste total de una transferencia internacional y quedarte con ese margen.",
        "sections": [
            ("p", "Cuando envías dinero a otro país, rara vez pagas solo la «comisión» que ves en pantalla. El coste real se oculta en el tipo de cambio y suele representar la parte más grande de la factura."),
            ("h", "El coste oculto: el margen sobre el tipo"),
            ("p", "Los bancos y muchos servicios de transferencia te ofrecen un tipo peor que el tipo medio del mercado (el punto medio entre los precios comprador y vendedor que ves en Fxverter o Google). La diferencia suele ser un margen del **1 % al 4 %**, y a veces mucho mayor en rutas exóticas. En una transferencia de 10.000 unidades, un margen del 3 % te cuesta 300 unidades sin que te des cuenta, normalmente más que cualquier comisión anunciada."),
            ("h", "Compara el importe total recibido, no la comisión"),
            ("p", "La única cifra que importa es **cuánto dinero llega**. Para cada proveedor, calcula:"),
            ("li", "La comisión que cobra, más"),
            ("li", "La diferencia entre su tipo y el tipo medio del mercado."),
            ("p", "Calcula ambos conceptos en la moneda de destino y obtendrás el coste real. Un proveedor que no cobra «comisión» pero aplica un margen del 4 % es mucho más caro que otro que cobra 5 dólares de forma visible y aplica un margen del 0,3 %."),
            ("h", "Tres minutos de comprobaciones"),
            ("li", "Consulta el **tipo medio del mercado** para tu par justo antes de enviar el dinero: los tipos cambian."),
            ("li", "Pide al proveedor el **importe total en la moneda del destinatario**, con todos los costes incluidos."),
            ("li", "Compara al menos dos proveedores el mismo día; los márgenes varían mucho según la ruta."),
            ("li", "Para importes grandes, pregunta si existe un **tramo con mejor tipo**: muchos servicios negocian a partir de ciertas cantidades."),
            ("li", "Ten cuidado con los **tipos promocionales** que solo se aplican a la primera transferencia."),
            ("h", "El momento y el método"),
            ("p", "En la mayoría de las rutas para particulares, los servicios especializados en transferencias cuestan menos que las transferencias bancarias y ofrecen una velocidad similar (de unos minutos a un día). Evita cambiar efectivo en los aeropuertos: sus márgenes son de los peores del sector. Si la transferencia no es urgente, seguir el tipo durante unos días y configurar una alerta para un nivel favorable puede compensar más que cualquier descuento en las comisiones."),
            ("h", "La regla en una línea"),
            ("p", "**Olvídate de la comisión y compara el importe recibido.** Todo lo demás es publicidad."),
        ],
    },
    "travel-money": {
        "title": "Dinero para viajar: ¿efectivo, tarjeta o cambio?",
        "description": "Cuánto efectivo llevar al extranjero, con qué tarjeta pagar y por qué «pagar en tu moneda» es el botón más caro de cualquier terminal de pago.",
        "sections": [
            ("p", "Todo viaje empieza con la misma pregunta: cuánto dinero cambiar antes de salir y con qué pagar una vez allí. La respuesta depende menos del destino que de tres decisiones que tomas en el terminal."),
            ("h", "La regla de oro ante cualquier terminal"),
            ("p", "Cuando un terminal de pago o un cajero te ofrece cobrarte **en tu moneda de origen en lugar de la moneda local**, rechaza siempre la oferta. Se llama conversión dinámica de divisa (DCC) y esconde un recargo del 3 % al 10 % tras una pantalla que parece ofrecer comodidad. Elige **pagar siempre en moneda local** y deja que tu banco haga la conversión: casi siempre, incluso un tipo bancario mediocre es mejor que el de la DCC."),
            ("h", "Cuánto efectivo llevar"),
            ("li", "**Destinos donde se usa mucho efectivo:** Japón, Alemania, el Sudeste Asiático fuera de las grandes ciudades, y mercados y zonas rurales de cualquier parte."),
            ("li", "**Destinos donde predomina la tarjeta:** los países nórdicos, el Reino Unido, China (pagos móviles) y la mayor parte de las zonas urbanas de Norteamérica."),
            ("li", "Una referencia razonable: lleva **efectivo local para uno o dos días de gastos** y repónlo en cajeros, en vez de cambiar una gran cantidad por adelantado."),
            ("h", "Cómo usar los cajeros"),
            ("p", "Las casas de cambio de los aeropuertos ofrecen los peores márgenes del sector: úsalas solo en caso de emergencia. Retirar dinero en cajeros vinculados a bancos del destino suele ofrecer un tipo cercano al tipo medio del mercado. Lo habitual es retirar de una vez el efectivo para varios días, para repartir mejor las comisiones fijas, y rechazar la oferta de conversión del cajero (la misma trampa de la DCC)."),
            ("h", "Tarjetas adecuadas para viajar"),
            ("li", "Las tarjetas **sin comisión por transacciones en moneda extranjera** evitan el recargo habitual del 1 % al 3 % en cada compra."),
            ("li", "Las **tarjetas de viaje prepago** fijan el tipo de cambio: son útiles para controlar el presupuesto, pero pierdes la ventaja si el tipo evoluciona a tu favor."),
            ("li", "Los **monederos móviles** (Apple Pay, Google Pay) aplican las condiciones de tu tarjeta y se aceptan en más lugares de los que muchos viajeros esperan."),
            ("h", "Guarda una pequeña reserva en una moneda fuerte"),
            ("p", "Un pequeño fajo de **dólares estadounidenses o euros** es un recurso de emergencia universal: se puede cambiar en todos los países del mundo y es la clásica salida cuando fallan las tarjetas, los cajeros no funcionan o una moneda local está en crisis. Probablemente no lo necesitarás; para eso sirven precisamente las reservas."),
            ("h", "Lista de comprobación"),
            ("li", "1. Avisa a tu banco o, mejor aún, usa una tarjeta sin comisiones por uso en el extranjero."),
            ("li", "2. Lleva algo de efectivo de tu país para las primeras horas, no todo el presupuesto."),
            ("li", "3. Retira dinero en cajeros de bancos locales y rechaza las ofertas de conversión."),
            ("li", "4. Paga siempre en moneda local."),
            ("li", "5. Guarda una reserva en USD/EUR en un lugar distinto de la cartera."),
            ("p", "Sigue estos cinco consejos y obtendrás un tipo mejor que el de la mayoría de los viajeros, sin tener que volver a pensar en el dinero hasta el vuelo de regreso."),
        ],
    },
    "when-to-exchange": {
        "title": "¿Cuándo es el mejor momento para cambiar divisas?",
        "description": "Nadie puede predecir los tipos de cambio de forma fiable, pero puedes evitar los peores momentos, usar alertas en vez de hacer conjeturas y dividir las conversiones grandes para promediar el tipo.",
        "sections": [
            ("p", "Empecemos por la respuesta sincera: **nadie predice los tipos de cambio de forma fiable**; ni los bancos, ni los analistas ni los algoritmos. Los operadores profesionales de divisas, con mejores datos que cualquiera de nosotros, apenas aciertan más que lanzando una moneda al aire en horizontes cortos. Por tanto, el objetivo no es adivinar el momento perfecto, sino evitar los peores y dejar que unos mecanismos sencillos hagan el resto."),
            ("h", "Qué mueve realmente los tipos a corto plazo"),
            ("p", "Las variaciones diarias las provocan las noticias: decisiones de los bancos centrales, datos de inflación, cifras de empleo y acontecimientos políticos. Algunas se anuncian con antelación y otras son inesperadas; el mercado reacciona en cuestión de segundos. Cuando te llega un titular sobre un «dólar fuerte», el movimiento normalmente ya se ha producido."),
            ("p", "A lo largo de semanas y meses, los tipos fluctúan con las diferencias entre los tipos de interés y el impulso económico. A lo largo de los años, las monedas tienden a volver a valores justificados por sus economías; pero «años» no es un horizonte de planificación para un viaje o una factura."),
            ("h", "Usa alertas en lugar de predicciones"),
            ("p", "La mayoría de las aplicaciones bancarias y de transferencias ofrecen **alertas de tipo de cambio**: estableces el nivel que considerarías favorable y recibes una notificación cuando el mercado lo alcanza. Así sustituyes las conjeturas por una regla. Si el tipo nunca llega a ese nivel, aun así habrás hecho la conversión, solo que sin ese golpe de suerte. Si lo alcanza, habrás conseguido un resultado ligeramente mejor que el del usuario medio del mercado; una ventaja que se acumula a lo largo de un año de transferencias."),
            ("h", "Divide las conversiones grandes"),
            ("p", "Si vas a mover una cantidad grande —la matrícula, la entrada para una vivienda o un pago empresarial—, considera **dividirla en varias partes** a lo largo de días o semanas. No alcanzarás el máximo ni el mínimo, pero obtendrás el **promedio** del periodo, que suele acercarse a un tipo justo y elimina el riesgo de convertirlo todo en el peor día del mes."),
            ("h", "Los peores momentos para cambiar"),
            ("li", "**Mostradores de aeropuerto:** ofrecen los peores márgenes del sector a cualquier hora."),
            ("li", "**La presión de una fecha límite de última hora:** si tienes que convertir hoy, no tienes ningún poder de negociación."),
            ("li", "**Las prisas de las vacaciones:** la demanda aumenta durante las principales fiestas del país de destino."),
            ("li", "**Justo después de un titular impactante:** la volatilidad es máxima cuando todo el mundo reacciona y los diferenciales se amplían."),
            ("h", "Para las empresas: deja de intentar acertar el momento y empieza a cubrirte"),
            ("p", "Las empresas que reciben facturas recurrentes en moneda extranjera no deberían intentar acertar el momento. Las herramientas habituales son sencillas: factura en tu propia moneda cuando sea posible, mantén un saldo multidivisa para cobrar y pagar de forma natural y, para pagos grandes y previsibles, pregunta a tu banco por un **contrato a plazo**. Este fija el tipo de hoy para una fecha futura y convierte un coste imprevisible en uno conocido."),
            ("h", "En resumen"),
            ("p", "Configura una alerta, evita los momentos que sabes que son malos, divide los importes grandes y sigue con tu vida. El tiempo que no pasas mirando gráficos vale más que la fracción de punto porcentual que quizá ganarías vigilándolos."),
        ],
    },
}
