# Footer support-link label per language (shown next to ♥ on every page)
SUPPORT_LABEL = {
    "en": "Support", "tr": "Destek", "de": "Unterstützen", "fr": "Soutenir",
    "es": "Apoyar", "pt": "Apoiar", "ru": "Поддержать", "zh": "支持",
    "ja": "支援する", "ko": "지원하기", "ar": "ادعم", "hi": "सहयोग करें",
    "id": "Dukung", "ms": "Sokong", "tl": "Suportahan", "it": "Supporta",
    "nl": "Steun", "pl": "Wesprzyj", "uk": "Підтримати", "sv": "Stöd",
    "th": "สนับสนุน", "lo": "ສະໜັບສະໜູນ", "vi": "Ủng hộ", "el": "Υποστήριξη",
    "bn": "সমর্থন", "fa": "حمایت", "cs": "Podpořit", "ro": "Susține", "da": "Støt",
}

UI = {
 "en": {
        "privacy":"Privacy: this website uses no cookies and collects no personal data. Anonymous, cookie-free visit statistics (page views and country) may be collected to improve the tool.",
        "favLabel":"★ Saved pairs",
        "save":"Save this pair",
        "saved":"Saved",
        "copy":"Copy result",
        "copied":"Copied!",
        "themeAuto":"Theme: auto",
        "themeLight":"Theme: light",
        "themeDark":"Theme: dark",
        "supportLabel":"Support",
        "supportTitle":"Support Fxverter",
        "share":"Share",
        "shared":"Link copied!",
        "feedback":"Feedback",
        "fbPlaceholder":"Your message…",
        "fbSend":"Send feedback",
        "fbOk":"✓ Feedback sent — thank you!",
        "fbEmpty":"Please write a message first.",
        "fbFail":"Sending failed — please try again or email us directly.",
        "curLink":"Browse all currencies",
        "guideLink":"Exchange-rate guides",
        "install":"Install app",
        "instTitle":"Install Fxverter",
        "instDesc":"Add to home screen for quick access — works offline.",
        "instBtn":"Install",
        "instLater":"Not now",
        "instIos":"Tap the Share button, then choose “Add to Home Screen”.",
        "nearHigh":"Rate near {days}-day high",
        "nearLow":"Rate near {days}-day low",
 },
 "tr": {
        "privacy":"Gizlilik: bu web sitesi çerez kullanmaz ve kişisel veri toplamaz. Aracı geliştirmek için anonim, çerezsiz ziyaret istatistikleri (sayfa görüntüleme ve ülke) toplanabilir.",
        "favLabel":"★ Kayıtlı çiftler",
        "save":"Bu çifti kaydet",
        "saved":"Kaydedildi",
        "copy":"Sonucu kopyala",
        "copied":"Kopyalandı!",
        "themeAuto":"Tema: otomatik",
        "themeLight":"Tema: açık",
        "themeDark":"Tema: koyu",
        "supportLabel":"Destek",
        "supportTitle":"Fxverter'i destekle",
        "share":"Paylaş",
        "shared":"Bağlantı kopyalandı!",
        "feedback":"Geri bildirim",
        "fbPlaceholder":"Mesajınız…",
        "fbSend":"Geri bildirim gönder",
        "fbOk":"✓ Geri bildirim gönderildi — teşekkürler!",
        "fbEmpty":"Lütfen önce bir mesaj yazın.",
        "fbFail":"Gönderilemedi — lütfen tekrar deneyin veya doğrudan e-posta gönderin.",
        "curLink":"Tüm para birimlerine göz at",
        "guideLink":"Döviz kuru rehberleri",
        "install":"Uygulamayı yükle",
        "instTitle":"Fxverter’i yükle",
        "instDesc":"Hızlı erişim için ana ekrana ekle — çevrimdışı da çalışır.",
        "instBtn":"Yükle",
        "instLater":"Şimdi değil",
        "instIos":"Paylaş düğmesine dokunun, sonra “Ana Ekrana Ekle”yi seçin.",
        "nearHigh":"Kur {days} günlük zirveye yakın",
        "nearLow":"Kur {days} günlük dipe yakın",
 },
 "de": {
        "privacy":"Datenschutz: Diese Website verwendet keine Cookies und erhebt keine personenbezogenen Daten. Zur Verbesserung des Tools können anonyme, cookiefreie Besuchsstatistiken (Seitenaufrufe und Land) erhoben werden.",
        "favLabel":"★ Gespeicherte Paare",
        "save":"Dieses Paar speichern",
        "saved":"Gespeichert",
        "copy":"Ergebnis kopieren",
        "copied":"Kopiert!",
        "themeAuto":"Design: automatisch",
        "themeLight":"Design: hell",
        "themeDark":"Design: dunkel",
        "supportLabel":"Unterstützen",
        "supportTitle":"Fxverter unterstützen",
        "share":"Teilen",
        "shared":"Link kopiert!",
        "feedback":"Feedback",
        "fbPlaceholder":"Ihre Nachricht…",
        "fbSend":"Feedback senden",
        "fbOk":"✓ Feedback gesendet — vielen Dank!",
        "fbEmpty":"Bitte zuerst eine Nachricht schreiben.",
        "fbFail":"Senden fehlgeschlagen — bitte erneut versuchen oder direkt eine E-Mail schreiben.",
        "curLink":"Alle Währungen ansehen",
        "guideLink":"Wechselkurs-Ratgeber",
        "install":"App installieren",
        "instTitle":"Fxverter installieren",
        "instDesc":"Für schnellen Zugriff zum Startbildschirm hinzufügen — funktioniert offline.",
        "instBtn":"Installieren",
        "instLater":"Jetzt nicht",
        "instIos":"Tippe auf die Teilen-Schaltfläche und wähle dann „Zum Home-Bildschirm«.",
        "nearHigh":"Kurs nahe {days}-Tage-Hoch",
        "nearLow":"Kurs nahe {days}-Tage-Tief",
 },
 "fr": {
        "privacy":"Confidentialité : ce site n'utilise aucun cookie et ne collecte aucune donnée personnelle. Des statistiques de visite anonymes, sans cookie (pages vues et pays), peuvent être collectées pour améliorer l'outil.",
        "favLabel":"★ Paires enregistrées",
        "save":"Enregistrer cette paire",
        "saved":"Enregistré",
        "copy":"Copier le résultat",
        "copied":"Copié !",
        "themeAuto":"Thème : auto",
        "themeLight":"Thème : clair",
        "themeDark":"Thème : sombre",
        "supportLabel":"Soutenir",
        "supportTitle":"Soutenir Fxverter",
        "share":"Partager",
        "shared":"Lien copié !",
        "feedback":"Commentaires",
        "fbPlaceholder":"Votre message…",
        "fbSend":"Envoyer le commentaire",
        "fbOk":"✓ Commentaire envoyé — merci !",
        "fbEmpty":"Veuillez d'abord écrire un message.",
        "fbFail":"Échec de l'envoi — réessayez ou écrivez-nous directement.",
        "curLink":"Parcourir toutes les devises",
        "guideLink":"Guides sur les taux de change",
        "install":"Installer l'application",
        "instTitle":"Installer Fxverter",
        "instDesc":"Ajouter à l’écran d’accueil pour un accès rapide — fonctionne hors ligne.",
        "instBtn":"Installer",
        "instLater":"Pas maintenant",
        "instIos":"Touchez le bouton Partager, puis choisissez « Sur l’écran d’accueil ».",
        "nearHigh":"Taux proche du plus haut sur {days} jours",
        "nearLow":"Taux proche du plus bas sur {days} jours",
 },
 "es": {
        "privacy":"Privacidad: este sitio web no usa cookies ni recoge datos personales. Para mejorar la herramienta pueden recogerse estadísticas de visita anónimas y sin cookies (páginas vistas y país).",
        "favLabel":"★ Pares guardados",
        "save":"Guardar este par",
        "saved":"Guardado",
        "copy":"Copiar resultado",
        "copied":"¡Copiado!",
        "themeAuto":"Tema: automático",
        "themeLight":"Tema: claro",
        "themeDark":"Tema: oscuro",
        "supportLabel":"Apoyar",
        "supportTitle":"Apoyar a Fxverter",
        "share":"Compartir",
        "shared":"¡Enlace copiado!",
        "feedback":"Comentarios",
        "fbPlaceholder":"Tu mensaje…",
        "fbSend":"Enviar comentarios",
        "fbOk":"✓ Comentarios enviados — ¡gracias!",
        "fbEmpty":"Escribe un mensaje primero.",
        "fbFail":"Error al enviar — inténtalo de nuevo o escríbenos por correo.",
        "curLink":"Ver todas las divisas",
        "guideLink":"Guías de tipos de cambio",
        "install":"Instalar aplicación",
        "instTitle":"Instalar Fxverter",
        "instDesc":"Añade a la pantalla de inicio para un acceso rápido — funciona sin conexión.",
        "instBtn":"Instalar",
        "instLater":"Ahora no",
        "instIos":"Toca el botón Compartir y elige «Añadir a pantalla de inicio».",
        "nearHigh":"Tipo cerca del máximo de {days} días",
        "nearLow":"Tipo cerca del mínimo de {days} días",
 },
 "pt": {
        "privacy":"Privacidade: este site não usa cookies e não coleta dados pessoais. Estatísticas de visita anônimas, sem cookies (visualizações de página e país), podem ser coletadas para melhorar a ferramenta.",
        "favLabel":"★ Pares salvos",
        "save":"Salvar este par",
        "saved":"Salvo",
        "copy":"Copiar resultado",
        "copied":"Copiado!",
        "themeAuto":"Tema: automático",
        "themeLight":"Tema: claro",
        "themeDark":"Tema: escuro",
        "supportLabel":"Apoiar",
        "supportTitle":"Apoiar o Fxverter",
        "share":"Compartilhar",
        "shared":"Link copiado!",
        "feedback":"Feedback",
        "fbPlaceholder":"Sua mensagem…",
        "fbSend":"Enviar feedback",
        "fbOk":"✓ Feedback enviado — obrigado!",
        "fbEmpty":"Escreva uma mensagem primeiro.",
        "fbFail":"Falha no envio — tente novamente ou envie um e-mail diretamente.",
        "curLink":"Ver todas as moedas",
        "guideLink":"Guias de câmbio",
        "install":"Instalar aplicativo",
        "instTitle":"Instalar o Fxverter",
        "instDesc":"Adicione à tela inicial para acesso rápido — funciona offline.",
        "instBtn":"Instalar",
        "instLater":"Agora não",
        "instIos":"Toque no botão Compartilhar e escolha «Adicionar à Tela de Início».",
        "nearHigh":"Taxa perto da máxima de {days} dias",
        "nearLow":"Taxa perto da mínima de {days} dias",
 },
 "ru": {
        "privacy":"Конфиденциальность: этот сайт не использует файлы cookie и не собирает персональные данные. Для улучшения инструмента могут собираться анонимные статистики посещений без cookie (просмотры страниц и страна).",
        "favLabel":"★ Сохранённые пары",
        "save":"Сохранить эту пару",
        "saved":"Сохранено",
        "copy":"Копировать результат",
        "copied":"Скопировано!",
        "themeAuto":"Тема: авто",
        "themeLight":"Тема: светлая",
        "themeDark":"Тема: тёмная",
        "supportLabel":"Поддержать",
        "supportTitle":"Поддержать Fxverter",
        "share":"Поделиться",
        "shared":"Ссылка скопирована!",
        "feedback":"Обратная связь",
        "fbPlaceholder":"Ваше сообщение…",
        "fbSend":"Отправить отзыв",
        "fbOk":"✓ Отзыв отправлен — спасибо!",
        "fbEmpty":"Сначала напишите сообщение.",
        "fbFail":"Не удалось отправить — попробуйте ещё раз или напишите напрямую.",
        "curLink":"Все валюты",
        "guideLink":"Руководства по курсам",
        "install":"Установить приложение",
        "instTitle":"Установить Fxverter",
        "instDesc":"Добавьте на главный экран для быстрого доступа — работает офлайн.",
        "instBtn":"Установить",
        "instLater":"Не сейчас",
        "instIos":"Нажмите кнопку «Поделиться» и выберите «На экран Домой».",
        "nearHigh":"Курс близок к максимуму за {days} дней",
        "nearLow":"Курс близок к минимуму за {days} дней",
 },
 "zh": {
        "privacy":"隐私：本网站不使用 Cookie、不收集个人数据。仅可能收集匿名的无 Cookie 访问统计（页面浏览量与国家/地区），用于改进工具。",
        "favLabel":"★ 已收藏币种对",
        "save":"收藏此币种对",
        "saved":"已收藏",
        "copy":"复制结果",
        "copied":"已复制！",
        "themeAuto":"主题：跟随系统",
        "themeLight":"主题：浅色",
        "themeDark":"主题：深色",
        "supportLabel":"支持",
        "supportTitle":"支持 Fxverter",
        "share":"分享",
        "shared":"链接已复制！",
        "feedback":"意见反馈",
        "fbPlaceholder":"写下你的反馈…",
        "fbSend":"发送反馈",
        "fbOk":"✓ 反馈已发送——感谢！",
        "fbEmpty":"请先写下反馈内容。",
        "fbFail":"发送失败——请重试或直接发邮件给我们。",
        "curLink":"浏览全部币种",
        "guideLink":"汇率指南",
        "install":"安装应用",
        "instTitle":"安装 Fxverter",
        "instDesc":"添加到主屏幕，随时使用——离线也能用。",
        "instBtn":"安装",
        "instLater":"暂不安装",
        "instIos":"点按分享按钮，然后选择「添加到主屏幕」。",
        "nearHigh":"汇率接近{days}天高点",
        "nearLow":"汇率接近{days}天低点",
 },
 "ja": {
        "privacy":"プライバシー：当サイトはクッキーを使用せず、個人データを収集しません。ツール改善のため、クッキーなしの匿名アクセス統計（ページビューと国）を収集する場合があります。",
        "favLabel":"★ 保存した通貨ペア",
        "save":"このペアを保存",
        "saved":"保存しました",
        "copy":"結果をコピー",
        "copied":"コピーしました！",
        "themeAuto":"テーマ：自動",
        "themeLight":"テーマ：ライト",
        "themeDark":"テーマ：ダーク",
        "supportLabel":"支援する",
        "supportTitle":"Fxverterを支援する",
        "share":"共有",
        "shared":"リンクをコピーしました！",
        "feedback":"フィードバック",
        "fbPlaceholder":"メッセージを入力…",
        "fbSend":"フィードバックを送信",
        "fbOk":"✓ フィードバックを送信しました — ありがとうございます！",
        "fbEmpty":"先にメッセージを入力してください。",
        "fbFail":"送信に失敗しました — 再試行するか、直接メールでお問い合わせください。",
        "curLink":"すべての通貨を見る",
        "guideLink":"為替レートガイド",
        "install":"アプリをインストール",
        "instTitle":"Fxverter をインストール",
        "instDesc":"ホーム画面に追加して素早くアクセス——オフラインでも使えます。",
        "instBtn":"インストール",
        "instLater":"後で",
        "instIos":"共有ボタンをタップして、「ホーム画面に追加」を選んでください。",
        "nearHigh":"レートは{days}日の高値付近",
        "nearLow":"レートは{days}日の安値付近",
 },
 "ko": {
        "privacy":"개인정보: 이 웹사이트는 쿠키를 사용하지 않으며 개인 데이터를 수집하지 않습니다. 도구 개선을 위해 익명의 쿠키 없는 방문 통계(페이지뷰 및 국가)가 수집될 수 있습니다.",
        "favLabel":"★ 저장된 통화 쌍",
        "save":"이 쌍 저장",
        "saved":"저장됨",
        "copy":"결과 복사",
        "copied":"복사됨!",
        "themeAuto":"테마: 자동",
        "themeLight":"테마: 밝게",
        "themeDark":"테마: 어둡게",
        "supportLabel":"支持",
        "supportTitle":"Fxverter 지원하기",
        "share":"공유",
        "shared":"링크 복사됨!",
        "feedback":"피드백",
        "fbPlaceholder":"메시지를 입력…",
        "fbSend":"피드백 보내기",
        "fbOk":"✓ 피드백이 전송되었습니다 — 감사합니다!",
        "fbEmpty":"먼저 메시지를 입력하세요.",
        "fbFail":"전송에 실패했습니다 — 다시 시도하거나 직접 이메일을 보내주세요.",
        "curLink":"모든 통화 보기",
        "guideLink":"환율 가이드",
        "install":"앱 설치",
        "instTitle":"Fxverter 설치",
        "instDesc":"홈 화면에 추가하면 빠르게 접속할 수 있고 오프라인에서도 작동합니다.",
        "instBtn":"설치",
        "instLater":"나중에",
        "instIos":"공유 버튼을 누른 다음 «홈 화면에 추가»를 선택하세요.",
        "nearHigh":"환율 {days}일 최고점 부근",
        "nearLow":"환율 {days}일 최저점 부근",
 },
 "ar": {
        "privacy":"الخصوصية: لا يستخدم هذا الموقع ملفات تعريف الارتباط ولا يجمع بيانات شخصية. قد تُجمع إحصاءات زيارة مجهولة بدون كوكيز (مشاهدات الصفحة والبلد) لتحسين الأداة.",
        "favLabel":"★ الأزواج المحفوظة",
        "save":"احفظ هذا الزوج",
        "saved":"محفوظ",
        "copy":"نسخ النتيجة",
        "copied":"تم النسخ!",
        "themeAuto":"المظهر: تلقائي",
        "themeLight":"المظهر: فاتح",
        "themeDark":"المظهر: داكن",
        "supportLabel":"ادعم",
        "supportTitle":"ادعم Fxverter",
        "share":"مشاركة",
        "shared":"تم نسخ الرابط!",
        "feedback":"ملاحظات",
        "fbPlaceholder":"رسالتك…",
        "fbSend":"إرسال الملاحظات",
        "fbOk":"✓ تم إرسال الملاحظات — شكرًا لك!",
        "fbEmpty":"يرجى كتابة رسالة أولاً.",
        "fbFail":"فشل الإرسال — حاول مرة أخرى أو راسلنا مباشرة.",
        "curLink":"تصفح جميع العملات",
        "guideLink":"أدلة أسعار الصرف",
        "install":"تثبيت التطبيق",
        "instTitle":"ثبِّت Fxverter",
        "instDesc":"أضِفه إلى الشاشة الرئيسية للوصول السريع — يعمل دون اتصال.",
        "instBtn":"تثبيت",
        "instLater":"ليس الآن",
        "instIos":"اضغط زر المشاركة ثم اختر «إضافة إلى الشاشة الرئيسية».",
        "nearHigh":"السعر قريب من أعلى مستوى خلال {days} يومًا",
        "nearLow":"السعر قريب من أدنى مستوى خلال {days} يومًا",
 },
 "hi": {
        "privacy":"गोपनीयता: यह वेबसाइट कुकीज़ का उपयोग नहीं करती और कोई व्यक्तिगत डेटा एकत्र नहीं करती। टूल को बेहतर बनाने के लिए गुमनाम, कुकी-मुक्त विज़िट आंकड़े (पेज व्यू और देश) एकत्र किए जा सकते हैं।",
        "favLabel":"★ सहेजे गए जोड़े",
        "save":"यह जोड़ा सहेजें",
        "saved":"सहेजा गया",
        "copy":"परिणाम कॉपी करें",
        "copied":"कॉपी हो गया!",
        "themeAuto":"थीम: स्वतः",
        "themeLight":"थीम: हल्की",
        "themeDark":"थीम: गहरी",
        "supportLabel":"सहयोग करें",
        "supportTitle":"Fxverter का समर्थन करें",
        "share":"साझा करें",
        "shared":"लिंक कॉपी हो गया!",
        "feedback":"प्रतिक्रिया",
        "fbPlaceholder":"आपका संदेश…",
        "fbSend":"प्रतिक्रिया भेजें",
        "fbOk":"✓ प्रतिक्रिया भेजी गई — धन्यवाद!",
        "fbEmpty":"पहले एक संदेश लिखें।",
        "fbFail":"भेजना विफल — फिर से प्रयास करें या सीधे हमें ईमेल करें।",
        "curLink":"सभी मुद्राएँ देखें",
        "guideLink":"विनिमय दर गाइड",
        "install":"ऐप इंस्टॉल करें",
        "instTitle":"Fxverter इंस्टॉल करें",
        "instDesc":"त्वरित ऐक्सेस के लिए होम स्क्रीन पर जोड़ें — ऑफ़लाइन भी चलता है।",
        "instBtn":"इंस्टॉल",
        "instLater":"अभी नहीं",
        "instIos":"Share बटन टैप करें, फिर «Add to Home Screen» चुनें।",
        "nearHigh":"दर {days} दिन के उच्चतम स्तर के पास",
        "nearLow":"दर {days} दिन के निम्नतम स्तर के पास",
 },
 "id": {
        "privacy":"Privasi: situs ini tidak menggunakan cookie dan tidak mengumpulkan data pribadi. Statistik kunjungan anonim tanpa cookie (jumlah tayangan halaman dan negara) dapat dikumpulkan untuk memperbaiki alat ini.",
        "favLabel":"★ Pasangan tersimpan",
        "save":"Simpan pasangan ini",
        "saved":"Tersimpan",
        "copy":"Salin hasil",
        "copied":"Tersalin!",
        "themeAuto":"Tema: otomatis",
        "themeLight":"Tema: terang",
        "themeDark":"Tema: gelap",
        "supportLabel":"Dukung",
        "supportTitle":"Dukung Fxverter",
        "share":"Bagikan",
        "shared":"Tautan disalin!",
        "feedback":"Umpan balik",
        "fbPlaceholder":"Pesan Anda…",
        "fbSend":"Kirim masukan",
        "fbOk":"✓ Masukan terkirim — terima kasih!",
        "fbEmpty":"Tulis pesan terlebih dahulu.",
        "fbFail":"Gagal mengirim — coba lagi atau kirim email langsung kepada kami.",
        "curLink":"Lihat semua mata uang",
        "guideLink":"Panduan kurs",
        "install":"Instal aplikasi",
        "instTitle":"Pasang Fxverter",
        "instDesc":"Tambahkan ke layar utama untuk akses cepat — bekerja offline.",
        "instBtn":"Pasang",
        "instLater":"Nanti saja",
        "instIos":"Ketuk tombol Bagikan, lalu pilih «Tambahkan ke Layar Utama».",
        "nearHigh":"Kurs dekat titik tertinggi {days} hari",
        "nearLow":"Kurs dekat titik terendah {days} hari",
 },
 "ms": {
        "privacy":"Privasi: laman web ini tidak menggunakan kuki dan tidak mengumpulkan data peribadi. Statistik lawatan tanpa nama tanpa kuki (paparan halaman dan negara) mungkin dikumpulkan untuk menambah baik alat ini.",
        "favLabel":"★ Pasangan disimpan",
        "save":"Simpan pasangan ini",
        "saved":"Disimpan",
        "copy":"Salin hasil",
        "copied":"Disalin!",
        "themeAuto":"Tema: automatik",
        "themeLight":"Tema: cerah",
        "themeDark":"Tema: gelap",
        "supportLabel":"Sokong",
        "supportTitle":"Sokong Fxverter",
        "share":"Kongsi",
        "shared":"Pautan disalin!",
        "feedback":"Maklum balas",
        "fbPlaceholder":"Mesej anda…",
        "fbSend":"Hantar maklum balas",
        "fbOk":"✓ Maklum balas dihantar — terima kasih!",
        "fbEmpty":"Tulis mesej dahulu.",
        "fbFail":"Hantar gagal — cuba lagi atau emel terus kepada kami.",
        "curLink":"Lihat semua mata wang",
        "guideLink":"Panduan kadar pertukaran",
        "install":"Pasang aplikasi",
        "instTitle":"Pasang Fxverter",
        "instDesc":"Tambah ke skrin utama untuk akses pantas — berfungsi luar talian.",
        "instBtn":"Pasang",
        "instLater":"Bukan sekarang",
        "instIos":"Ketik butang Kongsi, kemudian pilih «Tambah ke Skrin Utama».",
        "nearHigh":"Kadar hampir titik tertinggi {days} hari",
        "nearLow":"Kadar hampir titik terendah {days} hari",
 },
 "tl": {
        "privacy":"Privacy: hindi gumagamit ng cookies ang website na ito at hindi nagkokolekta ng personal na data. Maaaring mangolekta ng anonymous, cookie-free na visit statistics (page views at bansa) para pagbutihin ang tool.",
        "favLabel":"★ Na-save na pares",
        "save":"I-save ang pares na ito",
        "saved":"Na-save",
        "copy":"I-copy ang resulta",
        "copied":"Nakopya!",
        "themeAuto":"Tema: auto",
        "themeLight":"Tema: maliwanag",
        "themeDark":"Tema: madilim",
        "supportLabel":"Suportahan",
        "supportTitle":"Suportahan ang Fxverter",
        "share":"I-share",
        "shared":"Nakopya ang link!",
        "feedback":"Feedback",
        "fbPlaceholder":"Ang mensahe mo…",
        "fbSend":"Ipadala ang feedback",
        "fbOk":"✓ Naipadala ang feedback — salamat!",
        "fbEmpty":"Magsulat muna ng mensahe.",
        "fbFail":"Hindi naipadala — subukan mulan o direktang mag-email sa amin.",
        "curLink":"Tingnan ang lahat ng pera",
        "guideLink":"Mga gabay sa exchange rate",
        "install":"I-install ang app",
        "instTitle":"I-install ang Fxverter",
        "instDesc":"Idagdag sa home screen para mabilis na access — gumagana offline.",
        "instBtn":"I-install",
        "instLater":"Hindi ngayon",
        "instIos":"I-tap ang Share button, piliin ang «Add to Home Screen».",
        "nearHigh":"Malapit sa {days}-day high ang rate",
        "nearLow":"Malapit sa {days}-day low ang rate",
 },
 "it": {
        "privacy":"Privacy: questo sito non usa cookie e non raccoglie dati personali. Statistiche di visita anonime senza cookie (visualizzazioni di pagina e paese) possono essere raccolte per migliorare lo strumento.",
        "favLabel":"★ Coppie salvate",
        "save":"Salva questa coppia",
        "saved":"Salvata",
        "copy":"Copia risultato",
        "copied":"Copiato!",
        "themeAuto":"Tema: automatico",
        "themeLight":"Tema: chiaro",
        "themeDark":"Tema: scuro",
        "supportLabel":"Supporta",
        "supportTitle":"Sostieni Fxverter",
        "share":"Condividi",
        "shared":"Link copiato!",
        "feedback":"Feedback",
        "fbPlaceholder":"Il tuo messaggio…",
        "fbSend":"Invia feedback",
        "fbOk":"✓ Feedback inviato — grazie!",
        "fbEmpty":"Scrivi prima un messaggio.",
        "fbFail":"Invio non riuscito — riprova o scrivici direttamente.",
        "curLink":"Vedi tutte le valute",
        "guideLink":"Guide sui tassi di cambio",
        "install":"Installa l'app",
        "instTitle":"Installa Fxverter",
        "instDesc":"Aggiungi alla schermata Home per un accesso rapido — funziona offline.",
        "instBtn":"Installa",
        "instLater":"Non ora",
        "instIos":"Tocca il pulsante Condividi e scegli «Aggiungi a Home».",
        "nearHigh":"Tasso vicino al massimo di {days} giorni",
        "nearLow":"Tasso vicino al minimo di {days} giorni",
 },
 "nl": {
        "privacy":"Privacy: deze website gebruikt geen cookies en verzamelt geen persoonsgegevens. Anonieme, cookievrije bezochtsstatistieken (paginaweergaven en land) kunnen worden verzameld om de tool te verbeteren.",
        "favLabel":"★ Bewaarde paren",
        "save":"Dit paar bewaren",
        "saved":"Bewaard",
        "copy":"Resultaat kopiëren",
        "copied":"Gekopieerd!",
        "themeAuto":"Thema: automatisch",
        "themeLight":"Thema: licht",
        "themeDark":"Thema: donker",
        "supportLabel":"Steun",
        "supportTitle":"Steun Fxverter",
        "share":"Delen",
        "shared":"Link gekopieerd!",
        "feedback":"Feedback",
        "fbPlaceholder":"Uw bericht…",
        "fbSend":"Feedback verzenden",
        "fbOk":"✓ Feedback verzonden — bedankt!",
        "fbEmpty":"Schrijf eerst een bericht.",
        "fbFail":"Verzenden mislukt — probeer het opnieuw of mail ons direct.",
        "curLink":"Alle valuta's bekijken",
        "guideLink":"Wisselkoersgidsen",
        "install":"App installeren",
        "instTitle":"Fxverter installeren",
        "instDesc":"Voeg toe aan het beginscherm voor snelle toegang — werkt offline.",
        "instBtn":"Installeren",
        "instLater":"Niet nu",
        "instIos":"Tik op de deelknop en kies «Zet op het beginscherm».",
        "nearHigh":"Koers nabij {days}-dagen hoogtepunt",
        "nearLow":"Koers nabij {days}-dagen dieptepunt",
 },
 "pl": {
        "privacy":"Prywatność: ta strona nie używa plików cookie i nie zbiera danych osobowych. W celu ulepszenia narzędzia mogą być zbierane anonimowe statystyki wizyt bez plików cookie (wyświetlenia stron i kraj).",
        "favLabel":"★ Zapisane pary",
        "save":"Zapisz tę parę",
        "saved":"Zapisano",
        "copy":"Skopiuj wynik",
        "copied":"Skopiowano!",
        "themeAuto":"Motyw: automatycznie",
        "themeLight":"Motyw: jasny",
        "themeDark":"Motyw: ciemny",
        "supportLabel":"Wesprzyj",
        "supportTitle":"Wesprzyj Fxverter",
        "share":"Udostępnij",
        "shared":"Link skopiowano!",
        "feedback":"Opinia",
        "fbPlaceholder":"Twoja wiadomość…",
        "fbSend":"Wyślij opinię",
        "fbOk":"✓ Opinia wysłana — dziękujemy!",
        "fbEmpty":"Najpierw napisz wiadomość.",
        "fbFail":"Wysyłanie nie powiodło się — spróbuj ponownie lub napisz do nas bezpośrednio.",
        "curLink":"Zobacz wszystkie waluty",
        "guideLink":"Poradniki kursów",
        "install":"Zainstaluj aplikację",
        "instTitle":"Zainstaluj Fxverter",
        "instDesc":"Dodaj do ekranu głównego, aby mieć szybki dostęp — działa offline.",
        "instBtn":"Zainstaluj",
        "instLater":"Nie teraz",
        "instIos":"Stuknij przycisk Udostępnij i wybierz «Dodaj do ekranu głównego».",
        "nearHigh":"Kurs blisko maksimum {days} dni",
        "nearLow":"Kurs blisko minimum {days} dni",
 },
 "uk": {
        "privacy":"Приватність: цей сайт не використовує cookie та не збирає персональні дані. Для покращення інструменту можуть збиратися анонімні статистики відвідувань без cookie (перегляди сторінок і країна).",
        "favLabel":"★ Збережені пари",
        "save":"Зберегти цю пару",
        "saved":"Збережено",
        "copy":"Копіювати результат",
        "copied":"Скопійовано!",
        "themeAuto":"Тема: авто",
        "themeLight":"Тема: світла",
        "themeDark":"Тема: темна",
        "supportLabel":"Підтримати",
        "supportTitle":"Підтримати Fxverter",
        "share":"Поділитися",
        "shared":"Посилання скопійовано!",
        "feedback":"Зворотний зв'язок",
        "fbPlaceholder":"Ваше повідомлення…",
        "fbSend":"Надіслати відгук",
        "fbOk":"✓ Відгук надіслано — дякуємо!",
        "fbEmpty":"Спочатку напишіть повідомлення.",
        "fbFail":"Не вдалося надіслати — спробуйте ще раз або напишіть нам напряму.",
        "curLink":"Усі валюти",
        "guideLink":"Посібники з курсів",
        "install":"Встановити застосунок",
        "instTitle":"Встановити Fxverter",
        "instDesc":"Додайте на головний екран для швидкого доступу — працює офлайн.",
        "instBtn":"Встановити",
        "instLater":"Не зараз",
        "instIos":"Натисніть кнопку «Поділитися» та оберіть «На головний екран».",
        "nearHigh":"Курс біля максимуму за {days} днів",
        "nearLow":"Курс біля мінімуму за {days} днів",
 },
 "sv": {
        "privacy":"Integritet: denna webbplats använder inga cookies och samlar inte in personuppgifter. Anonyma besöksstatistik utan cookies (sidvisningar och land) kan samlas in för att förbättra verktyget.",
        "favLabel":"★ Sparade par",
        "save":"Spara detta par",
        "saved":"Sparat",
        "copy":"Kopiera resultat",
        "copied":"Kopierat!",
        "themeAuto":"Tema: automatiskt",
        "themeLight":"Tema: ljust",
        "themeDark":"Tema: mörkt",
        "supportLabel":"Stöd",
        "supportTitle":"Stöd Fxverter",
        "share":"Dela",
        "shared":"Länk kopierad!",
        "feedback":"Feedback",
        "fbPlaceholder":"Ditt meddelande…",
        "fbSend":"Skicka feedback",
        "fbOk":"✓ Feedback skickad — tack!",
        "fbEmpty":"Skriv ett meddelande först.",
        "fbFail":"Kunde inte skicka — försök igen eller mejla oss direkt.",
        "curLink":"Se alla valutor",
        "guideLink":"Växelkursguider",
        "install":"Installera appen",
        "instTitle":"Installera Fxverter",
        "instDesc":"Lägg till på startskärmen för snabb åtkomst — fungerar offline.",
        "instBtn":"Installera",
        "instLater":"Inte nu",
        "instIos":"Tryck på dela-knappen och välj «Lägg till på startskärmen».",
        "nearHigh":"Kursen nära högsta på {days} dagar",
        "nearLow":"Kursen nära lägsta på {days} dagar",
 },
 "th": {
        "privacy":"ความเป็นส่วนตัว: เว็บไซต์นี้ไม่ใช้คุกกี้และไม่เก็บข้อมูลส่วนบุคคล อาจมีการเก็บสถิติการเข้าชมแบบไม่ระบุตัวตนโดยไม่ใช้คุกกี้ (ยอดเข้าชมหน้าเว็บและประเทศ) เพื่อปรับปรุงเครื่องมือ",
        "favLabel":"★ คู่ที่บันทึกไว้",
        "save":"บันทึกคู่นี้",
        "saved":"บันทึกแล้ว",
        "copy":"คัดลอกผลลัพธ์",
        "copied":"คัดลอกแล้ว!",
        "themeAuto":"ธีม: อัตโนมัติ",
        "themeLight":"ธีม: สว่าง",
        "themeDark":"ธีม: มืด",
        "supportLabel":"สนับสนุน",
        "supportTitle":"สนับสนุน Fxverter",
        "share":"แชร์",
        "shared":"คัดลอกลิงก์แล้ว!",
        "feedback":"ส่งความคิดเห็น",
        "fbPlaceholder":"ข้อความของคุณ…",
        "fbSend":"ส่งความคิดเห็น",
        "fbOk":"✓ ส่งความคิดเห็นแล้ว — ขอบคุณ!",
        "fbEmpty":"กรุณาเขียนข้อความก่อน",
        "fbFail":"ส่งไม่สำเร็จ — ลองอีกครั้งหรือส่งอีเมลถึงเราโดยตรง",
        "curLink":"ดูสกุลเงินทั้งหมด",
        "guideLink":"คู่มืออัตราแลกเปลี่ยน",
        "install":"ติดตั้งแอป",
        "instTitle":"ติดตั้ง Fxverter",
        "instDesc":"เพิ่มที่หน้าจอหลักเพื่อเข้าใช้เร็ว — ใช้แบบออฟไลน์ได้",
        "instBtn":"ติดตั้ง",
        "instLater":"ไว้ทีหลัง",
        "instIos":"แตปปุ่มแชร์ แล้วเลือก «เพิ่มที่หน้าจอหลัก»",
        "nearHigh":"อัตราใกล้จุดสูงสุด {days} วัน",
        "nearLow":"อัตราใกล้จุดต่ำสุด {days} วัน",
 },
 "lo": {
        "privacy":"ຄວາມເປັນສ່ວນຕົວ: ເວັບໄຊນ໌ນີ້ບໍ່ໃຊ້ຄຸກກີ ແລະ ບໍ່ເກັບຂໍ້ມູນສ່ວນຕົວ. ອາດເກັບສະຖິตິກການເຂົ້າຊົມແບບນິລະນາມ ໂດຍບໍ່ໃຊ້ຄຸກກີ (ຈຳນວນເຂົ້າຊົມ ແລະ ປະເທດ) ເພື່ອປັບປຸງເຄື່ອງມື.",
        "favLabel":"★ ຄູ່ທີ່ບັນທຶກໄວ້",
        "save":"ບັນທຶກຄູ່ນີ້",
        "saved":"ບັນທຶກແລ້ວ",
        "copy":"ສຳເນົາຜົນການ",
        "copied":"ສຳເນົາແລ້ວ!",
        "themeAuto":"ຮູບແບບ: ອັດຕະໂນມັດ",
        "themeLight":"ຮູບແບບ: ສະຫວ່າງ",
        "themeDark":"ຮູບແບບ: ມືດ",
        "supportLabel":"ສະໜັບສະໜູນ",
        "supportTitle":"ສະໜັບສະໜູນ Fxverter",
        "share":"ແບ່ງປັນ",
        "shared":"ສຳເນົາລິ້ງແລ້ວ!",
        "feedback":"ຄຳຄິດເຫັນ",
        "fbPlaceholder":"ຂໍ້ຄວາມຂອງເຈົ້າ…",
        "fbSend":"ສົ່ງຄຳຄິດເຫັນ",
        "fbOk":"✓ ສົ່ງຄຳຄິດເຫັນແລ້ວ — ຂອບໃຈ!",
        "fbEmpty":"ກະລຸນາຂຽນຂໍ້ຄວາມກ່ອນ.",
        "fbFail":"ສົ່ງບໍ່ສຳເລັດ — ລອງໃໝ່ ຫຼື ສົ່ງອີເມວມາຫາເຮົາໂດຍກົງ.",
        "curLink":"ເບິ່ງສະກຸນເງິນທັງໝົດ",
        "guideLink":"ຄູ່ມືອັດຕາແລກປ່ຽນ",
        "install":"ຕິດຕັ້ງແອັບ",
        "instTitle":"ຕິດຕັ້ງ Fxverter",
        "instDesc":"ເພີ່ມໃສໜ້າຈໍຫຼັກເພື່ອເຂົ້າໃຊ້ໄວ — ໃຊ້ອອຟລາຍນ໌ໄດ້",
        "instBtn":"ຕິດຕັ້ງ",
        "instLater":"ບໍ່ຕົກການ",
        "instIos":"ແຕັບປຸ່ມແບ່ງປັນ ແລ້ວເລືອກ «ເພີ່ມໃສໜ້າຈໍຫຼັກ»",
        "nearHigh":"ອັດຕາໃກ້ຈຸດສູງສຸດ {days} ວັນ",
        "nearLow":"ອັດຕາໃກ້ຈຸດຕ່ຳສຸດ {days} ວັນ",
 },
 "vi": {
        "privacy":"Quyền riêng tư: trang web này không sử dụng cookie và không thu thập dữ liệu cá nhân. Thống kê truy cập ẩn danh, không cookie (lượt xem trang và quốc gia) có thể được thu thập để cải thiện công cụ.",
        "favLabel":"★ Cặp đã lưu",
        "save":"Lưu cặp này",
        "saved":"Đã lưu",
        "copy":"Sao chép kết quả",
        "copied":"Đã sao chép!",
        "themeAuto":"Chủ đề: tự động",
        "themeLight":"Chủ đề: sáng",
        "themeDark":"Chủ đề: tối",
        "supportLabel":"Ủng hộ",
        "supportTitle":"Ủng hộ Fxverter",
        "share":"Chia sẻ",
        "shared":"Đã sao chép liên kết!",
        "feedback":"Phản hồi",
        "fbPlaceholder":"Tin nhắn của bạn…",
        "fbSend":"Gửi phản hồi",
        "fbOk":"✓ Đã gửi phản hồi — cảm ơn bạn!",
        "fbEmpty":"Vui lòng viết tin nhắn trước.",
        "fbFail":"Gửi thất bại — thử lại hoặc gửi email trực tiếp cho chúng tôi.",
        "curLink":"Xem tất cả tiền tệ",
        "guideLink":"Cẩm nang tỷ giá",
        "install":"Cài đặt ứng dụng",
        "instTitle":"Cài đặt Fxverter",
        "instDesc":"Thêm vào màn hình chính để truy cập nhanh — hoạt động ngoại tuyến.",
        "instBtn":"Cài đặt",
        "instLater":"Để sau",
        "instIos":"Nhấn nút Chia sẻ, rồi chọn «Thêm vào Màn hình chính».",
        "nearHigh":"Tỷ giá gần mức cao nhất {days} ngày",
        "nearLow":"Tỷ giá gần mức thấp nhất {days} ngày",
 },
 "el": {
        "privacy":"Απορρήτου: αυτός ο ιστότοπος δεν χρησιμοποιεί cookie και δεν συλλέγει προσωπικά δεδομένα. Ανώνυμα στατιστικά επισκεψιμότητας χωρίς cookie (εμφανίσεις σελίδας και χώρα) ενδέχεται να συλλέγονται για τη βελτίωση του εργαλείου.",
        "favLabel":"★ Αποθηκευμένα ζεύγη",
        "save":"Αποθήκευση ζεύγους",
        "saved":"Αποθηκεύτηκε",
        "copy":"Αντιγραφή αποτελέσματος",
        "copied":"Αντιγράφηκε!",
        "themeAuto":"Θέμα: αυτόματο",
        "themeLight":"Θέμα: φωτεινό",
        "themeDark":"Θέμα: σκούρο",
        "supportLabel":"Υποστήριξη",
        "supportTitle":"Υποστηρίξτε το Fxverter",
        "share":"Κοινοποίηση",
        "shared":"Ο σύνδεσμος αντιγράφηκε!",
        "feedback":"Σχόλια",
        "fbPlaceholder":"Το μήνυμά σας…",
        "fbSend":"Αποστολή σχολίων",
        "fbOk":"✓ Τα σχόλια στάλθηκαν — ευχαριστούμε!",
        "fbEmpty":"Γράψτε πρώτα ένα μήνυμα.",
        "fbFail":"Η αποστολή απέτυχε — δοκιμάστε ξανά ή στείλτε μας email.",
        "curLink":"Όλα τα νομίσματα",
        "guideLink":"Οδηγοί ισοτιμιών",
        "install":"Εγκατάσταση εφαρμογής",
        "instTitle":"Εγκατάσταση Fxverter",
        "instDesc":"Προσθέστε στην αρχική οθόνη για γρήγορη πρόσβαση — λειτουργεί και offline.",
        "instBtn":"Εγκατάσταση",
        "instLater":"Όχι τώρα",
        "instIos":"Πατήστε το κουμπί Κοινοποίηση και επιλέξτε «Προσθήκη στην Αρχική οθόνη».",
        "nearHigh":"Η ισοτιμία κοντά στο μέγιστο {days} ημερών",
        "nearLow":"Η ισοτιμία κοντά στο ελάχιστο {days} ημερών",
 },
 "bn": {
        "privacy":"গোপনীয়তা: এই ওয়েবসাইট কুকি ব্যবহার করে না এবং কোনো ব্যক্তিগত তথ্য সংগ্রহ করে না। টুল উন্নত করতে নাম-গোপন কুকি-মুক্ত ভিজিট পরিসংখ্যান (পেজ ভিউ ও দেশ) সংগ্রহ করা হতে পারে।",
        "favLabel":"★ সংরক্ষিত জোড়া",
        "save":"এই জোড়া সংরক্ষণ",
        "saved":"সংরক্ষিত",
        "copy":"ফলাফল কপি",
        "copied":"কপি হয়েছে!",
        "themeAuto":"থিম: স্বয়ংক্রিয়",
        "themeLight":"থিম: হালকা",
        "themeDark":"থিম: গাঢ়",
        "supportLabel":"সমর্থন",
        "supportTitle":"Fxverter-কে সমর্থন করুন",
        "share":"শেয়ার",
        "shared":"লিংক কপি হয়েছে!",
        "feedback":"মতামত",
        "fbPlaceholder":"আপনার বার্তা…",
        "fbSend":"মতামত পাঠান",
        "fbOk":"✓ মতামত পাঠানো হয়েছে — ধন্যবাদ!",
        "fbEmpty":"প্রথমে একটি বার্তা লিখুন।",
        "fbFail":"পাঠানো ব্যর্থ — আবার চেষ্টা করুন বা সরাসরি ইমেইল করুন।",
        "curLink":"সব মুদ্রা দেখুন",
        "guideLink":"বিনিময় হার গাইড",
        "install":"অ্যাপ ইনস্টল করুন",
        "instTitle":"Fxverter ইনস্টল করুন",
        "instDesc":"দ্রুত অ্যাক্সেসের জন্য হোম স্ক্রিনে যোগ করুন — অফলাইনেও কাজ করে।",
        "instBtn":"ইনস্টল",
        "instLater":"এখন নয়",
        "instIos":"শেয়ার বাটনে ট্যাপ করুন, তারপর «Add to Home Screen» বেছে নিন।",
        "nearHigh":"হার {days} দিনের সর্বোচ্চের কাছে",
        "nearLow":"হার {days} দিনের সর্বনিম্নের কাছে",
 },
 "fa": {
        "privacy":"حریم خصوصی: این وب‌سایت از کوکی استفاده نمی‌کند و داده‌های شخصی جمع نمی‌کند. برای بهبود ابزار ممکن است آمار بازدید ناشناس و بدون کوکی (بازدید صفحه و کشور) جمع‌آوری شود.",
        "favLabel":"★ جفت‌های ذخیره‌شده",
        "save":"ذخیره این جفت",
        "saved":"ذخیره شد",
        "copy":"کپی نتیجه",
        "copied":"کپی شد!",
        "themeAuto":"پوسته: خودکار",
        "themeLight":"پوسته: روشن",
        "themeDark":"پوسته: تاریک",
        "supportLabel":"حمایت",
        "supportTitle":"حمایت از Fxverter",
        "share":"اشتراک‌گذاری",
        "shared":"لینک کپی شد!",
        "feedback":"بازخورد",
        "fbPlaceholder":"پیام شما…",
        "fbSend":"ارسال بازخورد",
        "fbOk":"✓ بازخورد ارسال شد — متشکرم!",
        "fbEmpty":"لطفاً ابتدا پیامی بنویسید.",
        "fbFail":"ارسال ناموفق بود — دوباره تلاش کنید یا مستقیماً ایمیل بزنید.",
        "curLink":"همه ارزها",
        "guideLink":"راهنمای نرخ ارز",
        "install":"نصب برنامه",
        "instTitle":"نصب Fxverter",
        "instDesc":"برای دسترسی سریع به صفحه اصلی اضافه کنید — آفلاین هم کار می‌کند.",
        "instBtn":"نصب",
        "instLater":"الان نه",
        "instIos":"دکمه اشتراک‌گذاری را بزنید و «افزودن به صفحه اصلی» را انتخاب کنید.",
        "nearHigh":"نرخ نزدیک بیشینه {days} روزه",
        "nearLow":"نرخ نزدیک کمینه {days} روزه",
 },
 "cs": {
        "privacy":"Soukromí: tento web nepoužívá soubory cookie a nesbírá osobní údaje. Anonymní statistiky návštěv bez cookies (zobrazené stránky a země) mohou být sbírány ke zlepšení nástroje.",
        "favLabel":"★ Uložené páry",
        "save":"Uložit tento pár",
        "saved":"Uloženo",
        "copy":"Zkopírovat výsledek",
        "copied":"Zkopírováno!",
        "themeAuto":"Motiv: automaticky",
        "themeLight":"Motiv: světlý",
        "themeDark":"Motiv: tmavý",
        "supportLabel":"Podpořit",
        "supportTitle":"Podpořte Fxverter",
        "share":"Sdílet",
        "shared":"Odkaz zkopírován!",
        "feedback":"Zpětná vazba",
        "fbPlaceholder":"Vaše zpráva…",
        "fbSend":"Odeslat zpětnou vazbu",
        "fbOk":"✓ Zpětná vazba odeslána — děkujeme!",
        "fbEmpty":"Nejprve napište zprávu.",
        "fbFail":"Odeslání selhalo — zkuste to znovu nebo nám napište přímo.",
        "curLink":"Všechny měny",
        "guideLink":"Průvodci kurzy",
        "install":"Nainstalovat aplikaci",
        "instTitle":"Nainstalovat Fxverter",
        "instDesc":"Přidejte na domovskou obrazovku pro rychlý přístup — funguje offline.",
        "instBtn":"Nainstalovat",
        "instLater":"Teď ne",
        "instIos":"Klepněte na tlačítko Sdílet a zvolte «Přidat na domovskou obrazovku».",
        "nearHigh":"Kurz blisko maxima za {days} dní",
        "nearLow":"Kurz blisko minima za {days} dní",
 },
 "ro": {
        "privacy":"Confidențialitate: acest site nu folosește cookie-uri și nu colectează date personale. Statistici de vizită anonime, fără cookie-uri (vizualizări de pagină și țară), pot fi colectate pentru a îmbunătăți instrumentul.",
        "favLabel":"★ Perechi salvate",
        "save":"Salvează această pereche",
        "saved":"Salvat",
        "copy":"Copiază rezultatul",
        "copied":"Copiat!",
        "themeAuto":"Temă: automat",
        "themeLight":"Temă: deschis",
        "themeDark":"Temă: întunecat",
        "supportLabel":"Susține",
        "supportTitle":"Susține Fxverter",
        "share":"Partajează",
        "shared":"Link copiat!",
        "feedback":"Feedback",
        "fbPlaceholder":"Mesajul tău…",
        "fbSend":"Trimite feedback",
        "fbOk":"✓ Feedback trimis — mulțumim!",
        "fbEmpty":"Scrie mai întâi un mesaj.",
        "fbFail":"Trimiterea a eșuat — încearcă din nou sau scrie-ne direct.",
        "curLink":"Toate valutele",
        "guideLink":"Ghiduri de curs valutar",
        "install":"Instalează aplicația",
        "instTitle":"Instalează Fxverter",
        "instDesc":"Adaugă pe ecranul de start pentru acces rapid — funcționează offline.",
        "instBtn":"Instalează",
        "instLater":"Nu acum",
        "instIos":"Atinge butonul de distribuire și alege «Adaugă la ecranul de pornire».",
        "nearHigh":"Cursul aproape de maximul de {days} zile",
        "nearLow":"Cursul aproape de minimul de {days} zile",
 },
 "da": {
        "privacy":"Privatliv: denne hjemmeside bruger ikke cookies og indsamler ikke persondata. Anonyme, cookiefri besøgsstatistikker (sidevisninger og land) kan indsamles for at forbedre værktøjet.",
        "favLabel":"★ Gemte par",
        "save":"Gem dette par",
        "saved":"Gemt",
        "copy":"Kopiér resultat",
        "copied":"Kopieret!",
        "themeAuto":"Tema: automatisk",
        "themeLight":"Tema: lys",
        "themeDark":"Tema: mørk",
        "supportLabel":"Støt",
        "supportTitle":"Støt Fxverter",
        "share":"Del",
        "shared":"Link kopieret!",
        "feedback":"Feedback",
        "fbPlaceholder":"Din besked…",
        "fbSend":"Send feedback",
        "fbOk":"✓ Feedback sendt — tak!",
        "fbEmpty":"Skriv først en besked.",
        "fbFail":"Kunne ikke sende — prøv igen eller skriv direkte til os.",
        "curLink":"Se alle valutaer",
        "guideLink":"Vekselkursguider",
        "install":"Installér appen",
        "instTitle":"Installér Fxverter",
        "instDesc":"Føj til startskærmen for hurtig adgang — virker offline.",
        "instBtn":"Installér",
        "instLater":"Ikke nu",
        "instIos":"Tryk på del-knappen, og vælg «Føj til startskærmen».",
        "nearHigh":"Kursen nær {days}-dages top",
        "nearLow":"Kursen nær {days}-dages bund",
 },
}
